### ISSUE TITLE
Auth sign in nullpointer exception

### ISSUE THREAD

**Issue by apspot** [firebase/FirebaseUI-Android#1005]
I try to login but before the login activity appears the app crashes. I use the device for testing and I have logged in and out several times but today I don't know what happened I'm not able to see the log in screen any more. If I disable smart lock with .setIsSmartLockEnabled(false) it solves the problem. On other 2 devices everything is working fine with enabled smart lock. What can be the problem with my smart lock that worked well until today? Please help! :)

  * Android device: Vernee Thor
  * Android OS version: 7.0
  * Google Play Services version: 11.7.46
  * Firebase/Play Services SDK version: 11.0.2
  * FirebaseUI version: 2.1.0

Exception:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.FragmentManager com.firebase.ui.auth.ui.HelperActivityBase.getSupportFragmentManager()' on a null object reference
  at com.firebase.ui.auth.util.signincontainer.SaveSmartLock.getInstance(SaveSmartLock.java:63)
  at com.firebase.ui.auth.util.AuthHelper.getSaveSmartLockInstance(AuthHelper.java:40)
  at com.firebase.ui.auth.util.signincontainer.IdpSignInContainer.onCreate(IdpSignInContainer.java:88)
  at android.support.v4.app.Fragment.performCreate(Fragment.java:2236)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1285)
  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1569)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1636)
  at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
  at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
  at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2201)
  at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2155)
  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2064)
  at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:718)
  at android.os.Handler.handleCallback(Handler.java:836)
  at android.os.Handler.dispatchMessage(Handler.java:103)
  at android.os.Looper.loop(Looper.java:203)
  at android.app.ActivityThread.main(ActivityThread.java:6251)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
```

Gradle:
```
compile 'com.firebaseui:firebase-ui-auth:2.1.0'
compile 'com.facebook.android:facebook-android-sdk:4.22.1'
compile("com.twitter.sdk.android:twitter-core:3.0.0@aar") { transitive = true }
```

This method is called when a button is clicked:
```
private void login() {
	startActivityForResult(
			AuthUI.getInstance()
					.createSignInIntentBuilder()
					.setAvailableProviders(
							Arrays.asList(new AuthUI.IdpConfig.Builder(AuthUI.EMAIL_PROVIDER).build(),
									new AuthUI.IdpConfig.Builder(AuthUI.GOOGLE_PROVIDER).build(),
									new AuthUI.IdpConfig.Builder(AuthUI.FACEBOOK_PROVIDER).build(),
									new AuthUI.IdpConfig.Builder(AuthUI.TWITTER_PROVIDER).build()))
					.setTheme(R.style.AppTheme)
					.setLogo(R.drawable.logo)
					.setPrivacyPolicyUrl("http://www.mydomain.com/privacy-policy.html")
					.setTosUrl("http://www.mydomain.com/terms-and-conditions.html")
					.build(),
			RC_SIGN_IN);
}
```

strings.xml:
```
<string name="facebook_application_id" translatable="false">numbers</string>
<string name="fb_login_protocol_scheme" translatable="false">fbnumbers</string>
<string name="twitter_consumer_key" translatable="false">lettersandnumbers</string>
<string name="twitter_consumer_secret" translatable="false">lettersandnumbers</string>
```

**Comment by SUPERCILEX** [comment]
Same root cause as https://github.com/firebase/FirebaseUI-Android/issues/856.

**Comment by SUPERCILEX** [comment]
Dup of https://github.com/firebase/FirebaseUI-Android/issues/856.

**Comment by samtstern** [comment]
Thanks!

**Comment by waleedkalyar** [comment]
i will do this code but get java.lang.NullPointerException at   AuthUI.getInstance()
