### ISSUE TITLE
IllegalArgumentException in RegisterEmailActivity

### ISSUE THREAD

**Issue by guytavor** [firebase/FirebaseUI-Android#1036]
```
Fatal Exception: java.lang.IllegalArgumentException: Unique transitionNames are required for all sharedElements
       at android.support.v4.app.BackStackRecord.addSharedElement(SourceFile:511)
       at com.firebase.ui.auth.ui.email.RegisterEmailActivity.onNewUser(SourceFile:127)
       at com.firebase.ui.auth.ui.email.CheckEmailFragment$2.onSuccess(SourceFile:208)
       at com.firebase.ui.auth.ui.email.CheckEmailFragment$2.onSuccess(SourceFile:204)
       at com.google.android.gms.tasks.zzj.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:146)
       at android.app.ActivityThread.main(ActivityThread.java:5593)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
       at dalvik.system.NativeStart.main(NativeStart.java)

```
We are using:
firebase-ui-auth:3.1.0
firebase-auth:11.4.2
GMS v11.4.2
gms:google-services:3.1.0
This seems to only happen on KitKat (api 19), multiple device manufacturers.

the entire crash information is available here: http://crashes.to/s/dfb96808883

We can't reproduce this, as we could not get our hands on an API19 device, but our guess is that this is an android sdk level incompatibility issue.

**Comment by samtstern** [comment]
@guytavor thanks for the report and the API level information, this is definitely a strange crash and I agree with your initial assessment.

**Comment by Lex74** [comment]
We have the same crash with API 17, 18, 19 after updating to
`com.google.firebase:firebase-auth:11.6.2` 
`com.android.support:appcompat-v7:27.0.2`

**Comment by clydebarrow** [comment]
Seeing the same thing on API 19. It is reproduceable in the Android emulator.

**Comment by samtstern** [comment]
This has been fixed and released in `3.1.3`.

**Comment by thippesha** [comment]
I have updated dependency to
// FirebaseUI for Cloud Firestore
implementation 'com.firebaseui:firebase-ui-firestore:3.3.0'

// FirebaseUI for Firebase Auth
implementation 'com.firebaseui:firebase-ui-auth:3.3.0'

But still, I am getting same issues on 

Devices
samsung50%
HTC25%
Micromax25%
Operating Systems
4.4.2  / 4.4.4

Fatal Exception: java.lang.IllegalArgumentExceptionUnique transitionNames are required for all sharedElements Raw Text
--
  | android.support.v4.app.BackStackRecord.dump (Unknown Source)
  | com.firebase.ui.auth.ui.email.RegisterEmailActivity.onNewUser (Unknown Source)
  | com.firebase.ui.auth.ui.email.CheckEmailFragment$2.onSuccess (Unknown Source)
  | com.firebase.ui.auth.ui.email.CheckEmailFragment$2.onSuccess (Unknown Source)
  | com.google.android.gms.tasks.zzj.run (Unknown Source)
  | dalvik.system.NativeStart.main (NativeStart.java)

**Comment by samtstern** [comment]
@thippesha are you 100% sure that the devices crashing are running Firebase UI `3.3.0` ?

**Comment by thippesha** [comment]
@samtstern
Oh sorry, Today only reverified, after your reply, I was not updated both def to 3.3.
// FirebaseUI for Cloud Firestore
implementation 'com.firebaseui:firebase-ui-firestore:3.3.0'

// FirebaseUI for Firebase Auth
implementation 'com.firebaseui:firebase-ui-auth:3.3.0'

Sorry it's my mistake
Thank you
