### ISSUE TITLE
Class cast exception with android.arch.lifecycle.GeneratedAdapter

### ISSUE THREAD

**Issue by emarc-m** [firebase/FirebaseUI-Android#1043]
* Android device: Emulator
  * Android OS version: 25 with Google Play
  * Google Play Services version: 11.9.51
  * Firebase/Play Services SDK version: 11.6.2
  * FirebaseUI version: 3.1.0
  
### Step 3: Describe the problem:

App crash on Firebase UI update with class cast exception

#### Steps to reproduce:

  1. Update from 3.0.0 to 3.1.0
  2. Open activity with FirebaseRecyclerAdapter
  3. App crashes
  
#### Observed Results:

```
Process: jp.co.sankeiliving.android.debug, PID: 14695
                                                                                  java.lang.ClassCastException: com.firebase.ui.database.FirebaseRecyclerAdapter_LifecycleAdapter cannot be cast to android.arch.lifecycle.GeneratedAdapter
                                                                                      at android.arch.lifecycle.Lifecycling.createGeneratedAdapter(Lifecycling.java:79)
                                                                                      at android.arch.lifecycle.Lifecycling.getCallback(Lifecycling.java:62)
                                                                                      at android.arch.lifecycle.LifecycleRegistry$ObserverWithState.<init>(LifecycleRegistry.java:346)
                                                                                      at android.arch.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:162)
                                                                                      at com.firebase.ui.database.FirebaseRecyclerAdapter.<init>(FirebaseRecyclerAdapter.java:40)
                                                                                      at jp.co.sankeiliving.android.chat.view.ChatAdapter.<init>(ChatAdapter.java:136)
                                                                                      at jp.co.sankeiliving.android.chat.view.ChatAdapterFactory.create(ChatAdapterFactory.java:24)
                                                                                      at jp.co.sankeiliving.android.chat.ChatActivity.onChatRoomLoaded(ChatActivity.java:233)
                                                                                      at jp.co.sankeiliving.android.chat.presenter.ChatActivityPresenter.onChatRoomLoaded(ChatActivityPresenter.java:105)
                                                                                      at jp.co.sankeiliving.android.chat.presenter.ChatActivityPresenter.bridge$lambda$0$ChatActivityPresenter(ChatActivityPresenter.java)
                                                                                      at jp.co.sankeiliving.android.chat.presenter.ChatActivityPresenter$$Lambda$1.onSuccess(Unknown Source)
                                                                                      at jp.co.sankeiliving.android.common.async.Async$Task.lambda$null$0$Async$Task(Async.java:251)
                                                                                      at jp.co.sankeiliving.android.common.async.Async$Task$$Lambda$1.run(Unknown Source)
                                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
  
#### Expected Results:

Should not crash
  
#### Relevant Code:

Adapter extends FirebaseRecyclerAdapter
  ```
  super(new FirebaseRecyclerOptions.Builder<ChatMessage>()
                .setQuery(reference, ChatMessage.class)
                .setLifecycleOwner(owner)
                .build());
  ```

**Comment by SUPERCILEX** [comment]
Have you tried running a `./gradlew clean`? That might help.

**Comment by emarc-m** [comment]
@SUPERCILEX yes I did the clean build. same issue.

**Comment by emarc-m** [comment]
I found that Glide causes the crash. I've recently upgrade to Glide v4.4.0. My temporary fix is to use a previous version v4.3.1. I'll post once I can investigate further. I'm still not sure what causes the issue.

**Comment by Lihacovs** [comment]
Hello, had the same issue. Removing FirestoreRecyclerOptions.Builder#setLifecycleOwner(...) method from FRO builder, and starting in onStart(), onStop() helped in my case:
```
    @Override
    public void onStart() {
        super.onStart();
        mFreePostsAdapter.startListening();

    }

    @Override
    public void onStop() {
        super.onStop();
        mFreePostsAdapter.stopListening();
    }
```
I had no time to investigate what caused the issue, would be interesting to know it

**Comment by samtstern** [comment]
If any of you is still experiencing the crash could you show your `build.gradle`?

**Comment by SUPERCILEX** [comment]
@samtstern I'm pretty sure this issue is fixed in `v3.1.1` since we upgraded to Arch Components 1.0.

Everyone else: make sure to upgrade to FUI `v3.1.1`, and please let us know if the crash still occurs on that version.

**Comment by emarc-m** [comment]
@SUPERCILEX I can confirm that ```v3.1.1``` fixes the problem. Do you have the reference issue or commit regarding to what was the cause? I'll close this issue. Thanks

**Comment by SUPERCILEX** [comment]
@emarc-m It was just a simple matter of upgrading to the stable version of AAC. The alpha version used a different class for the annotation processing, hence the CCE.

**Comment by emarc-m** [comment]
@SUPERCILEX Thanks!

Note: 
AAC = Android Architecture Components,
CCE = Class Cast Exception

**Comment by SUPERCILEX** [comment]
@emarc-m Haha, yeah, sorry for the acronyms. 😊
