### ISSUE TITLE
Demo app does not run unmodified

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#11]
I did the following:

  * `git clone` the repo
  * Open the app in Android Studio by doing **File > Open > FirebaseUI-Android > build.gradle`
  * Run the app by clicking **Run > Run 'app'**

The app displays briefly, and then crashes with the following logcat:
```
08-28 15:04:43.933  30224-30224/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.firebase.uidemo, PID: 30224
    java.lang.RuntimeException: java.lang.IllegalAccessException: java.lang.Class<com.firebase.uidemo.RecyclerViewDemoActivity$ChatHolder> is not accessible from java.lang.Class<com.firebase.ui.FirebaseRecyclerViewAdapter>
            at com.firebase.ui.FirebaseRecyclerViewAdapter.onCreateViewHolder(FirebaseRecyclerViewAdapter.java:174)
            at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5116)
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4416)
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4326)
            at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1955)
            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1364)
            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1327)
            at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:556)
            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2713)
            at android.support.v7.widget.RecyclerView.resumeRequestLayout(RecyclerView.java:1560)
            at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:275)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
            at android.view.Choreographer.doCallbacks(Choreographer.java:670)
            at android.view.Choreographer.doFrame(Choreographer.java:603)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.IllegalAccessException: java.lang.Class<com.firebase.uidemo.RecyclerViewDemoActivity$ChatHolder> is not accessible from java.lang.Class<com.firebase.ui.FirebaseRecyclerViewAdapter>
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at com.firebase.ui.FirebaseRecyclerViewAdapter.onCreateViewHolder(FirebaseRecyclerViewAdapter.java:166)
            at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5116)
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4416)
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4326)
            at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1955)
            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1364)
            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1327)
            at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:556)
            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2713)
            at android.support.v7.widget.RecyclerView.resumeRequestLayout(RecyclerView.java:1560)
            at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:275)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
            at android.view.Choreographer.doCallbacks(Choreographer.java:670)
            at android.view.Choreographer.doFrame(Choreographer.java:603)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by puf** [comment]
Hey Sam, Thanks for the report. I'd heard this once before, but had been unable to reproduce it. I just pushed a change that makes the ChatHolder and Chat classes public. Please give it a try.

**Comment by samtstern** [comment]
FYI that did fix it, thanks!

**Comment by andrewsosa001** [comment]
In the README, the code sample still has the ChatMessageViewHolder as a private class. Should it be declared public?
