### ISSUE TITLE
Caused by: java.lang.RuntimeException: Found conflicting setters with name: setWallpaper

### ISSUE THREAD

**Issue by PhilippeBoisney** [firebase/FirebaseUI-Android#1100]
### Describe your environment

  * Android device: Samsung S8
  * Android OS version: 7.0
  * Google Play Services version: 8.5
  * Firebase/Play Services SDK version: 11.8.0
  * FirebaseUI version: 3.1.3
### Describe the problem:
When I try to add a CollectionReference to an object (Room.java) via it's constructor, and store it to Firebase to create a reference to a collection, a RuntimeException is thrown.

#### Relevant Code:

```java
public class Room {
    private String uid;
    private DocumentReference userStudent;
    private DocumentReference userTeacher;
    private CollectionReference messages;

    public Room() { }

    public Room(String uid, DocumentReference userStudent, DocumentReference userTeacher, CollectionReference messages) {
        this.uid = uid;
        this.userStudent = userStudent;
        this.userTeacher = userTeacher;
        this.messages = messages; // THIS SEEMS TO CREATE THE EXCEPTION
    }

    // --- GETTERS ---
    public String getUid() { return uid; }
    public DocumentReference getUserStudent() { return userStudent; }
    public DocumentReference getUserTeacher() { return userTeacher; }
    public CollectionReference getMessages() { return messages; }

    // --- SETTERS ---
    public void setUid(String uid) { this.uid = uid; }
    public void setUserStudent(DocumentReference userStudent) { this.userStudent = userStudent; }
    public void setUserTeacher(DocumentReference userTeacher) { this.userTeacher = userTeacher; }
    public void setMessages(CollectionReference messages) { this.messages = messages; }
}
```
And next, when I try to store a new Room object in Firestore from an activity, a RuntimeException is thrown.

```java
CollectionReference messagesCollection = FirebaseFirestore.getInstance().collection("rooms").document(roomID).collection("messages");

// CREATE TEST ROOM
Room roomForTwoUsers = new Room(roomID, mentorRef, studentRef, messagesCollection);

// ADDING TEST ROOM TO FIRESTORE
CollectionReference roomsCollection = FirebaseFirestore.getInstance().collection("rooms");
roomsCollection.document(roomForTwoUsers.getUid()).set(roomForTwoUsers).addOnFailureListener(this, this.onFailureListener()); // THIS LINE THROW THE EXCEPTION
```

Here is the preview of stacktrace 

```
FATAL EXCEPTION: main
                                                                             Process: com.openclassrooms.firebaseoc, PID: 6296
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.openclassrooms.firebaseoc/com.openclassrooms.firebaseoc.storage.SearchActivity}: java.lang.RuntimeException: Found conflicting setters with name: setWallpaper (conflicts with setWallpaper defined on android.content.ContextWrapper)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2924)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
                                                                                 at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                                                                              Caused by: java.lang.RuntimeException: Found conflicting setters with name: setWallpaper (conflicts with setWallpaper defined on android.content.ContextWrapper)
                                                                                 at com.google.android.gms.internal.zzetm$zza.<init>(Unknown Source)
                                                                                 at com.google.android.gms.internal.zzetm.zzg(Unknown Source)
                                                                                 at com.google.android.gms.internal.zzetm.zza(Unknown Source)
                                                                                 at com.google.android.gms.internal.zzetm.zzd(Unknown Source)
                                                                                 at com.google.android.gms.internal.zzetm$zza.zze(Unknown Source)
                                                                                 at com.google.android.gms.internal.zzetm.zza(Unknown Source)
                                                                                 at com.google.android.gms.internal.zzetm.zzd(Unknown Source)
                                                                                 at com.google.android.gms.internal.zzetm$zza.zze(Unknown Source)
                                                                                 at com.google.android.gms.internal.zzetm.zza(Unknown Source)
                                                                                 at com.google.android.gms.internal.zzetm.zzd(Unknown Source)
                                                                                 at com.google.android.gms.internal.zzetm$zza.zze(Unknown Source)
                                                                                 at com.google.android.gms.internal.zzetm.zza(Unknown Source)
                                                                                 at com.google.android.gms.internal.zzetm.zza(Unknown Source)
                                                                                 at com.google.android.gms.internal.zzetm.zzbv(Unknown Source)
                                                                                 at com.google.firebase.firestore.zzk.zzcc(Unknown Source)
                                                                                 at com.google.firebase.firestore.DocumentReference.set(Unknown Source)
                                                                                 at com.openclassrooms.firebaseoc.storage.SearchActivity.createDatas(SearchActivity.java:80)
                                                                                 at com.openclassrooms.firebaseoc.storage.SearchActivity.onCreate(SearchActivity.java:40)
                                                                                 at android.app.Activity.performCreate(Activity.java:6912)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2877)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985) 
                                                                                 at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:154) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6692) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 
```

However, If I remove in the Room constructor the CollectionReference, it seems to work (But without creating the reference, of course...)

```java
public class Room {
    private String uid;
    private DocumentReference userStudent;
    private DocumentReference userTeacher;
    private CollectionReference messages;

    public Room() { }

    public Room(String uid, DocumentReference userStudent, DocumentReference userTeacher) {
        this.uid = uid;
        this.userStudent = userStudent;
        this.userTeacher = userTeacher;
    }

    ...
}
```

Is it me who don't understand CollectionReference or something goes wrong with the library ?

**Comment by samtstern** [comment]
@PhilippeBoisney thanks for the report.  Right now you can only store a `DocumentReference` as part of a document, a `CollectionReference` will cause an error.

I am going to close this issue since there's nothing FirebaseUI can do but I will file two requests internally:

  1. This should result in a much better error message.
  2. This should probably be supported in the long term.
