### ISSUE TITLE
Removing item from FirestoreRecyclerAdapter

### ISSUE THREAD

**Issue by dharan1011** [firebase/FirebaseUI-Android#1131]
### Step 1: Are you in the right place?
Yes
### Step 2: Describe your environment

  * Android device: Google Pixel AVD in macOs
  * Android OS version: 23
  * Firebase/Play Services SDK version: 11.8.0
  * FirebaseUI version: 3.2.1
  
### Step 3: Describe the problem:
I am using `FirestoreRecyclerAdapter` to retrieve data from Firestore and populate my recyclerview. Also I have used `ItemTouchHelper` to remove item dynamically  from recycler view when item is swiped to right. So i am storing the position of item in using `holder.itemView.setTag(position);` and retrieving position of item in 'ItemTouchHelper' using 'viewHolder.itemView.getTag();' and using the position to Remove the document from collection. But when I remove list item randomly and quickly the size of `BaseObservableSnapshotArray` changes but the cached position of object in `itemView.getTag()` doesn't changes so my app crashes. Is there any efficient logic to remove item from recyclerview using 'FirestoreRcyclerAdapter' and handle the offline scenario.
#### Steps to reproduce:

  1. Implement a RecyclerView and attach a FirestoreRecyclerAdapter.
  2. Attack a ItemTouchHelper to recyclerview then trigger when item is swiped
  3. Add logic to remove document of collection based on item's index.
  4. Remoce item at random position and quickly
  
#### Observed Results:

```
FATAL EXCEPTION: main
                                                                                      Process: com.dharanaditya.firestorequickstart, PID: 22442
                                                                                      java.lang.IndexOutOfBoundsException: Invalid index 8, size is 6
                                                                                          at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                          at java.util.ArrayList.get(ArrayList.java:308)
                                                                                          at com.firebase.ui.common.BaseObservableSnapshotArray.getSnapshot(BaseObservableSnapshotArray.java:70)
                                                                                          at com.dharanaditya.firestorequickstart.MainActivity$2.onSwiped(MainActivity.java:128)
                                                                                          at android.support.v7.widget.helper.ItemTouchHelper$4.run(ItemTouchHelper.java:692)
                                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```
  
#### Expected Results:

  Removal of RecyclerView item when Swiped Right when swiped to right at any pace and index.
  
#### Relevant Code:

  ```
        Query query = mFirestore.collection("chat")
                .orderBy("timestamp", Query.Direction.DESCENDING);

        FirestoreRecyclerOptions<Chat> options = new FirestoreRecyclerOptions.Builder<Chat>()
                .setQuery(query, Chat.class)
                .build();
        mAdapter = new FirestoreRecyclerAdapter<Chat, ChatViewHolder>(options) {
            @Override
            public ChatViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
                View v = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_chat, parent, false);
                return new ChatViewHolder(v);
            }

            @Override
            protected void onBindViewHolder(@NonNull ChatViewHolder holder, int position, @NonNull Chat model) {
                holder.itemView.setTag(position);
                holder.bind(model.getName(), model.getMessage(), model.getTimestamp());
            }

            @Override
            public int getItemCount() {
                return super.getItemCount();
            }

            @Override
            public void onDataChanged() {
                super.onDataChanged();
                mRecyclerView.scrollToPosition(0);
            }

        };
        mRecyclerView.setLayoutManager(new LinearLayoutManager(this));
        mRecyclerView.setAdapter(mAdapter);
        mAdapter.startListening();

        new ItemTouchHelper(new ItemTouchHelper.SimpleCallback(0, ItemTouchHelper.RIGHT) {
            @Override
            public boolean onMove(RecyclerView recyclerView, RecyclerView.ViewHolder viewHolder, RecyclerView.ViewHolder target) {
                return false;
            }

            @Override
            public void onSwiped(RecyclerView.ViewHolder viewHolder, int direction) {
                int pos = (int) viewHolder.itemView.getTag();
                DocumentSnapshot snapshot = (DocumentSnapshot) mAdapter.getSnapshots().getSnapshot(pos);
                mFirestore.collection("chat")
                        .document(snapshot.getId())
                        .delete()
                        .addOnSuccessListener(new OnSuccessListener<Void>() {
                            @Override
                            public void onSuccess(Void aVoid) {
                                Log.d(TAG, "onSuccess: Removed list item");
                            }
                        })
                        .addOnFailureListener(new OnFailureListener() {
                            @Override
                            public void onFailure(@NonNull Exception e) {
                                Log.d(TAG, "onFailure: "+e.getLocalizedMessage());
                            }
                        });
            }
        }).attachToRecyclerView(mRecyclerView);
  ```

**Comment by dharan1011** [comment]
Just went through the documentation and hacked a way through them to resolve the issue. 
- In the chat model class added a Field `
private @Exclude String documentId;
` to store the document id of the document in chat collection. 
- In `FirestoreRecyclerOptions` make use of `SnapshotParser `, retrieve document id from `DocumentSnapshot ` and set it to `Chat` object and return it.
- In `FirestoreRecyclerAdapter#onBindViewHolder()` make use of `ViewHolder.itemView#setTag()` method to save the documentId in `ViewHolder`.
- Now in `ItemTouchHelper#onSwiped()` retrive the documentId  using `ViewHolder.itemView#getTag()` and remove it from collection.

## Solution
```
        Query query = mFirestore.collection("chat")
                .orderBy("timestamp", Query.Direction.DESCENDING);

        FirestoreRecyclerOptions<Chat> options = new FirestoreRecyclerOptions.Builder<Chat>()
                .setQuery(query, new SnapshotParser<Chat>() {
                    @NonNull
                    @Override
                    public Chat parseSnapshot(@NonNull DocumentSnapshot snapshot) {
                        Chat chat = snapshot.toObject(Chat.class);
                        chat.setDocumentId(snapshot.getId());
                        return chat;
                    }
                })
                .setLifecycleOwner(this)
                .build();
        mAdapter = new FirestoreRecyclerAdapter<Chat, ChatViewHolder>(options) {
            @Override
            public ChatViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
                View v = LayoutInflater.from(parent.getContext()).inflate(R.layout.item_chat, parent, false);
                return new ChatViewHolder(v);
            }

            @Override
            protected void onBindViewHolder(@NonNull ChatViewHolder holder, int position, @NonNull Chat model) {
                holder.itemView.setTag(model.getDocumentId());
                holder.bind(model.getName(), model.getMessage(), model.getTimestamp());
            }
        };
        mRecyclerView.setLayoutManager(new LinearLayoutManager(this));
        mRecyclerView.setAdapter(mAdapter);

        new ItemTouchHelper(new ItemTouchHelper.SimpleCallback(0, ItemTouchHelper.RIGHT) {
            @Override
            public boolean onMove(RecyclerView recyclerView, RecyclerView.ViewHolder viewHolder, RecyclerView.ViewHolder target) {
                return false;
            }

            @Override
            public void onSwiped(RecyclerView.ViewHolder viewHolder, int direction) {
                String documentId = (String) viewHolder.itemView.getTag();
                mFirestore.collection("chat")
                        .document(documentId)
                        .delete()
                        .addOnSuccessListener(new OnSuccessListener<Void>() {
                            @Override
                            public void onSuccess(Void aVoid) {
                                Log.d(TAG, "onSuccess: Removed list item");
                            }
                        })
                        .addOnFailureListener(new OnFailureListener() {
                            @Override
                            public void onFailure(@NonNull Exception e) {
                                Log.d(TAG, "onFailure: " + e.getLocalizedMessage());
                            }
                        });
                mAdapter.notifyDataSetChanged();

            }
        }).attachToRecyclerView(mRecyclerView);
```

**Comment by samtstern** [comment]
@dharan1011 your solution sounds right to me: delete the item from the collection and let the adapter handle the deletion event.  Thanks for sharing!

**Comment by godslave05** [comment]
What will happen if you try to delete in offline mode

**Comment by pratikbutani** [comment]
@dharan1011 How to add `documentId` in document?
