### ISSUE TITLE
Error: "A TaskDescription's primary color should be opaque" when using Firebase Auth UI

### ISSUE THREAD

**Issue by ShaldonSwiidAppDesigns** [firebase/FirebaseUI-Android#1139]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 2: Describe your environment

  * Android device: Tablet
  * Android OS version: 6.0
  * Google Play Services version:11.8.0
  * Firebase/Play Services SDK version: 11.8.0
  * FirebaseUI version: 3.1.0
  
#### Steps to reproduce:

  1. Ran the Firebase Auth UI on a Tablet on Android 6.0 using Theme: AppTheme
  2. Error Thrown
  
#### Observed Results:

```
  java.lang.RuntimeException: Unable to start activity ComponentInfo{swiidappdesigns.haveasafetrip/com.firebase.ui.auth.KickoffActivity}: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2583)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2665)
                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1499)
                      at android.os.Handler.dispatchMessage(Handler.java:111)
                      at android.os.Looper.loop(Looper.java:207)
                      at android.app.ActivityThread.main(ActivityThread.java:5766)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                   Caused by: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
                      at android.app.ActivityManager$TaskDescription.<init>(ActivityManager.java:601)
                      at android.app.Activity.onApplyThemeResource(Activity.java:3774)
                      at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:150)
                      at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:94)
                      at android.support.v7.app.AppCompatActivity.setTheme(AppCompatActivity.java:89)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2523)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2665) 
                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1499) 
                      at android.os.Handler.dispatchMessage(Handler.java:111) 
                      at android.os.Looper.loop(Looper.java:207) 
                      at android.app.ActivityThread.main(ActivityThread.java:5766) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)   
```

#### Expected Results:

  Auth UI was meant to popup
  
#### Relevant Code:
Main.java:
```java
// Create and launch sign-in intent for a passenger
                                        startActivityForResult(
                                                AuthUI.getInstance()
                                                        .createSignInIntentBuilder()
                                                        .setAvailableProviders(providers)
                                                        .setLogo(R.mipmap.ic_splash)
                                                        .setTheme(R.style.AppTheme)
                                                        .build(),
                                                RC_SIGN_IN);
                                    }
```

Value styles.xml:

```xml
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:actionMenuTextColor">@color/tw__solid_white</item>
    </style>

    <style name="AppThemeNoActionBar" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimaryDark">@color/colorBlackTransparent</item>
         <item name="colorAccent">@color/colorAccent</item>
         <item name="colorPrimary">@color/colorBlackTransparent</item>
        <item name="android:windowContentOverlay">@null</item>
        <item name="windowActionBarOverlay">true</item>

    </style>

    <style name="AppTheme.NoActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
    </style>

    <style name="AppTheme.AppBarOverlay" parent="ThemeOverlay.AppCompat.Dark.ActionBar" />

    <style name="AppTheme.PopupOverlay" parent="ThemeOverlay.AppCompat.Light" />

</resources>
```

v21 styles.xml:

```xml
<resources>
    <style name="AppTheme" parent="Base.V21.Theme.AppCompat">
        <item name="colorPrimaryDark">#403C3A</item>
        <item name="colorPrimary">#7A7674</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:actionMenuTextColor">@color/tw__solid_white</item>
    </style>

    <style name="AppThemeNoActionBar" parent="Base.V21.Theme.AppCompat.Light">
        <item name="colorPrimaryDark">#403C3A</item>
        <item name="colorPrimary">#7A7674</item>
       <item name="android:windowContentOverlay">@null</item>
        <item name="windowActionBarOverlay">true</item>
    </style>

    <style name="AppTheme.NoActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
    </style>

    <style name="AppTheme.AppBarOverlay" parent="ThemeOverlay.AppCompat.Dark.ActionBar" />

    <style name="AppTheme.PopupOverlay" parent="ThemeOverlay.AppCompat.Light" />
</resources>
```

**Comment by samtstern** [comment]
Your problem is this:

```
        <item name="colorPrimaryDark">@color/colorBlackTransparent</item>
         <item name="colorAccent">@color/colorAccent</item>
         <item name="colorPrimary">@color/colorBlackTransparent</item>
```

You can't use a transparent color as your primary color in AppCompat, it can cause this crash (along with some others).

Closing as this is not an issue with FirebaseUI specifically.

**Comment by ShaldonSwiidAppDesigns** [comment]
Hi Sam Please hang on before you close it. It works just fine with my Android 7.0. It only doesn't work with Android 5.0 and 6.0

**Comment by ShaldonSwiidAppDesigns** [comment]
Please unclose this as this is in fact a Firebase UI issue

**Comment by ShaldonSwiidAppDesigns** [comment]
com.firebase.ui.auth.KickoffActivity

**Comment by ShaldonSwiidAppDesigns** [comment]
Please see my error log as it states it is being called from an issue when I open the UI

**Comment by ShaldonSwiidAppDesigns** [comment]
Sam?? Please man I need this as it is a work query. I have a Tablet with Android Version 6.0 and a Samsung Galaxy S7 Edge with Android Version 7.0. The Tablet runs fine until I select the login to direct my users to the Auth UI and the it crashes. My Samsung with the exact same code runs perfectly with no crashes

**Comment by ShaldonSwiidAppDesigns** [comment]
You can close this issue. I figured out with @morganchen12 help that I needed to change my primary color inside of the colors.xml file and not the values.xml file. However I still believe this is an issue with Firebase UI not allowing for transparency values.

**Comment by am9072** [comment]
ell..!! this is the error only because of primary color opaqueness

go to your res-->values-->color.xml
and remove two digits of primary color

watch video for more easiness.
https://youtu.be/pLO9KzxG--k
