### ISSUE TITLE
Error: "A TaskDescription's primary color should be opaque" when using Firebase Auth UI

### ISSUE THREAD

**Issue by ShaldonSwiidAppDesigns** [firebase/FirebaseUI-Android#1140]
### Step 2: Describe your environment

  Android device: Tablet and Samsung Galaxy S7 Edge
Android OS version: 6.0 and 7.0
Google Play Services version:11.8.0
Firebase/Play Services SDK version: 11.8.0
FirebaseUI version: 3.1.0
  
#### Steps to reproduce:

  1.Ran a login that redirects to  Firebase Auth UI on a Tablet running Android 6.0 using Theme: AppTheme. Error Thrown when selecting to login through Firebase Auth UI.
  2. Ran the exact same code on my Samsung running Android 7.0. Works like a charm.
  
#### Observed Results:

java.lang.RuntimeException: Unable to start activity ComponentInfo{swiidappdesigns.haveasafetrip/com.firebase.ui.auth.KickoffActivity}: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2583)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2665)
                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1499)
                      at android.os.Handler.dispatchMessage(Handler.java:111)
                      at android.os.Looper.loop(Looper.java:207)
                      at android.app.ActivityThread.main(ActivityThread.java:5766)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                   Caused by: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
                      at android.app.ActivityManager$TaskDescription.<init>(ActivityManager.java:601)
                      at android.app.Activity.onApplyThemeResource(Activity.java:3774)
                      at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:150)
                      at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:94)
                      at android.support.v7.app.AppCompatActivity.setTheme(AppCompatActivity.java:89)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2523)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2665) 
                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1499) 
                      at android.os.Handler.dispatchMessage(Handler.java:111) 
                      at android.os.Looper.loop(Looper.java:207) 
                      at android.app.ActivityThread.main(ActivityThread.java:5766) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)   
  
#### Expected Results:

Run exactly like it did on my Samsung Galaxy S7 Edge Android 7.0. I understand the situation of the opaque having an issue with Android versions lower than Android 7.0. However I have set my stylesv21 to have only opaque values as the Primary values. But as you can see, even with the stylesv21 set to opaque, I still have the issue.
  
#### Relevant Code:
Main.java:
// Create and launch sign-in intent for a passenger
                                        startActivityForResult(
                                                AuthUI.getInstance()
                                                        .createSignInIntentBuilder()
                                                        .setAvailableProviders(providers)
                                                        .setLogo(R.mipmap.ic_splash)
                                                        .setTheme(R.style.AppTheme)
                                                        .build(),
                                                RC_SIGN_IN);
                                    }

Value styles.xml:
<resources>

    
    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:actionMenuTextColor">@color/tw__solid_white</item>
    </style>

    <style name="AppThemeNoActionBar" parent="Theme.AppCompat.Light.NoActionBar">
        
        <item name="colorPrimaryDark">@color/colorBlackTransparent</item>
         <item name="colorAccent">@color/colorAccent</item>
         <item name="colorPrimary">@color/colorBlackTransparent</item>
        <item name="android:windowContentOverlay">@null</item>
        <item name="windowActionBarOverlay">true</item>

    </style>

    <style name="AppTheme.NoActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
    </style>

    <style name="AppTheme.AppBarOverlay" parent="ThemeOverlay.AppCompat.Dark.ActionBar" />

    <style name="AppTheme.PopupOverlay" parent="ThemeOverlay.AppCompat.Light" />

</resources>

v21 styles.xml:

<resources>
    <style name="AppTheme" parent="Base.V21.Theme.AppCompat">
        <item name="colorPrimaryDark">#403C3A</item>
        <item name="colorPrimary">#7A7674</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:actionMenuTextColor">@color/tw__solid_white</item>
    </style>

    <style name="AppThemeNoActionBar" parent="Base.V21.Theme.AppCompat.Light">
        <item name="colorPrimaryDark">#403C3A</item>
        <item name="colorPrimary">#7A7674</item>
       <item name="android:windowContentOverlay">@null</item>
        <item name="windowActionBarOverlay">true</item>
    </style>

    <style name="AppTheme.NoActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
    </style>

    <style name="AppTheme.AppBarOverlay" parent="ThemeOverlay.AppCompat.Dark.ActionBar" />

    <style name="AppTheme.PopupOverlay" parent="ThemeOverlay.AppCompat.Light" />
</resources>

@samtstern please before you close this matter, hear me out. I am creating this issue again but with more explanation this time. As I said above, it works perfectly on my Samsung Galaxy S7 Edge Android 7.0 however with my Tablet Android 6.0 the Firebase Auth UI is the one that crashes.

**Comment by ShaldonSwiidAppDesigns** [comment]
Can I ask why this matter, yet again, has been closed?

**Comment by morganchen12** [comment]
Though the crash may happen when launching FirebaseUI's auth flow, the cause of the crash itself is not necessarily within FirebaseUI.

**Comment by ShaldonSwiidAppDesigns** [comment]
@morganchen12 where else would it be coming from then if the exact same code works on Andorid 7.0 when calling the tartActivityForResult(
AuthUI.getInstance()
.createSignInIntentBuilder()
.setAvailableProviders(providers)
.setLogo(R.mipmap.ic_splash)
.setTheme(R.style.AppTheme)
.build(),
RC_SIGN_IN);  and not on when calling the exact same code on Android 6.0?

**Comment by morganchen12** [comment]
Try not using a transparent color as your main color in AppCompat. Begging for changes without addressing the root cause of your crash is not a good way to get help from library maintainers within or outside of Firebase.

Also, lack of crashes on legacy platforms is not necessarily an indicator that there aren't any incompatibility issues. Usually silent failures are _upgraded_ to crashes in later versions, since it's better to crash with a straightforward error message than to mask potential errors later.

**Comment by ShaldonSwiidAppDesigns** [comment]
@morganchen12 I do understand what you are saying. I just don't understand why the exact same code works for one OS and not the other if the OS changes had nothing to do with the UI. I will run my opaque values inside of my primary color values and see if they had any effect on this issue.

**Comment by ShaldonSwiidAppDesigns** [comment]
@morganchen12 I just ran the code again with the opaque values and it still crashes

**Comment by ShaldonSwiidAppDesigns** [comment]
Styles.xml
<resources>

    
    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:actionMenuTextColor">@color/tw__solid_white</item>
    </style>

    <style name="AppThemeNoActionBar" parent="Theme.AppCompat.Light.NoActionBar">
        
        <item name="colorPrimaryDark">#403C3A</item>
         <item name="colorAccent">@color/colorAccent</item>
         <item name="colorPrimary">#7A7674</item>
        <item name="android:windowContentOverlay">@null</item>
        <item name="windowActionBarOverlay">true</item>

    </style>

    <style name="AppTheme.NoActionBar">
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
    </style>

    <style name="AppTheme.AppBarOverlay" parent="ThemeOverlay.AppCompat.Dark.ActionBar" />

    <style name="AppTheme.PopupOverlay" parent="ThemeOverlay.AppCompat.Light" />

</resources>

**Comment by ShaldonSwiidAppDesigns** [comment]
Error Code yet again:
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: swiidappdesigns.haveasafetrip, PID: 2583
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{swiidappdesigns.haveasafetrip/com.firebase.ui.auth.KickoffActivity}: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2583)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2665)
                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1499)
                      at android.os.Handler.dispatchMessage(Handler.java:111)
                      at android.os.Looper.loop(Looper.java:207)
                      at android.app.ActivityThread.main(ActivityThread.java:5766)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                   Caused by: java.lang.RuntimeException: A TaskDescription's primary color should be opaque
                      at android.app.ActivityManager$TaskDescription.<init>(ActivityManager.java:601)
                      at android.app.Activity.onApplyThemeResource(Activity.java:3774)
                      at android.view.ContextThemeWrapper.initializeTheme(ContextThemeWrapper.java:150)
                      at android.view.ContextThemeWrapper.setTheme(ContextThemeWrapper.java:94)
                      at android.support.v7.app.AppCompatActivity.setTheme(AppCompatActivity.java:89)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2523)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2665) 
                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1499) 
                      at android.os.Handler.dispatchMessage(Handler.java:111) 
                      at android.os.Looper.loop(Looper.java:207) 
                      at android.app.ActivityThread.main(ActivityThread.java:5766) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by ShaldonSwiidAppDesigns** [comment]
@morganchen12 Do you see now that even when I changed my values to opaque values. It still throws this error? This is only happening with my Android 6.0 Tablet

**Comment by morganchen12** [comment]
This needs to be the case for **all** of your primary colors.

Since this isn't an issue with FirebaseUI, consider posting a question on StackOverflow instead.

**Comment by ShaldonSwiidAppDesigns** [comment]
@morganchen12 Ah ha you genius. I overlooked the colors.xml when I changed the values. Changing it inside of this file works, the other change inside of the values.xml file didn't make the change. Still though, wish they allowed for transparency inside of OS 6.

**Comment by samtstern** [comment]
Thank you @morganchen12 for your patience and guidance here.

@ShaldonSwiidAppDesigns I am glad you solved your issue, but please note that this interaction has not been a good example of open-source conduct:

  * Do not file two identical issues (#1139 and #1140).
  * When filing an issue you need to provide some proof that there is a problem within the library, in this case the error description pointed at your app code and StackOverflow had the answers.
  * Github is not a place for back-and-forth support, there are hundreds of thousands of firebase developers out there and we have only a few people watching Github!  We do our best, but spamming comments and pleading does not really change the facts.

**Comment by ShaldonSwiidAppDesigns** [comment]
@samtstern @morganchen12  I understand, I am still new to this. However I still believe there is in fact an issue here with the Firebase Auth UI as stated in my duplicate issue #1139. That with the transparency field set in the Primary color value on Android 7.0 it works perfectly, Firebase Auth UI only crashes when it comes to the Android 6.0 version when calling the exact same code with the transparency value inside of the Primary Colors field

**Comment by ShaldonSwiidAppDesigns** [comment]
@samstern @morganchen12 just one more thing to make you understand why I am saying that the transparency issue is a Firebase Auth UI issue. Is that transparency works for Android 6.0 on all of my other activities. The only activity it does not work on is when you open the Firebase Auth UI. Just saying. It may in fact be a good idea to investigate this a bit further.

**Comment by am9072** [comment]
well..!! this is the error only because of primary color opaqueness

go to your res-->values-->color.xml

`<color name="colorPrimary">#29FAB5CC</color>`

remove any two charachters

`<color name="colorPrimary">#29F5CC</color>`

watch video for more easiness.
[https://youtu.be/pLO9KzxG--k](url)
