### ISSUE TITLE
Unable to get Email from facebook login.

### ISSUE THREAD

**Issue by yokei15** [firebase/FirebaseUI-Android#1144]
**Unable to get Email via Facebook login gets crashed**

Permission for email is also mentioned but cant able to figure it out

```
private static final String EMAIL = "email";
CallbackManager = CallbackManager.Factory.create();
FirebaseAuth  mAuth = FirebaseAuth.getInstance();
LoginButton loginButton = (LoginButton) findViewById(R.id.login_button);
        loginButton.setReadPermissions(Arrays.asList(EMAIL));
        // Callback registration
        loginButton.registerCallback(callbackManager, new FacebookCallback<LoginResult>() {
            @Override
            public void onSuccess(LoginResult loginResult) {
                // App code
                handleFacebookAccessToken(loginResult.getAccessToken());
            }

            @Override
            public void onCancel() {
                // App code
                Log.e("Facebook_Cancel", "onCancel");
            }

            @Override
            public void onError(FacebookException exception) {
                // App code
                Log.e("Facebook_Exception", exception.getMessage());
            }
        });


@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        callbackManager.onActivityResult(requestCode, resultCode, data);
        super.onActivityResult(requestCode, resultCode, data);
    }


private void handleFacebookAccessToken(AccessToken token) {
        Log.e(TAG, "handleFacebookAccessToken:" + token);

        AuthCredential credential = FacebookAuthProvider.getCredential(token.getToken());
        mAuth.signInWithCredential(credential)
                .addOnCompleteListener(this, new OnCompleteListener<AuthResult>() {
                    @Override
                    public void onComplete(@NonNull Task<AuthResult> task) {
                        if (task.isSuccessful()) {
                            // Sign in success, update UI with the signed-in user's information
                            Log.e(TAG, "signInWithCredential:success");
                            FirebaseUser user = mAuth.getCurrentUser();
                            Log.e("Facebook_FirebaseUser", user.getEmail());
                            //updateUI(user);
                        } else {
                            // If sign in fails, display a message to the user.
                            Log.e(TAG, "signInWithCredential:failure", task.getException());
                            Toast.makeText(MainActivity.this, "Authentication failed.",
                                    Toast.LENGTH_SHORT).show();
                            //updateUI(null);
                        }

                        // ...
                    }
                });
    }
```
```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.ahsan.androidbasicswork, PID: 6333
                                                                           java.lang.NullPointerException: println needs a message
                                                                               at android.util.Log.println_native_inner(Native Method)
                                                                               at android.util.Log.println_native(Log.java:294)
                                                                               at android.util.Log.e(Log.java:420)
                                                                               at com.ahsan.androidbasicswork.MainActivity$3.onComplete(MainActivity.java:170)
                                                                               at com.google.android.gms.tasks.zzf.run(Unknown Source)
                                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6165)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

**Comment by samtstern** [comment]
@yokei15 it doesn't look like you're using FirebaseUI here, I see direct calls to `signInWithCredential` and other things.

If you're just using Firebase Auth and having trouble, try the `firebase/quickstart-android` repo or StackOverflow.
