### ISSUE TITLE
phone auth only crashes the app when canceled 

### ISSUE THREAD

**Issue by kareemElsayedDEV** [firebase/FirebaseUI-Android#1195]
when adding phone authentication to the app **only** it crashes when the user cancel the login operation producing:
```
Fatal Exception: java.lang.RuntimeException
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
                                                                                             at onActivityResult(SplashScreen.kt:0)
                                                                                             at android.app.Activity.dispatchActivityResult(Activity.java:6543)
                                                                                             at android.app.ActivityThread.deliverResults(ActivityThread.java:4054)
                                                                                             at android.app.ActivityThread.handleSendResult(ActivityThread.java:4101) 
                                                                                             at android.app.ActivityThread.access$1400(ActivityThread.java:177) 
                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1497) 
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                             at android.os.Looper.loop(Looper.java:145) 
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:5942) 
                                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) 
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195) 
```

so to generate this issue use the following code
`startActivityForResult(AuthUI.getInstance().createSignInIntentBuilder().setLogo(R.mipmap.logo).setAvailableProviders(Arrays.asList(AuthUI.IdpConfig.PhoneBuilder().build())).build(), REQUEST_SIGN_IN)`
then press back until the login cancels

**Comment by samtstern** [comment]
@kareemElsayedDEV I can't reproduce this on the demo app in this repository, so I think it's something specific to your app.

I see that you're using Kotlin and the crash is coming from `kotlin.jvm.internal`.  Can you show me the `onActivityResult` method of `SplashScreen.kt`?

**Comment by kareemElsayedDEV** [comment]
@samtstern i did debug this issue and it never reaches onActivityResult
any ways here is my code 
```
super.onActivityResult(requestCode, resultCode, data)
        if (requestCode == REQUEST_SIGN_IN) {
            val response: IdpResponse? = IdpResponse.fromResultIntent(data)
            if (resultCode == RESULT_OK) {
                return
            } else {
                if (response == null) {
                    TastyToast.makeText(this, resources.getString(R.string.error_cancelled_signIn), TastyToast.LENGTH_LONG, TastyToast.ERROR)
                    return
                }

                if (response.error?.errorCode== ErrorCodes.NO_NETWORK) {
                    TastyToast.makeText(this, resources.getString(R.string.error_no_internet_connection), TastyToast.LENGTH_LONG, TastyToast.ERROR)
                    return
                }

                if (response.error?.errorCode == ErrorCodes.UNKNOWN_ERROR) {
                    Crashlytics.log("${response.errorCode} is the error code for the signIn operation")
                    TastyToast.makeText(this, resources.getString(R.string.unknown_error), TastyToast.LENGTH_LONG, TastyToast.ERROR)
                    return
                }
            }
            Crashlytics.log("${response.errorCode} is the error code for the signIn operation")
            TastyToast.makeText(this, resources.getString(R.string.unknown_error), TastyToast.LENGTH_LONG, TastyToast.ERROR)
        }
```

**Comment by samtstern** [comment]
@kareemElsayedDEV try changing the signature of `onActivityResult` to accept a `null` Intent data:

something like:

```kotlin
(requestCode: int, resultCode: int, data: Intent?)
```

**Comment by kareemElsayedDEV** [comment]
actually yes that solved it!!
i really feel stupid
