### ISSUE TITLE
3.3.0 NullPointerException

### ISSUE THREAD

**Issue by xuaninbox** [firebase/FirebaseUI-Android#1239]
* Android device: Samsung
  * Android OS version: 8.0
  * Google Play Services version: 12.0.1
  * Firebase/Play Services SDK version: 12.0.1
  * FirebaseUI version: 3.3.0

#### Steps to reproduce:

reported by Crashlytics on 11 devices
  
#### Observed Results:

  crash with NullPointerException
  
#### Expected Results:

  not crash
  
#### Relevant Code:

  ```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.auth.FirebaseUser.getDisplayName()' on a null object reference
       at com.firebase.ui.auth.util.CredentialsUtil.buildCredential(CredentialsUtil.java:28)
       at com.firebase.ui.auth.ui.HelperActivityBase.startSaveCredentials(HelperActivityBase.java:107)
       at com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity$1.onSuccess(AuthMethodPickerActivity.java:97)
       at com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity$1.onSuccess(AuthMethodPickerActivity.java:94)
       at com.firebase.ui.auth.viewmodel.ResourceObserver.onChanged(ResourceObserver.java:34)
       at com.firebase.ui.auth.viewmodel.ResourceObserver.onChanged(ResourceObserver.java:13)
       at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
       at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:121)
       at android.arch.lifecycle.LiveData.access$400(LiveData.java:59)
       at android.arch.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:416)
       at android.arch.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:368)
       at android.arch.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
       at android.arch.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:292)
       at android.arch.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:332)
       at android.arch.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:137)
       at android.arch.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:123)
       at android.arch.lifecycle.ReportFragment.dispatch(ReportFragment.java:121)
       at android.arch.lifecycle.ReportFragment.onStart(ReportFragment.java:81)
       at android.app.Fragment.performStart(Fragment.java:2378)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1027)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
       at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2048)
       at android.app.FragmentController.dispatchStart(FragmentController.java:188)
       at android.app.Activity.performStart(Activity.java:6965)
       at android.app.Activity.performRestart(Activity.java:7075)
       at android.app.Activity.performResume(Activity.java:7080)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3768)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3832)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1534)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1424)
  ```

**Comment by xuaninbox** [comment]
Sry I wasn’t able to find the logs form Firebase analytics, I do have the fabric log of the crash, is that ok?

**Comment by xuaninbox** [comment]
```
startActivityForResult(
                        AuthUI.getInstance().createSignInIntentBuilder()
                                .setIsSmartLockEnabled(false)
                                .setLogo(R.drawable.ic_common_app_icon_text)
                                .setTheme(R.style.AppTheme)
                                .setAvailableProviders(
                                        arrayListOf(
                                                AuthUI.IdpConfig.EmailBuilder().build(),
                                                AuthUI.IdpConfig.GoogleBuilder().build(),
                                                AuthUI.IdpConfig.FacebookBuilder().build()
                                        )
                                )
                                .build(),
                        0
                )
  ```

I'll enable SmartLock again and see if we have the same issue

**Comment by samtstern** [comment]
Just doing some investigating, the `buildCredential` method is being called from two places:

  * `HelperActivityBase#startSaveCredentials`
    * Used in `FragmentBase`, `WelcomeBackPasswordPrompt`, `AuthMethodPickerActivity`, and `SingleSignInActivity`
  * `SmartLockHandler#saveCredentials`
    * Interestingly this method seems only to be used in tests?

If I had to guess (and I do) I'm gonna look deeper into `SingleSignInActivity` and `FragmentBase` since we messed with those classes in the latest release.

**Comment by samtstern** [comment]
Ok so here's what happens.  In `SocialProviderResponseHandler` we have this block:

```java
getAuth().signInWithCredential(ProviderUtils.getAuthCredential(response))
                .continueWithTask(new ProfileMerger(response))
                .addOnSuccessListener(new OnSuccessListener<AuthResult>() {
                    @Override
                    public void onSuccess(AuthResult result) {
                        setResult(Resource.forSuccess(response));
                    }
                })
```

In `AuthMethodPickerActivity` that causes this to happen:

```java
        mHandler.getOperation().observe(this, new ResourceObserver<IdpResponse>(
                this, R.string.fui_progress_dialog_signing_in) {
            @Override
            protected void onSuccess(@NonNull IdpResponse response) {
                startSaveCredentials(mHandler.getCurrentUser(), response, null);
            }
```

The call to `mHandler.getCurrentUser()` comes from `AuthViewModelBase`:

```java
    @Nullable
    public FirebaseUser getCurrentUser() {
        return mAuth.getCurrentUser();
    }
```

So I guess that maybe `getCurrentUser()` is not guaranteed to be set inside of the `Task` callback and we instead need to use the `FirebaseUser` from the `AuthResult`?

**Comment by SUPERCILEX** [comment]
@samtstern Yeah, that was my thought too but it's not coming from there. I really should have shared my thoughts earlier, but here's what I understand so far:
1. This result is _NOT_ coming from an IDP because it's launched after an Activity callback instead of including the `OperatableViewModel` in the stack trace.
1. That implies the result is coming from either the email or phone activity.
1. _That_ implies we're returning a `RESULT_OK` without actually having a successful sign-in.

That's what I've got so far...

**Comment by xuaninbox** [comment]
@SUPERCILEX @samtstern Thanks guys I believe i know whats going on

  ```
FirebaseAuth.getInstance().addAuthStateListener {
    it.currentUser?.let {
        if (it.providerData.count() == 1 && it.providerId == "password" && !it.isEmailVerified) {
            it.sendEmailVerification()
            showErrorAlertDialog("Verification email has been sent to ${it.email}. Please verify and sign in again.")
            FirebaseAuth.getInstance().signOut()
        } else {
            // do staff
        }
    } ?: run {
        // do staff
    }
}
  ```
We have some code that will check if email is verified after login success, if not we'll send the verification email and logout the user. I think AuthStateListener may sometimes happen before the startSaveCredentials thus causing the null pointer.

any suggestions in how to handle this use case without running into this issue?

**Comment by samtstern** [comment]
@xuaninbox in general you don't want to have active auth state listeners while you're in the FirebaseUI flow because we're doing all kinds of auth actions behind the scenes.  Would it work if you unregistered the listener before starting FirebaseUI and then registered it again when FirebaseUI comes back?

**Comment by SUPERCILEX** [comment]
@xuaninbox Well lol, yeah, that'll do it. You'll have to move that to `onActivityResult` since FUI expects to have full control of sign-in/out for the duration of the flow. @samtstern Do you think we should change our assumptions? This seems like a really extreme edge case to me...

**Comment by xuaninbox** [comment]
Thanks guys! I'll move the sign out to onActivityResult, maybe adding a note here may help someone in the future~ https://github.com/firebase/FirebaseUI-Android/blame/master/auth/README.md#L366
