### ISSUE TITLE
SocialProviderResponseHandler.startSignIn NPE

### ISSUE THREAD

**Issue by j2emanue** [firebase/FirebaseUI-Android#1306]
hey, you guys have any idea why crashlytics is reporting this error?  i have the latest.

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=110, result=-1, data=Intent {  launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 }(has extras) }} to activity {com.mobile.pomelo/com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.android.gms.common.api.GoogleApi.zzb(com.google.android.gms.common.api.internal.zzde)' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4556)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4599)
       at android.app.ActivityThread.-wrap22(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1715)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6823)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
```

more details:
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.android.gms.common.api.GoogleApi.zzb(com.google.android.gms.common.api.internal.zzde)' on a null object reference
       at com.google.android.gms.internal.zzdza.zzb(Unknown Source)
       at com.google.android.gms.internal.zzdzh.zza(Unknown Source)
       at com.google.firebase.auth.FirebaseAuth.signInWithCredential(Unknown Source)
       at com.firebase.ui.auth.viewmodel.idp.SocialProviderResponseHandler.startSignIn(SourceFile:59)
       at com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity$2.handleResponse(SourceFile:186)
       at com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity$2.onSuccess(SourceFile:167)
       at com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity$2.onSuccess(SourceFile:164)
       at com.firebase.ui.auth.viewmodel.ResourceObserver.onChanged(SourceFile:47)
       at com.firebase.ui.auth.viewmodel.ResourceObserver.onChanged(SourceFile:16)
       at android.arch.lifecycle.LiveData.considerNotify(SourceFile:109)
       at android.arch.lifecycle.LiveData.dispatchingValue(SourceFile:126)
       at android.arch.lifecycle.LiveData.setValue(SourceFile:282)
       at android.arch.lifecycle.MutableLiveData.setValue(SourceFile:33)
       at com.firebase.ui.auth.viewmodel.OperableViewModel.setResult(SourceFile:24)
       at com.firebase.ui.auth.data.remote.GoogleSignInHandler.onActivityResult(SourceFile:88)
       at com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity.onActivityResult(SourceFile:212)
       at android.app.Activity.dispatchActivityResult(Activity.java:7329)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4552)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4599)
       at android.app.ActivityThread.-wrap22(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1715)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6823)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
```

seen on:  device: SM-C710F
android: 7.1.1
portrait mode
not rooted.

firebase version i need to force to 12.0.1

here is how i call the library:

 override fun loadFireBaseUi() {

        var startFireBaseUi: () -> Unit = {
            val providers = Arrays.asList(
                    AuthUI.IdpConfig.GoogleBuilder().build(),
                    AuthUI.IdpConfig.FacebookBuilder().build(),
                    AuthUI.IdpConfig.EmailBuilder().build()
            )

            // Create and launch sign-in intent
            startActivityForResult(
                    AuthUI.getInstance()
                            .createSignInIntentBuilder()
                            .setAvailableProviders(providers)
                            .setIsSmartLockEnabled(false)
                            .setIsAccountLinkingEnabled(true, null)              
                            .setTheme(R.style.FireBaseUIPomeloAppTheme)
                            .setLogo(R.drawable.pomelo_logo_white)
                            .build(),
                    RC_SIGN_IN)
        }

        startFireBaseUi()
    }

**Comment by j2emanue** [comment]
i suspected it was  a firebase sdk issue, thanks

**Comment by j2emanue** [comment]
just some other software im wroking with, nothing to do with you guys.
oneSignal forcing me to use that version because they wont use firebase
versioning.
