### ISSUE TITLE
PrebuiltUI 'Sign in with email' causing fatal exception

### ISSUE THREAD

**Issue by scottstainton** [firebase/FirebaseUI-Android#1377]
Android Device: Samsung J5
Android OS version: 6.0.1 API 23
FirebaseUI version: 4.0.1
  
Describe the problem:

Clicking the 'Sign in with email' button on the Prebuilt-UI causes fatal exception. 
A similar issue was reported in  [issue 196](https://github.com/firebase/FirebaseUI-Android/issues/196) but was fixed in 0.4.4.

Steps to reproduce:

  1. Click the 'sign in with email' button 
  
Observed Results:
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.neuratechnologies.faceageapp, PID: 28626
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.scottstainton.myapp/com.firebase.ui.auth.ui.email.EmailActivity}: android.view.InflateException: Binary XML file line #25: Binary XML file line #25: Error inflating class android.support.design.widget.TextInputLayout
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3319)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
                      at android.app.ActivityThread.access$1100(ActivityThread.java:229)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:7325)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                   Caused by: android.view.InflateException: Binary XML file line #25: Binary XML file line #25: Error inflating class android.support.design.widget.TextInputLayout
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                      at com.firebase.ui.auth.ui.email.CheckEmailFragment.onCreateView(CheckEmailFragment.java:88)
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2425)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2623)
                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2410)
                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2365)
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2272)
                      at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3271)
                      at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3227)
                      at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
                      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:610)
                      at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1266)
                      at android.app.Activity.performStart(Activity.java:6943)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3276)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
                      at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:7325) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                   Caused by: android.view.InflateException: Binary XML file line #25: Error inflating class android.support.design.widget.TextInputLayout
                      at android.view.LayoutInflater.createView(LayoutInflater.java:657)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                      at com.firebase.ui.auth.ui.email.CheckEmailFragment.onCreateView(CheckEmailFragment.java:88) 
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2425) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460) 
                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852) 
                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802) 
                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2623) 
                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2410) 
                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2365) 
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2272) 
                      at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3271) 
                      at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3227) 
                      at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201) 
                      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:610) 
                      at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178) 
                      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1266) 
                      at android.app.Activity.performStart(Activity.java:6943) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3276) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
                      at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:7325) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Constructor.newInstance(Native Method)
                      at android.view.LayoutInflater.createView(LayoutInflater.java:631)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                      at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                      at com.firebase.ui.auth.ui.email.CheckEmailFragment.onCreateView(CheckEmailFragment.java:88) 
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2425) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460) 
                      at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852) 
                      at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802) 
                      at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2623) 
                      at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2410) 
                      at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2365) 
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2272) 
                      at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3271) 
                      at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3227) 
                      at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201) 
                      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:610) 
                      at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178) 
                      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1266) 
                      at android.app.Activity.performStart(Activity.java:6943) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3276) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415) 
                      at android.app.ActivityThread.access$1100(ActivityThread.java:229) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:148) 
                      at android.app.ActivityThread.main(ActivityThread.java:7325) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                   Caused by: java.lang.NoSuchFieldError: No static field error_color_material of type I in class Landr
I/Process: Sending signal. PID: 28626 SIG: 9
Application terminated.
```
  
Expected Results:

To be presented with login screen
  
Relevant Code:

Start the login activity via:

```java
startActivityForResult(
                            AuthUI.getInstance()
                                    .createSignInIntentBuilder()
                                    .setIsSmartLockEnabled(!BuildConfig.DEBUG /* credentials */, true /* hints */)
                                    .setAvailableProviders(Arrays.asList(
                                            new AuthUI.IdpConfig.EmailBuilder().build(),
                                            new AuthUI.IdpConfig.GoogleBuilder().build(),
                                            new AuthUI.IdpConfig.FacebookBuilder().build()))
                                    .setLogo(R.drawable.silver_on_black_splash)
                                    .build(),
                            RC_SIGN_IN);
```

**Comment by scottstainton** [comment]
I was using 'com.android.support:appcompat-v7:28.0.0-alpha3', downgraded to 'com.android.support:appcompat-v7:27.1.1' and it fixed. Don't think it was a firebase issue.

**Comment by mmoreno1992** [comment]
Confirm @scottstainton solution, it worked for me too
