### ISSUE TITLE
No virtual method requireContext()Landroid/content/Context; in class Lcom/firebase/ui/auth/ui/email/CheckEmailFragment

### ISSUE THREAD

**Issue by Hishmad** [firebase/FirebaseUI-Android#1398]
Hello again

When user sign in with email the app crash...

### Step 1: Are you in the right place?

YES

### Step 2: Describe your environment

  * Android device:  Samsung S7
  * Android OS version:  8.0.0
  * Google Play Services version:  4.0.1
  * Firebase/Play Services SDK version: 16.0.1
  * FirebaseUI version: 4.1.0
  
### Step 3: Describe the problem:

```
java.lang.NoSuchMethodError: No virtual method requireContext()Landroid/content/Context; in class Lcom/firebase/ui/auth/ui/email/CheckEmailFragment; or its super classes (declaration of 'com.firebase.ui.auth.ui.email.CheckEmailFragment' appears in /data/app/id.iternak.iternakdetail-52Tp4xJCvIDrJkYY8Ebldg==/split_lib_dependencies_apk.apk)
        at com.firebase.ui.auth.ui.email.CheckEmailFragment.onViewCreated(CheckEmailFragment.java:122)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1430)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3231)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:572)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1340)
        at android.app.Activity.performStart(Activity.java:7191)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2920)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

app/build.gradle
```
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

android {
    compileSdkVersion 27
    buildToolsVersion '27.0.3'
    defaultConfig {
        applicationId "id.iternak.iternakdetail"
        minSdkVersion 21
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            def requested = details.requested
            if (requested.group == 'com.android.support') {
                if (!requested.name.startsWith("multidex")) {
                    details.useVersion '27.0.1'
                }
            }
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:27.1.1'
    testImplementation 'junit:junit:4.12'
    implementation "android.arch.lifecycle:extensions:$lifecycle_version"
    implementation 'com.android.support:support-v4:27.1.1'
    implementation 'com.android.support:support-v13:27.1.1'
    implementation 'com.android.support:design:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'android.arch.lifecycle:runtime:1.1.1'
    implementation 'com.google.firebase:firebase-core:16.0.1'
    implementation 'com.google.firebase:firebase-database:16.0.1'
    implementation 'com.google.firebase:firebase-storage:16.0.1'
    implementation 'com.google.android.gms:play-services-auth:15.0.1'
    implementation 'com.google.firebase:firebase-auth:16.0.1'
    implementation 'com.firebaseui:firebase-ui-auth:4.1.0'
    implementation "org.jetbrains.anko:anko-common:$anko_version"
    implementation 'com.github.bumptech.glide:glide:4.1.1'
    implementation 'android.arch.lifecycle:extensions:1.1.1'
    implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'
    implementation 'io.reactivex.rxjava2:rxkotlin:2.2.0'

    annotationProcessor 'com.github.bumptech.glide:compiler:4.1.1'


}

// Add to the bottom of the file
apply plugin: 'com.google.gms.google-services'

```

Project build.gradle
```
buildscript {
    ext.kotlin_version = '1.2.51'
    ext.anko_version = '0.10.1'
    ext.lifecycle_version = '1.1.1'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.0.1'


        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by samtstern** [comment]
@Hishmad the methods you're missing were added in version `27.1.0` of the support library:
https://developer.android.com/topic/libraries/support-library/revisions#new-apis_2

This part of your script is making sure you're stuck on `27.0.1`:

```
configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            def requested = details.requested
            if (requested.group == 'com.android.support') {
                if (!requested.name.startsWith("multidex")) {
                    details.useVersion '27.0.1'
                }
            }
        }
    }
```

I'd change that version, if you can.

**Comment by Hishmad** [comment]
Noted with many thanks

**Comment by ainhtoopaing-source** [comment]
java.lang.NoSuchMethodError: No virtual method requireContext()Landroid/content/Context; in class Landroid/content/ContentProvider; or its super classes (declaration of 'android.content.ContentProvider' appears in /system/framework/framework.jar)
	at com.android.camera.external.mivi.MiviInfoContentProvider.onCreate(Unknown Source:2)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2127)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2096)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7216)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6699)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6594)
	at android.app.ActivityThread.access$1400(ActivityThread.java:229)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1901)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:226)
	at android.app.ActivityThread.main(ActivityThread.java:7592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
