### ISSUE TITLE
ClassNotFoundException always on first run

### ISSUE THREAD

**Issue by SimonMarquis** [firebase/FirebaseUI-Android#1407]
When running my app after a clean install, I get the following crash (only trigger on the 1st run):

```
2018-08-11 11:23:13.429 11839-11882/? E/AndroidRuntime: FATAL EXCEPTION: TokenRefresher
    Process: my.package.name, PID: 11839
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/auth/internal/zzae;
        at com.google.firebase.auth.FirebaseAuth.a(Unknown Source:58)
        at com.google.firebase.auth.FirebaseAuth.a(Unknown Source:2)
        at com.google.firebase.auth.internal.v.run(Unknown Source:38)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.auth.internal.zzae" on path: DexPathList[[zip file "/data/app/my.package.name-6cbahSbL8hf2Akie_ZnPAw==/base.apk"],nativeLibraryDirectories=[/data/app/my.package.name-6cbahSbL8hf2Akie_ZnPAw==/lib/arm64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.firebase.auth.FirebaseAuth.a(Unknown Source:58) 
        at com.google.firebase.auth.FirebaseAuth.a(Unknown Source:2) 
        at com.google.firebase.auth.internal.v.run(Unknown Source:38) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

It seems that the class `com.google.firebase.auth.internal.zzae` is being removed from the apk by proguard (listed in proguard's usage.txt file).
Adding the proguard rule `-keep class com.google.firebase.auth.internal.zzae { *; }` seems to prevent the crash.
Also, disabling R8 with `android.enableR8=false` without the proguard rule prevent the crash.

---

Device:
- Pixel 2 XL
- Android P
- Google Play Services 13.2.72

Configuration:
- targetSdkVersion 28
- release build
- minifyEnabled true
- android.enableJetifier=true
- android.useAndroidX=true

Dependencies:
- com.firebaseui:firebase-ui-auth:4.1.0
- com.firebaseui:firebase-ui-database:4.1.0
- com.firebaseui:firebase-ui-storage:4.1.0
- com.google.firebase:firebase-core:16.0.1
- com.google.firebase:firebase-auth:16.0.2
- com.google.firebase:firebase-database:16.0.1
- com.google.firebase:firebase-storage:16.0.1
- com.google.firebase:firebase-messaging:17.1.0

**Comment by SUPERCILEX** [comment]
As you noticed, this isn't an FUI crash. You're running AGP 3.3.x I assume? If so, please star my issue since I got the same crash: https://issuetracker.google.com/issues/112232549

**Comment by SimonMarquis** [comment]
Yes, AGP 3.3.0-alpha05.
I knnow it's not a FUI crash but there was no firebase root github project to report this issue and I thought reporting on this project might be enough.
Also, I've also created a ticket on the R8 project: https://issuetracker.google.com/issues/112452064

I don't think this is exactly the same issue though (mine is about a class provided by the Firebase library, and yours seems to be a custom user class)

**Comment by SUPERCILEX** [comment]
Hmmm, interesting. Either way, since disabling R8 fixed the issue, it's not something that can be fixed on Firebase's end.

**Comment by SUPERCILEX** [comment]
FYI, to report bugs in the non-open-source libraries, it's here if you scroll down: https://firebase.google.com/support/

**Comment by SimonMarquis** [comment]
I see, then I'll update this issue when I'll get more details from the R8 team.
Someone already answered in the R8 issuetracker:
> It's going to be an easy fix

**Comment by SUPERCILEX** [comment]
Cool beans!
