### ISSUE TITLE
AuthUI KickoffActivity throwing RuntimeException: Cannot create an instance of class com.firebase.ui.auth.a.b.f

### ISSUE THREAD

**Issue by SimonMarquis** [firebase/FirebaseUI-Android#1429]
Following #1407 (seems to be fixed by AGP 3.3.0-alpha08), now when starting the AuthUI signIn Intent, the KickoffActivity tries to create an instance of `com.firebase.ui.auth.a.b.f` and fails.

**Start signIn intent:**
```
val intent = AuthUI.getInstance(Firebase.app)
                    .createSignInIntentBuilder()
                    .setTheme(R.style.MyTheme)
                    .setAvailableProviders(AUTH_PROVIDERS)
                    .setIsSmartLockEnabled(true)
                    .build()
startActivityForResult(intent, REQUEST_CODE)
```

**Crash stacktrace:**
```
2018-08-30 19:37:06.582 29849-29849/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: my.package.name, PID: 29849
    java.lang.RuntimeException: Unable to start activity ComponentInfo{my.package.name/com.firebase.ui.auth.KickoffActivity}: java.lang.RuntimeException: Cannot create an instance of class com.firebase.ui.auth.a.b.f
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: Cannot create an instance of class com.firebase.ui.auth.a.b.f
        at androidx.lifecycle.A$a.a(:202)
        at androidx.lifecycle.A.a(:135)
        at androidx.lifecycle.A.a(:103)
        at com.firebase.ui.auth.KickoffActivity.onCreate(:33)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.NoSuchMethodException: <init> [class android.app.Application]
        at java.lang.Class.getConstructor0(Class.java:2327)
        at java.lang.Class.getConstructor(Class.java:1725)
        at androidx.lifecycle.A$a.a(:200)
        at androidx.lifecycle.A.a(:135) 
        at androidx.lifecycle.A.a(:103) 
        at com.firebase.ui.auth.KickoffActivity.onCreate(:33) 
        at android.app.Activity.performCreate(Activity.java:7136) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

---

Disabling R8 with `android.enableR8=false` **doesn't fix the issue.**  
Adding the proguard rule `-keep class com.firebase.ui.auth.** { * ; }` **fixes the issue.**

---

Device:
- Pixel 2 XL
- Android P
- Google Play Services 13.2.78

Configuration:
- targetSdkVersion 28
- release build
- minifyEnabled true
- android.enableJetifier=true
- android.useAndroidX=true

Buildscript classpath:
- com.android.tools.build:gradle:3.3.0-alpha08
- org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.61
- com.google.gms:google-services:4.0.2

Dependencies:
- com.firebaseui:firebase-ui-auth:4.1.0
- com.firebaseui:firebase-ui-database:4.1.0
- com.firebaseui:firebase-ui-storage:4.1.0
- com.google.firebase:firebase-core:16.0.3
- com.google.firebase:firebase-auth:16.0.3
- com.google.firebase:firebase-database:16.0.1
- com.google.firebase:firebase-storage:16.0.1
- com.google.firebase:firebase-messaging:17.3.0

**Comment by SUPERCILEX** [comment]
Yeah, that's expected until RC 2 comes out: https://issuetracker.google.com/issues/112230489

**Comment by SimonMarquis** [comment]
👍 I wasn't aware of the `androidx.lifecycle:lifecycle-viewmodel:2.0.0-rc01` transitive dependency (since most of the other androidx dependencies were already -rc02).

**Comment by SUPERCILEX** [comment]
Yeah, I didn't notice that either and accidentally filed a bug with R8. 😳 Now, I guess it's just a matter of complaining until they ship it. 😉

**Comment by samtstern** [comment]
Thanks both!  Closing as this is a bug in R8
