### ISSUE TITLE
Crostini + Android Studio + FirebaseUI = FirebaseUiException: Code: 16, message: 16: 

### ISSUE THREAD

**Issue by kermitdefroghere** [firebase/FirebaseUI-Android#1442]
Hi,
I got Linux going in Beta on my Pixelbook recently but am experiencing FirebaseUiException errors when attempting to login with FirebaseUI using Google Provider.
(I have no problems running from Android Studio on Windows 10 machine)

I should also mention that Android Studio on Chrome OS only supports ADB over wifi (not USB).
I have a sneaky suspicion that may be a factor.

Laptop: Pixelbook, Chrome OS 69 (Beta channel)
Android Device: Pixel, Android 9
  * Google Play Services version: _13.2.80____
  * Firebase/Play Services SDK version: ___firebase-core:16.0.1__
  * FirebaseUI version: _4.1.0___
  
Describe the problem:
Attempting to login with Google provider causes firebaseui exception.

#### Steps to reproduce:

  1. __Login with Google Account___
  2. _____
  3. _____
  
#### Observed Results:

E/AuthUI: A sign-in error occurred.
          com.firebase.ui.auth.FirebaseUiException: Code: 16, message: 16: 
              at com.firebase.ui.auth.data.remote.GoogleSignInHandler.onActivityResult(GoogleSignInHandler.java:106)
              at com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity.onActivityResult(AuthMethodPickerActivity.java:242)
              at android.app.Activity.dispatchActivityResult(Activity.java:7454)
              at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)
              at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
              at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
              at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
              at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
              at android.os.Handler.dispatchMessage(Handler.java:106)
              at android.os.Looper.loop(Looper.java:193)
              at android.app.ActivityThread.main(ActivityThread.java:6669)
              at java.lang.reflect.Method.invoke(Native Method)
              at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AuthUI: A sign-in error occurred.
          com.firebase.ui.auth.FirebaseUiException: Code: 16, message: 16: 
              at com.firebase.ui.auth.data.remote.GoogleSignInHandler.onActivityResult(GoogleSignInHandler.java:106)
              at com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity.onActivityResult(AuthMethodPickerActivity.java:242)
              at android.app.Activity.dispatchActivityResult(Activity.java:7454)
              at android.app.ActivityThread.deliverResults(ActivityThread.java:4353)
              at android.app.ActivityThread.handleSendResult(ActivityThread.java:4402)
              at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
              at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
              at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
              at android.os.Handler.dispatchMessage(Handler.java:106)
              at android.os.Looper.loop(Looper.java:193)
              at android.app.ActivityThread.main(ActivityThread.java:6669)
              at java.lang.reflect.Method.invoke(Native Method)
              at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
  
#### Expected Results:

ActivityResult to be received.
  
#### Relevant Code:
            startActivityForResult(
                    AuthUI.getInstance()
                            .createSignInIntentBuilder()
                            .setTheme(R.style.AppTheme)
                            .setAvailableProviders(Arrays.asList(
                                    new AuthUI.IdpConfig.EmailBuilder().build(),
                                    new AuthUI.IdpConfig.GoogleBuilder().build()))
                            .setTosAndPrivacyPolicyUrls("http://www.1010physiotherapy.com/terms-of-service",
                                    "http://www.1010physiotherapy.com/privacy")
                            .setLogo(R.drawable.login_image)
                            .build(),
                    RC_SIGN_IN);

  ```

**Comment by samtstern** [comment]
Have you added the SHA1 of the development certificate of your Pixel book
to the Firebase console?

**Comment by kermitdefroghere** [comment]
Yes and I just double checked it.
The SHA1 from the signingReport from Android Studio on the Pixelbook is registered within the Firebase project settings.
Is there anything else I need to do? Do I need to do anything with the google-services.json by chance?

**Comment by samtstern** [comment]
@kermitdefroghere huh that's interesting, thanks for sharing the solution!

**Comment by Vkadel** [comment]
I encountered this problem after the latest update. I had to rest my my keys in the console and re download my json file as well.

**Comment by samtstern** [comment]
@Vkadel your SHA1 in production can never change, so this is not possible in production.  However your debug key can sometimes change, causing this issue.
