### ISSUE TITLE
project import error

### ISSUE THREAD

**Issue by ZohaibGhafoor** [firebase/FirebaseUI-Android#1480]
can not import project did all clean rebuild clean cahche but nothing works. and give me this error

```
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':app'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:79)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:73)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$400(LifecycleProjectEvaluator.java:54)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.run(LifecycleProjectEvaluator.java:107)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:68)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:687)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:140)
	at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:41)
	at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuild.run(DefaultGradleLauncher.java:274)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.initialization.DefaultGradleLauncher.configureBuild(DefaultGradleLauncher.java:182)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:141)
	at org.gradle.initialization.DefaultGradleLauncher.getConfiguredBuild(DefaultGradleLauncher.java:119)
	at org.gradle.internal.invocation.GradleBuildController$2.call(GradleBuildController.java:86)
	at org.gradle.internal.invocation.GradleBuildController$2.call(GradleBuildController.java:83)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:154)
	at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:38)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:96)
	at org.gradle.internal.invocation.GradleBuildController.configure(GradleBuildController.java:83)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedBuildActionRunner.run(ClientProvidedBuildActionRunner.java:70)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.run(RunAsBuildOperationBuildActionRunner.java:50)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:44)
	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:79)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:44)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:62)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:81)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.cache.CacheOpenException: Could not open cache directory ebibtw2zb429oxginmksxegnr (/Users/zohaibahmed/.gradle/caches/4.10/gradle-kotlin-dsl/ebibtw2zb429oxginmksxegnr).
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:80)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:42)
	at org.gradle.cache.internal.DefaultCacheFactory.doOpen(DefaultCacheFactory.java:95)
	at org.gradle.cache.internal.DefaultCacheFactory.open(DefaultCacheFactory.java:69)
	at org.gradle.cache.internal.DefaultCacheRepository$PersistentCacheBuilder.open(DefaultCacheRepository.java:124)
	at org.gradle.kotlin.dsl.cache.ScriptCache.cacheDirFor(ScriptCache.kt:71)
	at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost.cacheDirFor(KotlinScriptEvaluator.kt:245)
	at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost.cachedDirFor(KotlinScriptEvaluator.kt:234)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.compileSecondStageScript(Interpreter.kt:446)
	at Program.loadSecondStageFor(Unknown Source)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.evaluateSecondStageOf(Interpreter.kt:403)
	at Program.execute(Unknown Source)
	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.eval(Interpreter.kt:498)
	at org.gradle.kotlin.dsl.execution.Interpreter.eval(Interpreter.kt:164)
	at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator.evaluate(KotlinScriptEvaluator.kt:112)
	at org.gradle.kotlin.dsl.provider.KotlinScriptPluginFactory$create$1.invoke(KotlinScriptPluginFactory.kt:51)
	at org.gradle.kotlin.dsl.provider.KotlinScriptPluginFactory$create$1.invoke(KotlinScriptPluginFactory.kt:36)
	at org.gradle.kotlin.dsl.provider.KotlinScriptPlugin.apply(KotlinScriptPlugin.kt:34)
	at org.gradle.configuration.BuildOperationScriptPlugin$1$1.run(BuildOperationScriptPlugin.java:69)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.execute(BuildOperationScriptPlugin.java:66)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.execute(BuildOperationScriptPlugin.java:63)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
	at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:63)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:41)
	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.run(LifecycleProjectEvaluator.java:105)
	... 89 more
Caused by: org.gradle.internal.exceptions.LocationAwareException: Build file '/Users/zohaibahmed/Desktop/Sample_Projects/FirebaseUI-Android/app/build.gradle.kts' line: 20
Script compilation errors:
```

**Comment by samtstern** [comment]
I see this error here:
```
Caused by: org.gradle.cache.CacheOpenException: Could not open cache directory ebibtw2zb429oxginmksxegnr (/Users/zohaibahmed/.gradle/caches/4.10/gradle-kotlin-dsl/ebibtw2zb429oxginmksxegnr).
```

Could you try completely deleting the directory `/Users/zohaibahmed/.gradle/caches/4.10`?  It may be corrupted in some way.

**Comment by samtstern** [comment]
@ZohaibGhafoor what version of Android Studio are you using?

Are you able to run this at the command line inside the FirebaseUI android directory:

```
./gradlew clean cleanBuildCache :library:prepareArtifacts
```

**Comment by ZohaibGhafoor** [comment]
@samtstern i'm using most recent latest version 3.2
i did only ./gradlew clean. still same errror
i will try ./gradlew clean cleanBuildCache :library:prepareArtifacts and let you know if still same error.

**Comment by ZohaibGhafoor** [comment]
@samtstern i also try this on my ubuntu linux machine but still got same error.

also did `./gradlew clean cleanBuildCache :library:prepareArtifacts` and again got error.

`FAILURE: Build failed with an exception.

* Where:
Build file '/home/zohaib/Desktop/Sample_Projects/FirebaseUI-Android/app/build.gradle.kts' line: 4

* What went wrong:
Script compilation errors:

  Line 04: android {
           ^ Unresolved reference: android

  Line 05:     defaultConfig {
               ^ Unresolved reference: defaultConfig

  Line 06:         multiDexEnabled = true
                   ^ Unresolved reference: multiDexEnabled

  Line 09:     buildTypes {
               ^ Unresolved reference: buildTypes

  Line 10:         named("release").configure {
                   ^ Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
                       public inline fun <reified T : Any> NamedDomainObjectCollection<out Any>.named(name: String): NamedDomainObjectProvider<TypeVariable(T)> defined in org.gradle.kotlin.dsl
                       public inline fun <reified T : Any> NamedDomainObjectCollection<out Any>.named(name: String, noinline configuration: TypeVariable(T).() -> Unit): NamedDomainObjectProvider<TypeVariable(T)> defined in org.gradle.kotlin.dsl
                       public fun <T : Any> NamedDomainObjectCollection<out Any>.named(name: String, type: KClass<TypeVariable(T)>): NamedDomainObjectProvider<TypeVariable(T)> defined in org.gradle.kotlin.dsl
                       public fun <T : Any> NamedDomainObjectCollection<out Any>.named(name: String, type: KClass<TypeVariable(T)>, configuration: TypeVariable(T).() -> Unit): NamedDomainObjectProvider<TypeVariable(T)> defined in org.gradle.kotlin.dsl
                       public inline fun <reified T : Named> ObjectFactory.named(name: String): TypeVariable(T) defined in org.gradle.kotlin.dsl
                       @Incubating public inline fun <T : Named> ObjectFactory.named(type: KClass<TypeVariable(T)>, name: String): TypeVariable(T) defined in org.gradle.kotlin.dsl
                       public inline fun <reified T : Task> TaskContainer.named(name: String): TaskProvider<TypeVariable(T)> defined in org.gradle.kotlin.dsl
                       public fun <T : Task> TaskContainer.named(name: String, type: KClass<TypeVariable(T)>): TaskProvider<TypeVariable(T)> defined in org.gradle.kotlin.dsl
                       public fun <T : Task> TaskContainer.named(name: String, type: KClass<TypeVariable(T)>, configuration: TypeVariable(T).() -> Unit): TaskProvider<TypeVariable(T)> defined in org.gradle.kotlin.dsl
                       @Incubating public inline fun <T : Any> ModelMap<TypeVariable(T)>.named(name: String, ruleSource: KClass<out RuleSource>): Unit defined in org.gradle.kotlin.dsl

  Line 13:             signingConfig = signingConfigs["debug"]
                       ^ Unresolved reference: signingConfig

  Line 13:             signingConfig = signingConfigs["debug"]
                                       ^ Unresolved reference: signingConfigs

  Line 15:             postprocessing {
                       ^ Unresolved reference: postprocessing

  Line 16:                 isRemoveUnusedCode = true
                           ^ Unresolved reference: isRemoveUnusedCode

  Line 17:                 isRemoveUnusedResources = true
                           ^ Unresolved reference: isRemoveUnusedResources

  Line 18:                 isObfuscate = true
                           ^ Unresolved reference: isObfuscate

  Line 19:                 isOptimizeCode = true
                           ^ Unresolved reference: isOptimizeCode

  Line 24:     lintOptions {
               ^ Unresolved reference: lintOptions

  Line 25:         disable("ResourceName", "MissingTranslation")
                   ^ Unresolved reference: disable

  Line 30:     implementation(Config.Libs.Firebase.core)
               ^ Unresolved reference: implementation

  Line 31:     implementation(Config.Libs.Support.design)
               ^ Unresolved reference: implementation

  Line 32:     implementation(Config.Libs.Support.multidex)
               ^ Unresolved reference: implementation

  Line 34:     implementation(project(":auth"))
               ^ Unresolved reference: implementation

  Line 35:     implementation(project(":auth-github"))
               ^ Unresolved reference: implementation

  Line 36:     implementation(project(":firestore"))
               ^ Unresolved reference: implementation

  Line 37:     implementation(project(":database"))
               ^ Unresolved reference: implementation

  Line 38:     implementation(project(":storage"))
               ^ Unresolved reference: implementation

  Line 40:     implementation(Config.Libs.Provider.facebook)
               ^ Unresolved reference: implementation

  Line 42:     implementation(Config.Libs.Support.cardView)
               ^ Unresolved reference: implementation

  Line 43:     implementation(Config.Libs.Support.customTabs)
               ^ Unresolved reference: implementation

  Line 44:     implementation(Config.Libs.Provider.twitter) { isTransitive = true }
               ^ Unresolved reference: implementation

  Line 44:     implementation(Config.Libs.Provider.twitter) { isTransitive = true }
                                                              ^ Unresolved reference: isTransitive

  Line 46:     implementation(Config.Libs.Misc.glide)
               ^ Unresolved reference: implementation

  Line 47:     annotationProcessor(Config.Libs.Misc.glideCompiler)
               ^ Unresolved reference: annotationProcessor

  Line 50:     implementation(Config.Libs.Arch.paging)
               ^ Unresolved reference: implementation

  Line 55:     implementation(Config.Libs.Misc.permissions)
               ^ Unresolved reference: implementation

  Line 56:     implementation(Config.Libs.Misc.butterKnife)
               ^ Unresolved reference: implementation

  Line 57:     annotationProcessor(Config.Libs.Misc.butterKnifeCompiler)
               ^ Unresolved reference: annotationProcessor

  Line 58:     debugImplementation(Config.Libs.Misc.leakCanary)
               ^ Unresolved reference: debugImplementation

  Line 59:     debugImplementation(Config.Libs.Misc.leakCanaryFragments)
               ^ Unresolved reference: debugImplementation

  Line 60:     releaseImplementation(Config.Libs.Misc.leakCanaryNoop)
               ^ Unresolved reference: releaseImplementation

  Line 61:     testImplementation(Config.Libs.Misc.leakCanaryNoop)
               ^ Unresolved reference: testImplementation

37 errors

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
`

**Comment by AdamSHurwitz** [comment]
I'm seeing the same issue. 

# Implementation

1. `git clone git@github.com:firebase/FirebaseUI-Android.git`
2. Android Studio: _File_ > _New_ > _Import Project_ > _FirebaseUI-Android_ path > _Import project from external model_ > _Gradle_ > _Use local gradle distribution_ > Select _Yes_ to override existing **.Idea** file > Select _Configure_ when _Android framework is detected_ dialog is displayed.
3. Once I received the build error above, I followed your advice and  added the **local.properties** file to the root _FirebaseUI-Android_ directory. I found the Android SDK path in terminal and used the `pwd` command to retrieve the path: `sdk.dir=/Users/adamhurwitz/Library/Android/sdk`
4. I attempted re-importing after adding the _local.properties_ file with the same build error.

# Attempted Solutions
I've also attempted the following variations in the import process:
1. Deleting the _.idea_ file before importing as well as overwriting the file.
2. All of the below variations were tested with both file paths **1)** _File_ > _New_ > _Import Project_ > _FirebaseUI-Android_ path > ... and **2)** _File_ > _New_ > _Import Project_ > _app_ path  > .... 
3. _File_ > _New_ > _Import Project_ > _file_path_ > _Create project from existing sources_ > ...
4. _File_ > _New_ > _Import Project_ > _file_path_ > _Import project from external model_ > _Android Gradle_ > ... ([different build error message](https://docs.google.com/document/d/1LNjOvDJvkubFsXDjnJ6qqAhkSY9teeors4mx8IVIhJo/edit?usp=sharing)).

**Comment by samtstern** [comment]
Woot!
