### ISSUE TITLE
Crash rotating device

### ISSUE THREAD

**Issue by Fax3D** [firebase/FirebaseUI-Android#155]
I got a crash rotating a device while signing in with e-mail&password.
I'm using com.firebaseui:firebase-ui-auth:0.4.0. on a Nexus 5 with Android 6.0.1.

Step to reproduce:
- Launch AuthUI intent to show sign in dialog
- Insert email & password
- When clicking "Next" to start sign in process, during the progress loader try to rotate your device
- Crash!

Hope this additional info could help.

Here the stack trace:
FATAL EXCEPTION: main
                                                                     Process: ***, PID: 6978
                                                                     java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView{1d3e843 V.E...... R......D 0,0-1026,348} not attached to window manager
                                                                         at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:424)
                                                                         at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:350)
                                                                         at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
                                                                         at android.app.Dialog.dismissDialog(Dialog.java:362)
                                                                         at android.app.Dialog.dismiss(Dialog.java:345)
                                                                         at com.firebase.ui.auth.ui.ActivityHelper.dismissDialog(ActivityHelper.java:47)
                                                                         at com.firebase.ui.auth.ui.email.RegisterEmailActivity$2$1.onComplete(RegisterEmailActivity.java:159)
                                                                         at com.google.android.gms.tasks.zzc$1.run(Unknown Source)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by katowulf** [comment]
Add code and version info please. See [creating an mcve](http://stackoverflow.com/help/mcve).

**Comment by Fax3D** [comment]
@katowulf Added some info.

Thanks.

**Comment by samtstern** [comment]
Fixed implemented in #238, will make it into next release.

**Comment by samtstern** [comment]
This fix for this issue is included in version 0.5.0.
