### ISSUE TITLE
KickoffActivity' does not implement interface

### ISSUE THREAD

**Issue by heshesh2010** [firebase/FirebaseUI-Android#1554]
* Android device:  samsung note 5 
  * Android OS version: 7.0
  * Google Play Services version: com.google.gms:google-services:4.2.0
  * Firebase/Play Services SDK version: 16.0.1
  * FirebaseUI version: 4.3
  
I have problem with firebaseUi auth 
```
2018-12-18 00:42:13.336 3713-5178/? E/Parcel: Class not found when unmarshalling: com.firebase.ui.auth.data.model.FlowParameters
    java.lang.ClassNotFoundException: com.firebase.ui.auth.data.model.FlowParameters
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:400)
        at android.os.Parcel.readParcelableCreator(Parcel.java:2517)
        at android.os.Parcel.readParcelable(Parcel.java:2471)
        at android.os.Parcel.readValue(Parcel.java:2374)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2727)
        at android.os.BaseBundle.unparcel(BaseBundle.java:269)
        at android.os.BaseBundle.getString(BaseBundle.java:992)
        at android.content.Intent.getStringExtra(Intent.java:6702)
        at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:336)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1094)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5837)
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5642)
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:176)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3613)
        at android.os.Binder.execTransact(Binder.java:573)
     Caused by: java.lang.ClassNotFoundException: com.firebase.ui.auth.data.model.FlowParameters
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:1346)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:1406)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:400) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:2517) 
        at android.os.Parcel.readParcelable(Parcel.java:2471) 
        at android.os.Parcel.readValue(Parcel.java:2374) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2727) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:269) 
        at android.os.BaseBundle.getString(BaseBundle.java:992) 
        at android.content.Intent.getStringExtra(Intent.java:6702) 
        at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:336) 
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1094) 
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5837) 
        at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5642) 
        at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:176) 
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3613) 
        at android.os.Binder.execTransact(Binder.java:573) 
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
2018-12-18 00:42:13.466 4527-4527/com.heshamapps.heshe.thedentalstore E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.heshamapps.heshe.thedentalstore, PID: 4527
    java.lang.IncompatibleClassChangeError: Class 'com.firebase.ui.auth.KickoffActivity' does not implement interface 'androidx.lifecycle.LifecycleOwner' in call to 'androidx.lifecycle.Lifecycle androidx.lifecycle.LifecycleOwner.getLifecycle()' (declaration of 'androidx.lifecycle.LiveData' appears in /data/app/com.heshamapps.heshe.thedentalstore-2/split_lib_dependencies_apk.apk)
        at androidx.lifecycle.LiveData.observe(LiveData.java:172)
        at com.firebase.ui.auth.KickoffActivity.onCreate(KickoffActivity.java:35)
        at android.app.Activity.performCreate(Activity.java:6942)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2880)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)`
```

gradle file

```groovy
apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.heshamapps.heshe.thedentalstore"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    androidTestImplementation('androidx.test.espresso:espresso-core:3.1.1-alpha01', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-alpha2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1-beta01'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'android.arch.paging:runtime:1.0.1'
    implementation 'androidx.media:media:1.1.0-alpha01'
    implementation 'androidx.vectordrawable:vectordrawable:1.1.0-alpha01'
    implementation 'com.google.android.material:material:1.1.0-alpha01'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.palette:palette:1.0.0'
    implementation 'androidx.browser:browser:1.0.0'


    implementation 'com.mikepenz:materialdrawer:6.1.1'
    implementation 'com.firebaseui:firebase-ui-auth:4.2.1'
    implementation 'com.google.firebase:firebase-auth:16.1.0'
    implementation "com.google.android.gms:play-services-auth:16.0.1"



    implementation 'com.firebaseui:firebase-ui-firestore:4.3.0'

    implementation 'com.jakewharton:butterknife:9.0.0-rc2'
    annotationProcessor 'com.jakewharton:butterknife-compiler:9.0.0-rc2'
    implementation 'com.github.GrenderG:Toasty:1.3.1'
    implementation 'com.squareup.picasso:picasso:2.5.2'

}

apply plugin: 'com.google.gms.google-services'
```

**Comment by samtstern** [comment]
@heshesh2010 can you try using FirebaseUI `4.3.0` which was just released?  It has newer dependencies.

**Comment by heshesh2010** [comment]
I have updated to 4.3.0 but still get same error

**Comment by heshesh2010** [comment]
any update ?

**Comment by samtstern** [comment]
@heshesh2010 sorry about the slow response!  Most of the team was out of the office for Christmas/New Years vacations.

**Comment by samtstern** [comment]
If you look at this issue:
https://github.com/firebase/FirebaseUI-Android/issues/1544

For other users this has come from a dependency issue.  While I am just guessing, I can identify a few sure problems in your dependencies:

You have dependencies on multiple versions of constraint layout:
```
    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-alpha2'
    // ...
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
```

You are mixing versions of FirebaseUI:
```
    implementation 'com.firebaseui:firebase-ui-auth:4.2.1'
    // ...
    implementation 'com.firebaseui:firebase-ui-firestore:4.3.0'
```

I would suggest running `./gradlew :app:androidDependencies` and searching for one of the problematic dependencies mentioned in #1544.

**Comment by heshesh2010** [comment]
i have to use both firestore with firebase auth , so how to use both of them?

**Comment by samtstern** [comment]
@heshesh2010 you can use both but you should do so at the same version.  Either `4.2.1` for both or `4.3.0` for both.  It's not safe to mix versions of FirebaseUI.

**Comment by heshesh2010** [comment]
i have updated my gradle file but still get same error 

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    androidTestImplementation('androidx.test.espresso:espresso-core:3.1.1-alpha01', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    implementation fileTree(include: ['*.jar'], dir: 'libs')
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'android.arch.paging:runtime:1.0.1'
    implementation 'androidx.media:media:1.1.0-alpha01'
    implementation 'androidx.vectordrawable:vectordrawable:1.1.0-alpha01'
    implementation 'com.google.android.material:material:1.1.0-alpha02'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.palette:palette:1.0.0'
    implementation 'androidx.browser:browser:1.0.0'
    implementation 'com.github.bumptech.glide:glide:4.8.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'
    implementation 'com.github.Gavras:MultiLineRadioGroup:v1.0.0.6'
    implementation 'com.rengwuxian.materialedittext:library:2.1.4'
    implementation 'com.geniusforapp.fancydialog:FancyDialog:0.1.4'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'com.mikepenz:materialdrawer:6.1.1'



    implementation 'com.firebaseui:firebase-ui-firestore:4.3.0'
    //Firebase Core Authentication
    implementation 'com.google.firebase:firebase-auth:16.1.0'
    //Firebase Authentication UI
    implementation 'com.firebaseui:firebase-ui-auth:4.3.0'

    implementation 'com.jakewharton:butterknife:9.0.0-rc2'
    annotationProcessor 'com.jakewharton:butterknife-compiler:9.0.0-rc2'
    implementation 'com.github.GrenderG:Toasty:1.3.1'
    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'com.airbnb.android:lottie:2.2.5'

**Comment by samtstern** [comment]
As I mentioned, I suspect that you are somehow getting a transitive dependency on this (or something like it):
```
implementation 'androidx.core:core:1.1.0-alpha02'
```

Please check `./gradlew :app:dependencies` and `./gradlew :app:androidDependencies` for mentions of this.

**Comment by samtstern** [comment]
Ok I tried making a fresh app with your dependencies and the first error I got is:
```
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.1.0-alpha02] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:4:5-10:43 to override.
```

So right away I can tell this is the same root cause as #1544 since there is a mention of `androidx.core:core:1.1.0-alpha02`.  I will find out where it comes from.

**Comment by dnazarov** [comment]
In the newer version you should comment _core-ktx_

`// implementation 'androidx.core:core-ktx:1.1.0-alpha05'`
