### ISSUE TITLE
Recover password :  IllegalArgumentException: Given String is empty or null

### ISSUE THREAD

**Issue by Nebneb** [firebase/FirebaseUI-Android#1582]
### Environment

  * Android device: Any
  * Android OS version: Seen on Android 5-8-9 but does not look relevant
  * Google Play Services version: 16.0.1
  * Firebase/Play Services SDK version: 16.0.1
  * FirebaseUI version: 4.2.1
  
### Encountered problem:

We are getting a crash on recover password when users leave an empty email and validate with the soft keyboard's done button.

#### Steps to reproduce:

  1. Start logging-in with Firebase auth UI
  2. At password step, press "recover password"
  3. Make the email field empty and validate with soft keyboard's done button.
  
#### Observed Results:

The app crashes with the following stacktrace :
```
Fatal Exception: java.lang.IllegalArgumentException: Given String is empty or null
       at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(Unknown Source:5)
       at com.google.firebase.auth.FirebaseAuth.sendPasswordResetEmail(Unknown Source:251)
       at com.firebase.ui.auth.viewmodel.email.RecoverPasswordHandler.startReset(RecoverPasswordHandler.java:20)
       at com.firebase.ui.auth.ui.email.RecoverPasswordActivity.onDonePressed(RecoverPasswordActivity.java:120)
       at com.firebase.ui.auth.util.ui.ImeHelper$1.onEditorAction(ImeHelper.java:31)
       at android.widget.TextView.onEditorAction(TextView.java:5397)
       at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:139)
       at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:304)
       at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6934)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
  ```
#### Expected Results:

  * The behavior should be the same as when we press the UI's done button.

**Comment by samtstern** [comment]
@Nebneb thanks for reporting this!  Seems like a pretty straight-forward bug and I will add it to the next release milestone.

**Comment by samtstern** [comment]
This has been fixed and released in version `4.3.2`

**Comment by Nebneb** [comment]
Thans a lot! 😎

**Comment by Shailevy** [comment]
Happens again (version are pretty much in the call stuck):

Fatal Exception: java.lang.IllegalArgumentException: Given String is empty or null
       at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(com.google.android.gms:play-services-basement@@18.1.0:2)
       at com.google.android.gms.internal.firebase-auth-api.zzvv.<init>(com.google.firebase:firebase-auth@@21.0.5:1)
       at com.google.android.gms.internal.firebase-auth-api.zzvv.$r8$init$synthetic(com.google.firebase:firebase-auth@@21.0.5:3)
       at com.google.android.gms.internal.firebase-auth-api.zzrm.zzO(zzrm.java:4)
       at com.google.android.gms.internal.firebase-auth-api.zzrm.zzc(zzrm.java:8)
       at com.google.android.gms.internal.firebase-auth-api.zzqi.zzb(zzqi.java:7)
       at com.google.android.gms.internal.firebase-auth-api.zzpv.zzb$bridge(com.google.firebase:firebase-auth@@21.0.5:9)
       at com.google.android.gms.internal.firebase-auth-api.zzuq.zza(zzuq.java:24)
       at com.google.android.gms.internal.firebase-auth-api.zztw.zzt(com.google.firebase:firebase-auth@@21.0.5:4)
       at com.google.android.gms.internal.firebase-auth-api.zzrm.zzE(zzrm.java:3)
       at com.google.android.gms.internal.firebase-auth-api.zzti.zzy(com.google.firebase:firebase-auth@@21.0.5:5)
       at com.google.android.gms.internal.firebase-auth-api.zzss.zzc(zzss.java:1)
       at com.google.android.gms.internal.firebase-auth-api.zzrr.zzc$bridge(com.google.firebase:firebase-auth@@21.0.5:59)
       at com.google.android.gms.internal.firebase-auth-api.zzuj.run(com.google.firebase:firebase-auth@@21.0.5:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)
