### ISSUE TITLE
Crash without internet connection

### ISSUE THREAD

**Issue by Fax3D** [firebase/FirebaseUI-Android#164]
If i start ui auth flow intent without an internet connection, i can see the account picker but when i tap on my account i got this crash:

com.google.android.gms.tasks.RuntimeExecutionException: com.google.firebase.FirebaseException: An internal error has occured. [ Internal error. ]
                                                                           at com.google.android.gms.tasks.zzh.getResult(Unknown Source)
                                                                           at com.firebase.ui.auth.ui.AcquireEmailHelper$1.onComplete(AcquireEmailHelper.java:57)
                                                                           at com.google.android.gms.tasks.zzc$1.run(Unknown Source)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:145)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5951)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
                                                                        Caused by: com.google.firebase.FirebaseException: An internal error has occured. [ Internal error. ]
                                                                           at com.google.android.gms.internal.zzacq.zzbN(Unknown Source)
                                                                           at com.google.android.gms.internal.zzacn$zzg.zza(Unknown Source)
                                                                           at com.google.android.gms.internal.zzacy.zzbO(Unknown Source)
                                                                           at com.google.android.gms.internal.zzacy$zza.onFailure(Unknown Source)
                                                                           at com.google.android.gms.internal.zzact$zza.onTransact(Unknown Source)
                                                                           at android.os.Binder.execTransact(Binder.java:446)

**Comment by iainmcgin** [comment]
Hey,

This issue is already fixed for the next release of Firebase Auth; the library will correctly throw a network error in this case. We'll need to test that we're handling this new exception in FirebaseUI appropriately, so I'll leave this open until we confirm it's fixed when the new version lands.

**Comment by kz** [comment]
@iainmcgin Has the new version you mentioned been released yet?

I tested the authentication flow without a network connection and received the following:
```
07-12 15:49:26.080 9698-9698/in.iamkelv.golink W/AcquireEmailHelper: Error fetching providers for email
                                                                     com.google.firebase.FirebaseNetworkException: A network error (such as timeout, interrupted connection or unreachable host) has occurred.
                                                                         at com.google.android.gms.internal.zzafg.zzes(Unknown Source)
                                                                         at com.google.android.gms.internal.zzafd$zzg.zza(Unknown Source)
                                                                         at com.google.android.gms.internal.zzafo.zzet(Unknown Source)
                                                                         at com.google.android.gms.internal.zzafo$zza.onFailure(Unknown Source)
                                                                         at com.google.android.gms.internal.zzafj$zza.onTransact(Unknown Source)
                                                                         at android.os.Binder.execTransact(Binder.java:453)
```

Is there a way I can neatly handle `com.google.firebase.FirebaseNetworkException`? It would be good to let the user know that the connection failed.

**Comment by samtstern** [comment]
@kz I just released version 0.4.3, I am not exactly sure which commit Iain was referencing but can you check if your issue was fixed?

**Comment by kz** [comment]
@samtstern Thanks for your reply. Unfortunately, I have decided to go with FirebaseJS in an Ionic app instead. If I do get this error again while using Firebase for Android in the future, I will be sure to let you know.

**Comment by samtstern** [comment]
@kz good luck with Ionic!  Closing this issue for now, if someone else has the same problem they can open a fresh issue.

**Comment by ulohani90** [comment]
Still facing this issue on Android 5.0 . Updated firebase core to 10.0.1.

**Comment by katie1006** [comment]
Got this crash using firebase-auth 15.0.0
