### ISSUE TITLE
Firebase Auth UI Unable to start activity "AuthMethodPickerActivity" Marshmallow

### ISSUE THREAD

**Issue by ahmermughal** [firebase/FirebaseUI-Android#1643]
Device Info:
  * Android device: Nexus 6P
  * Android OS version: Marshmallow (23)
  * Firebase/Play Services SDK version: firebase:firebase-core:16.0.9, firebase:firebase-auth:17.0.0
  * FirebaseUI version: firebase-ui-auth:5.0.0
  

When I try to run it on Oreo and Pie the Firebase auth UI works perfectly fine but when using Marshmallow the app crashes. The error is Unable to start activity (com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity)
Please look at the logs below

Logs:

```
    Process: com.idevelopstudio.looter, PID: 5532
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.idevelopstudio.looter/com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f080142
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f080142
        at android.content.res.Resources.getValue(Resources.java:1351)
        at android.content.res.Resources.getDrawable(Resources.java:804)
        at android.content.Context.getDrawable(Context.java:458)
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:3934)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:3981)
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:1969)
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:575)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:141)
        at com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity.onCreate(AuthMethodPickerActivity.java:97)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
  ```

**Comment by samtstern** [comment]
Thanks for reporting this @ahmermughal, looks like something is going wrong looking up a resource in `AuthMethodPickerActivity.onCreate(AuthMethodPickerActivity.java:97)`. 

I will try and reproduce this myself.

**Comment by Velocity-** [comment]
Any update on this, @samtstern? I'm hesitant to update to 5.0.0 because of this issue. We have a lot of Marshmallow users, so I'm trying to be careful here.

**Comment by samtstern** [comment]
@Velocity- and @ahmermughal I can't reproduce this problem ... I was able to launch the sample app from this repo on an Android 23 (Marshmallow) emulator with no problem and complete a basic authentication flow.

Can you try with the sample app in this repo (run the `app` module) and see if you get a crash on your device?  If you don't get a crash then this means there's something else going wrong in your app.  Even though the crash is in FirebaseUI, it could be related to the other dependencies you have or how your app's own resources are being merged in,

**Comment by rami-alloush** [comment]
I'm facing this issue on Android 6.0 as well. Works perfect on other version. Any thoughts ?

**Comment by tonmoym2mx** [comment]
I was get the same problem . I was add .setLogo(R.drawable.logoname)  and that logo was drawable-24 so it crashes .

**Comment by rami-alloush** [comment]
Thanks, yeah it seems to be icon related on my side as well. Thanks again.
