### ISSUE TITLE
.enableAnonymousUsersAutoUpgrade() problem 

### ISSUE THREAD

**Issue by tharsoma** [firebase/FirebaseUI-Android#1654]
Similar to https://github.com/firebase/FirebaseUI-Android/issues/1475
<img width="924" alt="Screen Shot 2019-07-12 at 5 16 10 PM" src="https://user-images.githubusercontent.com/52842703/61164834-daf12b00-a4cd-11e9-8358-aed23cdda104.png">

**The problem:**
When enable .enableAnonymousUsersAutoUpgrade() in AuthUI.getInstance().createSignInIntentBuilder(), and after signing in anonymously and then signing with Twitter/Facebook account that does not have an email attached to their accounts, gives an error "Unkown error". However, when signing in anonymously and then signing in with Twitter/Facebook account that has an email attached to them, things work fine. 

It looks like enableAnonymousUsersAutoUpgrade() have an issue when trying to upgrade an anonymous account using Twitter/Facebook account which doesn't have an email attached to them.

**Steps to reproduce:**
1. Sign in anonymously
2. Sign in Twitter/Facebook account that does not have an email attached their accounts.

**Observed Results:**
07-12 17:14:10.282 10030-10030/com.com2us.pixelgo.android.google.global.normal.pixelbnb E/AuthUI: A sign-in error occurred.
    java.lang.NullPointerException: Email cannot be empty
        at com.firebase.ui.auth.util.data.ProviderUtils.fetchSortedProviders(ProviderUtils.java:191)
        at com.firebase.ui.auth.viewmodel.idp.SocialProviderResponseHandler$1.onFailure(SocialProviderResponseHandler.java:85)
        at com.google.android.gms.tasks.zzl.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7224)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by unace** [comment]
I am also experiencing the same issue. Anyone else having the same issue?

**Comment by demolaf** [comment]
Hello,

Thank you for taking the time to submit this bug.

We are happy to let you know that this has been resolved in **FirebaseUI for Android v10.0.0**, which is now available as a beta release. You can find the release notes [here](https://github.com/firebase/FirebaseUI-Android/releases/tag/10.0.0-beta02) and follow the [upgrade guide](https://github.com/firebase/FirebaseUI-Android/blob/master/docs/upgrade-to-10.0.md) to get started.

We will close this issue now. If you still experience this in the new version, please feel free to open a new issue.

Thank you again for your contribution.
