### ISSUE TITLE
Unable to sign in with email provider if Google services not present and existing account was created under Google provider

### ISSUE THREAD

**Issue by Deishelon** [firebase/FirebaseUI-Android#1941]
### [REQUIRED] Describe your environment

  * Operating System version: Android 9.0 / 11

  * Firebase UI version: 7.1.1
  * Firebase SDK version: firebase-core:18.0.3 and firebase-auth:20.0.4

#### Steps to reproduce:

1) Create an account with Google as the provider on a device / emulator with Google Play services
2) Log out & try login in with email address (email provider) - this will work. 
3) Now, switch to an emulator / device without Google Play Services, and try to login using the same email.
4) You will get sign-in error.

```
2021-05-09 15:14:46.223 3876-3876/com.example.app E/AuthUI: A sign-in error occurred.
    com.firebase.ui.auth.FirebaseUiException: Developer error
        at com.firebase.ui.auth.r.e.h$a.d(ProviderUtils.java:17)
        at com.firebase.ui.auth.r.e.h$a.a(ProviderUtils.java:1)
        at com.google.android.gms.tasks.s.run(com.google.android.gms:play-services-tasks@@17.1.0:1)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at e.c.b.b.b.l.a.dispatchMessage(com.google.android.gms:play-services-tasks@@17.1.0:1)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2021-05-09 15:14:46.490 3876-3876/com.example.app E/AuthUI: A sign-in error occurred.
    com.firebase.ui.auth.FirebaseUiException: Developer error
        at com.firebase.ui.auth.ui.email.EmailActivity.Q(EmailActivity.java:2)
        at com.firebase.ui.auth.ui.email.EmailActivity.r(EmailActivity.java:1)
        at com.firebase.ui.auth.ui.email.a$a.c(CheckEmailFragment.java:3)
        at com.firebase.ui.auth.s.d.b(ResourceObserver.java:13)
        at com.firebase.ui.auth.s.d.a(ResourceObserver.java:1)
        at androidx.lifecycle.LiveData.d(LiveData.java:6)
        at androidx.lifecycle.LiveData.e(LiveData.java:8)
        at androidx.lifecycle.LiveData.o(LiveData.java:4)
        at androidx.lifecycle.d0.o(MutableLiveData.java:1)
        at com.firebase.ui.auth.s.b.k(OperableViewModel.java:1)
        at com.firebase.ui.auth.ui.email.b.p(CheckEmailHandler.java:1)
        at com.firebase.ui.auth.ui.email.b$a.a(CheckEmailHandler.java:5)
        at com.google.android.gms.tasks.w.run(com.google.android.gms:play-services-tasks@@17.1.0:3)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at e.c.b.b.b.l.a.dispatchMessage(com.google.android.gms:play-services-tasks@@17.1.0:1)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
#### Expected outcome:
If a user created account with Google, and then tries to sign in with email (on a device where Google Play Services are not present) - the user will be able to log-in successfully. 

#### Relevant Code:
The most basic app auth set up, the issue is on the library side, as I would expect it to carry on & log in user with email

**Comment by Deishelon** [comment]
Yes, I do check for play services.

My logic if play services available allow google and email login. 
If not only email login.

But this leaves with a case, when user had google services and created account with google.

Then updated the phone which does not have Google services, and now locked out of the account.

**Comment by samtstern** [comment]
@Deishelon unfortunately there is no way for the user to access that account on that device.

**Comment by Deishelon** [comment]
That seems a bit of an issue. Would me deleting the user account in firebase and user creating new one work? 

And then manually migrating user data to the new account? 

If I were not to use firebase - would I have this issue too?

**Comment by samtstern** [comment]
@Deishelon yes deleting the account and re-creating it using a non-Google identity provider would work. And yes this issue is not a Firebase issue, it's a fundamental issue with Google Sign In (GSI). GSI does not work  on devices without Play services.
