### ISSUE TITLE
java.lang.RuntimeException: Unable to resume activity {/com.facebook.FacebookActivity}

### ISSUE THREAD

**Issue by zung** [firebase/FirebaseUI-Android#1977]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: _Pixel 2____
  * Android OS version: __11___
  * Google Play Services version: __21.21.16___
  * Firebase/Play Services SDK version: __bom 28.1.0___
  * FirebaseUI version: __7.2.0__
  * Facebook-Android-Sdk version:__8.1.0__
  
### Step 3: Describe the problem:
it crash when use facebook login.

  * What happened?  This could be a description, `logcat` output, etc.
  ```
2021-07-13 15:42:45.432 31531-31531**** E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ***, PID: 31531
    java.lang.RuntimeException: Unable to resume activity {packagename/com.facebook.FacebookActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4444)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
        at com.facebook.login.LoginFragment$2.onBackgroundProcessingStarted(LoginFragment.java:110)
        at com.facebook.login.LoginClient.notifyBackgroundProcessingStart(LoginClient.java:397)
        at com.facebook.login.GetTokenLoginMethodHandler.tryAuthorize(GetTokenLoginMethodHandler.java:65)
        at com.facebook.login.LoginClient.tryCurrentHandler(LoginClient.java:280)
        at com.facebook.login.LoginClient.tryNextHandler(LoginClient.java:233)
        at com.facebook.login.LoginClient.authorize(LoginClient.java:120)
        at com.facebook.login.LoginClient.startOrContinueAuth(LoginClient.java:101)
        at com.facebook.login.LoginFragment.onResume(LoginFragment.java:161)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:3026)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:604)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:306)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1636)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3112)
        at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:3070)
        at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:273)
        at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:434)
        at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:423)
        at android.app.Activity.performResume(Activity.java:8160)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4434)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
  ```
  
#### Expected Results:

  * What did you expect to happen?
  Able to log in with facebook normally！

**Comment by samtstern** [comment]
@zung I don't see anything in that stack trace which references `com.firebase` or `com.firebaseui` so I don't think this is an actual FirebaseUI bug. Do you have some proof that it is?

**Comment by zung** [comment]
I'm sorry, I should be in the wrong place！Can you help me delete this issue?

**Comment by zung** [comment]
I have integrated firebase-ui-auth and facebook-android-sdk according to the firebase documentation, but the facebbok login has been unsuccessful and this exception has been reported.

**Comment by samtstern** [comment]
@zung it looks like the issue is in the Facebook SDK, based on this line:
```
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
      at com.facebook.login.LoginFragment$2.onBackgroundProcessingStarted(LoginFragment.java:110)
```

I'd try asking on StackOverflow or finding one of Facebook's GitHub repos (if they exist). Good luck!

**Comment by zung** [comment]
@samtstern I found a solution here https://github.com/facebook/facebook-android-sdk/issues/698#issuecomment-592828072、https://github.com/facebook/facebook-android-sdk/issues/698#issuecomment-646059083
