### ISSUE TITLE
App is not launched

### ISSUE THREAD

**Issue by saka7252** [firebase/FirebaseUI-Android#1990]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: SM-G973N
  * Android OS version: 11
  * Google Play Services version: ?
  * Firebase/Play Services SDK version: ?
  * FirebaseUI version: 8.0.0
  
#### Steps to reproduce:

  1. Download full source code('https://github.com/firebase/FirebaseUI-Android')
  2. Build & Run project 
  3. Launch succeeded message is displayed. 
  4. Click Firebase UI's Launcher Icon in Android Device(SM-G973N)
  5. App is not installed message is displayed. 
  6. App is not working....
  
#### Observed Results:

2021-08-09 17:17:41.840 5288-5288/? E/ProActiveLaunch: Sending Broadcast
2021-08-09 17:17:41.842 3842-4126/? E/ActivityManager: Checking for the Active launch isPkgEverLaunched :false, isPkgStopped : true
2021-08-09 17:17:41.931 5288-5288/? E/AppStartUtils: Launcher does not have the permission to launch Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.firebase.uidemo/.ChooserActivity bnds=[542,1701][789,1981] (has extras) }. Make sure to create a MAIN intent-filter for the corresponding activity or use the exported attribute for this activity. tag=IconInfo(title=Firebase UI intent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.firebase.uidemo/.ChooserActivity (has extras) } id=90 type=0 container=-102 screen=0 cellX=2 cellY=5 spanX=1 spanY=1 rank=22 hidden=0 dropPos=null user=UserHandle{0} screenType=0) intent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.firebase.uidemo/.ChooserActivity bnds=[542,1701][789,1981] (has extras) }
    java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.firebase.uidemo/.ChooserActivity bnds=[542,1701][789,1981] (has extras) } from ProcessRecord{aa1ec53d0 5288:com.sec.android.app.launcher/u0a91} (pid=5288, uid=10091) not exported from uid 10214
        at android.os.Parcel.createException(Parcel.java:1966)
        at android.os.Parcel.readException(Parcel.java:1934)
        at android.os.Parcel.readException(Parcel.java:1884)
        at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:3619)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1669)
        at android.app.Activity.startActivityForResult(Activity.java:4689)
        at android.app.Activity.startActivity(Activity.java:5004)
        at com.android.launcher3.framework.support.data.AppStartUtils.startActivitySafely(AppStartUtils.java:64)
        at com.android.launcher3.apptray.view.util.AppsUtils.startActivitySafely(AppsUtils.java:160)
        at com.android.launcher3.apptray.view.container.AppsContainer.startAppShortcutOrInfoActivity(AppsContainer.java:804)
        at com.android.launcher3.apptray.view.container.AppsContainer.onClick(AppsContainer.java:760)
        at com.android.launcher3.infra.stage.AppsStage.onClick(AppsStage.java:206)
        at com.android.launcher3.framework.view.features.stage.StageManagerImp.onClick(StageManagerImp.java:669)
        at com.android.launcher3.infra.activity.Launcher.onClick(Launcher.java:1184)
        at android.view.View.performClick(View.java:7352)
        at android.view.View.performClickInternal(View.java:7318)
        at android.view.View.access$3200(View.java:846)
        at android.view.View$PerformClick.run(View.java:27800)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:2144)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:908)
[new 2.txt](https://github.com/firebase/FirebaseUI-Android/files/6952943/new.2.txt)

        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:671)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1548)
        at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:612)
2021-08-09 17:17:43.938 3311-4009/? E/BufferQueueProducer: [Toast[5288]#0] disconnect: not connected (req=1)
2021-08-09 17:17:48.530 5031-5031/? E/cr_BTSPrefs: No data found for task id: 53
2021-08-09 17:17:48.531 5031-5031/? E/cr_BkgrdTaskScheduler: Task cannot be canceled because no data was found instorage or data was invalid
2021-08-09 17:17:52.657 3528-3645/? E/storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
2021-08-09 17:17:53.168 5031-5031/? E/chromium: [ERROR:merchant_viewer_data_manager.cc(106)] Clearing 3 merchants.
2021-08-09 17:17:53.987 3842-7787/? E/BartenderActivityManager: BarTender: pid : 5147 cached=true abnormal=false kill=false stay=false release=false
2021-08-09 17:17:57.174 3842-4302/? E/Watchdog: !@Sync 2208 [2021-08-09 17:17:57.174] FD count : 552
2021-08-09 17:18:00.044 5288-5288/? E/LiveIconManager: createLiveIconBitmap : com.sec.android.app.clockpackage apps size 1
2021-08-09 17:18:00.907 3842-6040/? E/BartenderActivityManager: BarTender: pid : 5134 cached=true abnormal=false kill=false stay=false release=false

  
#### Expected Results:

  * What did you expect to happen?
  * FirebaseUI-Android app should be work.
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by monteiroman** [comment]
Same problem here.

**Comment by AdityaBavadekar** [comment]
This seems like a manifest problem.

**Comment by thatfiredev** [comment]
Sorry I missed this issue earlier. Thanks for bumping this thread @AdityaBavadekar

That's right, exported need to be set to `true`. The fix has now been pushed to our main branch.
