### ISSUE TITLE
FirebaseRecyclerAdapter and FirestoreRecyclerAdapter error recreate activity or adapter updateOptions

### ISSUE THREAD

**Issue by OneDevUA** [firebase/FirebaseUI-Android#2014]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ua.dev.notifycloud, PID: 27882
    java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionNotifyViewHolder{3a08004 position=3 id=-1, oldPos=1, pLpos:1 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{e22214 VFED..... ......ID 0,0-1080,1645 #7f080193 app:id/rv}, adapter:ua.dev.notifycloud.ui.AppActivity$getAdapter$1@b277bf8, layout:androidx.recyclerview.widget.LinearLayoutManager@622cabd, context:ua.dev.notifycloud.ui.AppActivity@802f278
        at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:6156)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6339)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4255)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4010)
        at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:2028)
        at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:417)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:722)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by Shailevy** [comment]
+1

**Comment by thatfiredev** [comment]
@OneDevUA From what I'm seeing, none of the lines in this stacktrace point to FirebaseUI. Maybe you could share the source code of your adapter?

**Comment by samuel22gj** [comment]
On the latest version **2.8.0**. I also encountered this problem. I use `startListening()` and `stopListening()` manually instead of setup `setLifecycleOwner()` for automatic start/stop to solve this.

BTW, the reproduce flow is:
1. open a screen with `FirestoreRecyclerAdapter` and 
 setup with `setLifecycleOwner()`
2. press the home button
3. reopen app from recent app

Hope it can be fixed in the future.

ref: https://firebaseopensource.com/projects/firebase/firebaseui-android/firestore/readme/

**Comment by ParryPatel021** [comment]
I have resolved this issue by calling `stopListening()` from `onDestroy()` of Activity Instead of calling it from `onStop()`.
It seems that after calling `stopListening()` it does not start when it returns to the same Activity.

Library Version:`implementation 'com.firebaseui:firebase-ui-firestore:8.0.2'`
