### ISSUE TITLE
The format of the phone number provided is incorrect

### ISSUE THREAD

**Issue by OneDevUA** [firebase/FirebaseUI-Android#2015]
E/FirebaseAuth: [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17042 TOO_SHORT
E/AuthUI: A sign-in error occurred.
    com.google.firebase.auth.FirebaseAuthInvalidCredentialsException: The format of the phone number provided is incorrect. Please enter the phone number in a format that can be parsed into E.164 format. E.164 phone numbers are written in the format [+][country code][subscriber number including area code]. [ TOO_SHORT ]
        at com.google.android.gms.internal.firebase-auth-api.zzto.zza(com.google.firebase:firebase-auth@@21.0.1:28)
        at com.google.android.gms.internal.firebase-auth-api.zzus.zza(com.google.firebase:firebase-auth@@21.0.1:1)
        at com.google.android.gms.internal.firebase-auth-api.zzut.run(com.google.firebase:firebase-auth@@21.0.1:3)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by thatfiredev** [comment]
@OneDevUA can you tell us which phone number you're inputting?
