### ISSUE TITLE
PID: 3346     com.google.firebase.database.DatabaseException: Found conflicting getters for name: getOverlay

### ISSUE THREAD

**Issue by alejandroR9** [firebase/FirebaseUI-Android#2044]
I get an error in this

```java
package com.example.alphaapporiginal;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import com.example.alphaapporiginal.Modal.Productos;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;
import com.mcdev.quantitizerlibrary.HorizontalQuantitizer;
import com.squareup.picasso.Picasso;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;

public class ProductoDetallesActivity extends AppCompatActivity {

private Button agregarCarrito;
private HorizontalQuantitizer numeroBoton;
private ImageView productoImagen;
private TextView productoPrecio,productoDescripcion,productoNombre;
private String productoID = "", estado= "Normal",CurrentUserID;
private FirebaseAuth auth;

[@OverRide](https://github.com/OverRide)
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_producto_detalles);

    productoID = getIntent().getStringExtra("pid");

    agregarCarrito=(Button) findViewById(R.id.boton_siguiente_detalles);
    numeroBoton=(HorizontalQuantitizer)findViewById(R.id.numero_boton);
    productoImagen=(ImageView)findViewById(R.id.producto_imagen_detalles);
    productoPrecio=(TextView)findViewById(R.id.producto_precio_detalles);
    productoDescripcion=(TextView)findViewById(R.id.producto_descripcion_detalles);
    productoNombre=(TextView)findViewById(R.id.producto_nombre_detalles);
    ObtenerDatosProducto(productoID);
    auth=FirebaseAuth.getInstance();
    CurrentUserID = auth.getCurrentUser().getUid();
    agregarCarrito.setOnClickListener(new View.OnClickListener() {
        [@OverRide](https://github.com/OverRide)
        public void onClick(View v) {
            if (estado.equals("Pedido") || estado.equals("Enviado")){
                Toast.makeText(ProductoDetallesActivity.this,
"Esperando a que el primero pedido finalice.....",
Toast.LENGTH_SHORT).show();
            }else{
                agregarAlaLista();
            }
        }
    });

}

[@OverRide](https://github.com/OverRide)
protected void onStart() {
    super.onStart();
    VerificarEstadoOrden();
}
private void agregarAlaLista() {

        String CurrentTime,CurrentDate;
        Calendar calendar = Calendar.getInstance();
        SimpleDateFormat data = new SimpleDateFormat("MM-dd-yyyy");
        CurrentDate=data.format(calendar.getTime());
        SimpleDateFormat time = new SimpleDateFormat("HH:mm:ss");
        CurrentTime=time.format(calendar.getTime());

        final DatabaseReference CartListRef =
FirebaseDatabase.getInstance("[https://alphaapporiginal-default-rtdb.firebaseio.com/").getReference().child("Carrito](https://alphaapporiginal-default-rtdb.firebaseio.com/%22).getReference().child(%22Carrito)");

        final HashMap<String,Object> map = new HashMap<>();
        map.put("pid",productoID);
        map.put("nombre",productoNombre.getText().toString());
        map.put("precio",productoPrecio.getText().toString());
        map.put("fecha",CurrentDate);
        map.put("hora",CurrentTime);
        map.put("cantidad",numeroBoton);
        map.put("descuento","");

        CartListRef.child("Usuario
Compra").child(CurrentUserID).child("Productos").child(productoID).updateChildren(map).addOnCompleteListener(new
OnCompleteListener<Void>() {
            [@OverRide](https://github.com/OverRide)
            public void ***@***.*** Task<Void> task) {
                if (task.isSuccessful()){

CartListRef.child("Administracion").child(CurrentUserID).child("Productos").child(productoID).updateChildren(map).addOnCompleteListener(new
OnCompleteListener<Void>() {
                        [@OverRide](https://github.com/OverRide)
                        public void ***@***.*** Task<Void> task) {
                            if (task.isSuccessful()){

Toast.makeText(ProductoDetallesActivity.this, "Agregado...",
Toast.LENGTH_SHORT).show();

                                Intent intent = new
Intent(ProductoDetallesActivity.this,PrincipalActivity.class);
                                startActivity(intent);
                            }
                        }
                    });
                }
            }
        });


}
private void ObtenerDatosProducto(String productoID) {
    DatabaseReference ProductoRef =
FirebaseDatabase.getInstance("[https://alphaapporiginal-default-rtdb.firebaseio.com/").getReference().child("Productos](https://alphaapporiginal-default-rtdb.firebaseio.com/%22).getReference().child(%22Productos)");
    ProductoRef.child(productoID).addValueEventListener(new
ValueEventListener() {
        [@OverRide](https://github.com/OverRide)
        public void ***@***.*** DataSnapshot snapshot) {
            if (snapshot.exists()){
                Productos productos = snapshot.getValue(Productos.class);
                productoNombre.setText(productos.getNombre());
                productoDescripcion.setText(productos.getDescripcion());
                productoPrecio.setText(productos.getPrecioven());
                Picasso.get().load(productos.getImagen()).into(productoImagen);
            }
        }

        [@OverRide](https://github.com/OverRide)
        public void ***@***.*** DatabaseError error) {

        }
    });
}

private void VerificarEstadoOrden() {
    DatabaseReference OrdenRef;
    OrdenRef= FirebaseDatabase.getInstance("[https://alphaapporiginal-default-rtdb.firebaseio.com/").getReference().child("Ordenes").child(CurrentUserID](https://alphaapporiginal-default-rtdb.firebaseio.com/%22).getReference().child(%22Ordenes%22).child(CurrentUserID));
    OrdenRef.addValueEventListener(new ValueEventListener() {
        [@OverRide](https://github.com/OverRide)
        public void ***@***.*** DataSnapshot snapshot) {
            if (snapshot.exists()){
                String envioStado =
snapshot.child("estado").getValue().toString();
                if (envioStado.equals("Enviado")){
                    estado="Enviado";

                }else if (envioStado.equals("No enviado")){
                    estado="Pedido ";

                }
            }
        }

        [@OverRide](https://github.com/OverRide)
        public void ***@***.*** DatabaseError error) {

        }
    });
}

}

```
........................LOGCAT

```
2022-07-01 12:18:04.617 3346-3346/com.example.alphaapporiginal
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example.alphaapporiginal, PID: 3346
com.google.firebase.database.DatabaseException: Found conflicting getters
for name: getOverlay
at
com.google.firebase.database.core.utilities.encoding.CustomClassMapper$BeanMapper.(CustomClassMapper.java:478)
at
com.google.firebase.database.core.utilities.encoding.CustomClassMapper.loadOrCreateBeanMapperForClass(CustomClassMapper.java:330)
at
com.google.firebase.database.core.utilities.encoding.CustomClassMapper.serialize(CustomClassMapper.java:167)
at
com.google.firebase.database.core.utilities.encoding.CustomClassMapper.serialize(CustomClassMapper.java:142)
at
com.google.firebase.database.core.utilities.encoding.CustomClassMapper.convertToPlainJavaTypes(CustomClassMapper.java:66)
at
com.google.firebase.database.DatabaseReference.updateChildrenInternal(DatabaseReference.java:412)
at
com.google.firebase.database.DatabaseReference.updateChildren(DatabaseReference.java:392)
at
com.example.alphaapporiginal.ProductoDetallesActivity.agregarAlaLista(ProductoDetallesActivity.java:94)
at
com.example.alphaapporiginal.ProductoDetallesActivity.access$100(ProductoDetallesActivity.java:31)
at
com.example.alphaapporiginal.ProductoDetallesActivity$1.onClick(ProductoDetallesActivity.java:62)
at android.view.View.performClick(View.java:7448)
at
com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1194)
at android.view.View.performClickInternal(View.java:7425)
at android.view.View.access$3600(View.java:810)
at android.view.View$PerformClick.run(View.java:28305)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7656)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)


THIS IS MY CLASS

package com.example.alphaapporiginal.Modal;

public class Productos {

    private String
nombre,descripcion,precioven,imagen,categoria,pid,fecha,hora,cantidad,preciocom;

    public Productos(){}

    public Productos(String nombre, String descripcion, String
precioven, String imagen, String categoria, String pid, String fecha,
String hora, String cantidad, String preciocom) {
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.precioven = precioven;
        this.imagen = imagen;
        this.categoria = categoria;
        this.pid = pid;
        this.fecha = fecha;
        this.hora = hora;
        this.cantidad = cantidad;
        this.preciocom = preciocom;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getPrecioven() {
        return precioven;
    }

    public void setPrecioven(String precioven) {
        this.precioven = precioven;
    }

    public String getImagen() {
        return imagen;
    }

    public void setImagen(String imagen) {
        this.imagen = imagen;
    }

    public String getCategoria() {
        return categoria;
    }

    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    public String getPid() {
        return pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public String getHora() {
        return hora;
    }

    public void setHora(String hora) {
        this.hora = hora;
    }

    public String getCantidad() {
        return cantidad;
    }

    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }

    public String getPreciocom() {
        return preciocom;
    }

    public void setPreciocom(String preciocom) {
        this.preciocom = preciocom;
    }
}
HELP PLEASE

**Comment by thatfiredev** [comment]
I'm closing this issue as it is not related to FirebaseUI

**Comment by alejandroR9** [comment]
Please help me I put the code that you told me and I got this error:
2022-07-04 21:32:13.215 3488-3488/com.example.alphaapporiginal E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.alphaapporiginal, PID: 3488
    com.google.firebase.database.DatabaseException: Failed to convert value of type java.lang.Long to String
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.convertString(CustomClassMapper.java:426)
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.deserializeToClass(CustomClassMapper.java:217)
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.deserializeToType(CustomClassMapper.java:179)
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.access$100(CustomClassMapper.java:48)
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper$BeanMapper.deserialize(CustomClassMapper.java:593)
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper$BeanMapper.deserialize(CustomClassMapper.java:563)
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.convertBean(CustomClassMapper.java:433)
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.deserializeToClass(CustomClassMapper.java:232)
        at com.google.firebase.database.core.utilities.encoding.CustomClassMapper.convertToCustomClass(CustomClassMapper.java:80)
        at com.google.firebase.database.DataSnapshot.getValue(DataSnapshot.java:203)
        at com.firebase.ui.database.ClassSnapshotParser.parseSnapshot(ClassSnapshotParser.java:29)
        at com.firebase.ui.database.ClassSnapshotParser.parseSnapshot(ClassSnapshotParser.java:15)
        at com.firebase.ui.common.BaseCachingSnapshotParser.parseSnapshot(BaseCachingSnapshotParser.java:36)
        at com.firebase.ui.common.BaseObservableSnapshotArray.get(BaseObservableSnapshotArray.java:52)
        at com.firebase.ui.database.FirebaseRecyclerAdapter.getItem(FirebaseRecyclerAdapter.java:109)
        at com.firebase.ui.database.FirebaseRecyclerAdapter.onBindViewHolder(FirebaseRecyclerAdapter.java:149)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1897)
        at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:414)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by alejandroR9** [comment]
Please help me I put the code that you told me and I got this error:
2022-07-04 21:32:13.215 3488-3488/com.example.alphaapporiginal
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example.alphaapporiginal, PID: 3488
com.google.firebase.database.DatabaseException: Failed to convert value of
type java.lang.Long to String
at
com.google.firebase.database.core.utilities.encoding.CustomClassMapper.convertString(CustomClassMapper.java:426)
at
com.google.firebase.database.core.utilities.encoding.CustomClassMapper.deserializeToClass(CustomClassMapper.java:217)
at
com.google.firebase.database.core.utilities.encoding.CustomClassMapper.deserializeToType(CustomClassMapper.java:179)
at
com.google.firebase.database.core.utilities.encoding.CustomClassMapper.access$100(CustomClassMapper.java:48)
at
com.google.firebase.database.core.utilities.encoding.CustomClassMapper$BeanMapper.deserialize(CustomClassMapper.java:593)
at
com.google.firebase.database.core.utilities.encoding.CustomClassMapper$BeanMapper.deserialize(CustomClassMapper.java:563)
at
com.google.firebase.database.core.utilities.encoding.CustomClassMapper.convertBean(CustomClassMapper.java:433)
at
com.google.firebase.database.core.utilities.encoding.CustomClassMapper.deserializeToClass(CustomClassMapper.java:232)
at
com.google.firebase.database.core.utilities.encoding.CustomClassMapper.convertToCustomClass(CustomClassMapper.java:80)
at com.google.firebase.database.DataSnapshot.getValue(DataSnapshot.java:203)
at
com.firebase.ui.database.ClassSnapshotParser.parseSnapshot(ClassSnapshotParser.java:29)
at
com.firebase.ui.database.ClassSnapshotParser.parseSnapshot(ClassSnapshotParser.java:15)
at
com.firebase.ui.common.BaseCachingSnapshotParser.parseSnapshot(BaseCachingSnapshotParser.java:36)
at
com.firebase.ui.common.BaseObservableSnapshotArray.get(BaseObservableSnapshotArray.java:52)
at
com.firebase.ui.database.FirebaseRecyclerAdapter.getItem(FirebaseRecyclerAdapter.java:109)
at
com.firebase.ui.database.FirebaseRecyclerAdapter.onBindViewHolder(FirebaseRecyclerAdapter.java:149)
at
androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
at
androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
at
androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
at
androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
at
androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
at
androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
at
androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
at
androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
at
androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
at
androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
at
androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
at
androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
at
androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1897)
at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:414)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
at android.view.Choreographer.doCallbacks(Choreographer.java:796)
at android.view.Choreographer.doFrame(Choreographer.java:727)
at
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7656)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by thatfiredev** [comment]
@alejandroR9 so it looks like getValue actually returns a `Long`, so you might want to convert into a `String` before sending to the database:
```java
map.put("cantidad", numeroBoton.getValue() + "");
```

Also, the crash might still happen because you've already added some Long values to the database. So you'll want to find these records and delete them from your database.
