### ISSUE TITLE
Stop at processing animation when loading UI

### ISSUE THREAD

**Issue by choisyin** [firebase/FirebaseUI-Android#2051]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: Sony Xperia Premium
  * Android OS version: 9
  * com.google.firebase:firebase-bom:30.3.1
  * com.firebaseui:firebase-ui-***: 8.0.1
  
### Step 3: Describe the problem:
The firebase UI works fine several weeks ago. However, it comes the problem that can't enter into UI and just stop at processing animation.

  
#### Expected Results:
  Work fine.
   

Thank you so much.

**Comment by shrutip90** [comment]
Could you please give us some more information on what method causes the hang and the logs or any stack traces that you are seeing?

**Comment by choisyin** [comment]
The following is the code. I set it up in the onCreate.

       public void setSignInUI() {
        List<AuthUI.IdpConfig> providers = Arrays.asList(
                new AuthUI.IdpConfig.EmailBuilder().build(),
                new AuthUI.IdpConfig.PhoneBuilder().build(),
                new AuthUI.IdpConfig.GoogleBuilder().build(),
                new AuthUI.IdpConfig.FacebookBuilder().build(),
                new AuthUI.IdpConfig.TwitterBuilder().build());

        // Create and launch sign-in intent
        Intent signInIntent = AuthUI.getInstance()
                .createSignInIntentBuilder()
                .setAvailableProviders(providers)
                .setLogo(R.drawable.my_great_logo)      // Set logo drawable
                .setTheme(R.style.MySuperAppTheme)      // Set theme
                .build();


        signInLauncher.launch(signInIntent);
        UserLoggingActivity.buildActionCodeSettings();


        }

The log output. There is a security exception that seems relate to the issue.

`I/SnapshotHandler: Unable to retrieve flag snapshot for com.google.android.libraries.consentverifier#com.example.find_other_current_place_java, using defaults.
W/MobStoreFlagStore: Unable to update local snapshot for com.google.android.libraries.consentverifier#com.example.find_other_current_place_java, may result in stale flags.
    java.util.concurrent.ExecutionException: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.example.find_other_current_place_java, sha256=[f576c742eb100b82f8957b433bb6d3bde9da1a229259a2f74276f641f67199ae], atk=false, ver=222615030.true (go/gsrlt)
        at aif.s(:com.google.android.gms.dynamite_mapsdynamite@222615067@22.26.15 (100408-0):3)
        at aif.get(:com.google.android.gms.dynamite_mapsdynamite@222615067@22.26.15 (100408-0):2)
        at ajp.g(:com.google.android.gms.dynamite_mapsdynamite@222615067@22.26.15 (100408-0):2)
        at yg.d(:com.google.android.gms.dynamite_mapsdynamite@222615067@22.26.15 (100408-0):1)
        at yi.run(:com.google.android.gms.dynamite_mapsdynamite@222615067@22.26.15 (100408-0):0)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.example.find_other_current_place_java, sha256=[f576c742eb100b82f8957b433bb6d3bde9da1a229259a2f74276f641f67199ae], atk=false, ver=222615030.true (go/gsrlt)
        at android.os.Parcel.createException(Parcel.java:1969)
        at android.os.Parcel.readException(Parcel.java:1935)
        at android.os.Parcel.readException(Parcel.java:1885)
        at es.bc(:com.google.android.gms.dynamite_mapsdynamite@222615067@22.26.15 (100408-0):2)
        at rs.a(:com.google.android.gms.dynamite_mapsdynamite@222615067@22.26.15 (100408-0):4)
        at iz.e(:com.google.android.gms.dynamite_mapsdynamite@222615067@22.26.15 (100408-0):2)
        at jy.t(:com.google.android.gms.dynamite_mapsdynamite@222615067@22.26.15 (100408-0):2)
        at jy.u(:com.google.android.gms.dynamite_mapsdynamite@222615067@22.26.15 (100408-0):3)
        at jy.e(:com.google.android.gms.dynamite_mapsdynamite@222615067@22.26.15 (100408-0):2)
        at kc.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@222615067@22.26.15 (100408-0):69)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:280)
        at android.os.HandlerThread.run(HandlerThread.java:65)`
