### ISSUE TITLE
NoSuchMethodException in FirebaseRecyclerAdapter onCreateViewHolder 

### ISSUE THREAD

**Issue by stasbar** [firebase/FirebaseUI-Android#210]
* Android device: Nexus 6P
  * Android OS version: API 24
  * Firebase/Play Services SDK version: 9.2.0
  * FirebaseUI version: 0.4.2
  
Hello
I'm getting NoSuchMethodException in com.firebase.ui.database.FirebaseRecyclerAdapter onCreateViewHolder 
The code is the best description:

Init Reference, Adapter, RecyclerView

        commentsRef = FirebaseUtil.getGearCommentsRef().child(paths.get(currentPosition));
        commentsAdapter = new CommentsAdapter(commentsRef);
        rvComments.setAdapter(commentsAdapter);

My Adapter and ViewHolder classes
```
public class CommentsAdapter extends FirebaseRecyclerAdapter<Comment, CommentsAdapter.CommentViewHolder> {


    public CommentsAdapter(DatabaseReference ref) {
        super(Comment.class, R.layout.liquid_online_comment_row, CommentsAdapter.CommentViewHolder.class, ref);
    }

    @Override
    protected void populateViewHolder(CommentViewHolder viewHolder, Comment model, int position) {
        viewHolder.setContent(model.content);
    }

    class CommentViewHolder extends RecyclerView.ViewHolder {
        View view;
        
        public CommentViewHolder(View itemView) {
            super(itemView);
            view = itemView;
        }

        public void setContent(String comment){
            TextView field = (TextView) view.findViewById(R.id.text_view_comment_content);
            field.setText(comment);
        }

    }

}
```
Row Layout
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="horizontal" android:layout_width="match_parent"
    android:layout_height="wrap_content">
    <ImageView
        android:id="@+id/image_view_comment_content_avatar"
        android:layout_width="40dp"
        android:layout_height="40dp"
        android:layout_weight="0"
        android:src="@drawable/ic_action_account_box" />

    <TextView
        android:padding="8dp"
        android:id="@+id/text_view_comment_content"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_weight="1" />

</LinearLayout>
```

#### Observed Results:
```
java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [class android.view.View]
                                                                             at com.firebase.ui.database.FirebaseRecyclerAdapter.onCreateViewHolder(FirebaseRecyclerAdapter.java:165)
                                                                             at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5779)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5003)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
                                                                             at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
                                                                             at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
                                                                             at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
                                                                             at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
                                                                             at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
                                                                             at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2788)
                                                                             at android.view.View.measure(View.java:19730)
  
```

    @Override
    public VH onCreateViewHolder(ViewGroup parent, int viewType) {
        ViewGroup view = (ViewGroup) LayoutInflater.from(parent.getContext()).inflate(viewType, parent, false);
        try {
            Constructor<VH> constructor = mViewHolderClass.getConstructor(View.class);
            return constructor.newInstance(view);
        } catch (NoSuchMethodException e) {
            throw new RuntimeException(e);   <--------- HERE
        } catch (InvocationTargetException e) {
            throw new RuntimeException(e);
        } catch (InstantiationException e) {
            throw new RuntimeException(e);
        } catch (IllegalAccessException e) {
            throw new RuntimeException(e);
        }
    }

**Comment by stasbar** [comment]
The problem is that ViewHolder has to be static. So it should look like this:
```
static class CommentViewHolder extends RecyclerView.ViewHolder {
...
}
```

**Comment by puf** [comment]
The ViewHolder (and POJO class) only have to be static if you embed them
into another class.

For inner classes, the Java compiler generates an hidden field (and a
constructor that takes that field) to keep a reference to the containing
object, so that you can do things like `MainActivity.this` in instances of
the inner class. This hidden field/parameter makes it difficult for the
reflection code in Firebase/FirebaseUI to find the correct constructor.

Marking the class as static removes the implicit field/parameter, so things
work normally again. Alternatively you can just put the `CommentViewHolder`
in its own file `CommentViewHolder.java`.
