### ISSUE TITLE
android.content.res.Resources$NotFoundException since version 0.4.2

### ISSUE THREAD

**Issue by dabele91** [firebase/FirebaseUI-Android#213]
* Android device: Nexus 6P
  * Android OS version: 6.0.1
  * Google Play Services version: 9.2.0/9.2.1
  * Firebase/Play Services SDK version: 9.2.0/9.2.1
  * FirebaseUI version: 0.4.2
  
Since I've upgraded firebase to version 9.2.0/9.2.1 and firebase-ui to 0.4.2 i'm always receiving the following error when i want to use the FirebaseRecyclerAdapter:

```
android.content.res.Resources$NotFoundException: Resource ID #0x2
    at android.content.res.Resources.getValue(Resources.java:1351)
    at android.content.res.Resources.loadXmlResourceParser(Resources.java:2774)
    at android.content.res.Resources.getLayout(Resources.java:1165)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:421)
    at com.firebase.ui.database.FirebaseRecyclerAdapter.onCreateViewHolder(FirebaseRecyclerAdapter.java:160)
    at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5779)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5003)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4913)
    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
    at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:531)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
    at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3260)
    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3069)
    at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1505)
    at android.support.v7.widget.RecyclerView.access$400(RecyclerView.java:151)
    at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:305)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
    at android.view.Choreographer.doFrame(Choreographer.java:603)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

If i downgrade to version 0.4.1 everything works fine.
The error happens, when i'm overriding the getItemViewType Method.
I'm using a GridLayoutManager that checks the item view type and shows than one or two elements per row. (depends on the item view type result)

**Comment by dabele91** [comment]
Sorry, I've found the problem. In version 0.4.2 of firebase-ui, the firebase recycler adapter is also overriding and using this method.
