### ISSUE TITLE
Release builds return the error code 12500

### ISSUE THREAD

**Issue by mary-ng5519** [firebase/FirebaseUI-Android#2132]
the integration of 'com.firebaseui:firebase-ui-auth' returns error 12500, we already updated and check latest json configs, Android client ID (from goole cloud console) and SHA-5 extracted from release jsk, it work only debug build, in release builds, it returns the 12500 error code
*scope of evaluation: release builds for internal testing, doesnt push the release APK to PlayStore channels
```
Troubleshootings:
https://stackoverflow.com/questions/36185774/release-debug-version-and-authorization-google
https://stackoverflow.com/questions/51360250/firebase-ui-authentication-with-google-fails-with-message-code10-message10)
```
```
2023-06-17 02:11:40.003 29373-29373 AuthUI                  usap64                               E  A sign-in error occurred.
                                                                                                    com.firebase.ui.auth.FirebaseUiException: Code: 12500, message: 12500: 
                                                                                                    	at com.firebase.ui.auth.data.remote.GoogleSignInHandler.onActivityResult(GoogleSignInHandler.java:114)
                                                                                                    	at com.firebase.ui.auth.ui.idp.SingleSignInActivity.onActivityResult(SingleSignInActivity.java:144)
                                                                                                    	at android.app.Activity.dispatchActivityResult(Activity.java:8550)
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:5583)
                                                                                                    	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5631)
                                                                                                    	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8653)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2023-06-17 02:11:40.003 29373-29373 AuthUI                  usap64                               E  A sign-in error occurred.
                                                                                                    com.firebase.ui.auth.FirebaseUiException: Code: 12500, message: 12500: 
                                                                                                    	at com.firebase.ui.auth.data.remote.GoogleSignInHandler.onActivityResult(GoogleSignInHandler.java:114)
                                                                                                    	at com.firebase.ui.auth.ui.idp.SingleSignInActivity.onActivityResult(SingleSignInActivity.java:144)
                                                                                                    	at android.app.Activity.dispatchActivityResult(Activity.java:8550)
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:5583)
                                                                                                    	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5631)
                                                                                                    	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8653)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2023-06-17 02:11:40.055 29373-29373 AuthUI                  usap64                               E  A sign-in error occurred.
                                                                                                    com.firebase.ui.auth.FirebaseUiException: Code: 12500, message: 12500: 
                                                                                                    	at com.firebase.ui.auth.data.remote.GoogleSignInHandler.onActivityResult(GoogleSignInHandler.java:114)
                                                                                                    	at com.firebase.ui.auth.ui.idp.SingleSignInActivity.onActivityResult(SingleSignInActivity.java:144)
                                                                                                    	at android.app.Activity.dispatchActivityResult(Activity.java:8550)
                                                                                                    	at android.app.ActivityThread.deliverResults(ActivityThread.java:5583)
                                                                                                    	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5631)
                                                                                                    	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8653)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by thatfiredev** [comment]
Also, it would be helpful to us if you can tell us what version of Firebase Auth and Firebase UI you're using.

**Comment by drindt** [comment]
I have exactly the same problem. I use `firebase-bom:33.1.1` and `firebase-ui-auth:8.0.2`. I can absolutely rule out that this is a wrong setup, i.e. signing fingerprints.
I would be very grateful for any help. The code has been running smoothly so far. I cannot understand in which version construct the error occurs.

Thanks,
Daniel

**Comment by demolaf** [comment]
Hello,

Thank you for taking the time to submit this bug.

A new release is planned shortly, which should resolve this request. 

In the meantime, we will close this issue, if this is not resolved in the new version - please feel free to create a new issue for this bug.
