### ISSUE TITLE
Only Telenor network operator Number is getting error 39 on requesting otp  

### ISSUE THREAD

**Issue by mohsiniqbalcui** [firebase/FirebaseUI-Android#2141]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

Only Telenor network operator Number is giving error 39 in pakistan all other network are working fine and receving otp. 
![IMG-20231006-WA0037](https://github.com/firebase/FirebaseUI-Android/assets/41267719/f9a693eb-79e6-493b-b121-fec9f12e3ce0)

  * Android device:  Emulator and Physical
  * Android OS version:  5.0 and above
  * Google Play Services version: 23.37.17
  * Firebase/Play Services SDK version: 20.4.0
  * FirebaseUI version: 21.1.0
  
#### Steps to reproduce:

  1. Download this app https://play.google.com/store/apps/details?id=com.app.bikjaa
  2. In Welcom screen press button "login with phone"
  3. Enter any Telenor number staring from (034..........) with selecting pakistan as country code +92
  4. [0340 7795694] [0343 7340100] [0347 1447099] [0342 4215519] with selecting pakistan as country code +92
  5.  error code 39 come 
  6. Run the app in both emulator or physical device
 
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  In mobile error 39 comes 
  
  [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17499 Error code:39
AuthUI                   E  A sign-in error occurred.
                            com.google.firebase.FirebaseException: An internal error has occurred. [ Error code:39 ]
                            	at com.google.android.gms.internal.firebase-auth-api.zzxc.zza(com.google.firebase:firebase-auth@@21.1.0:6)
                            	at com.google.android.gms.internal.firebase-auth-api.zzxw.zza(com.google.firebase:firebase-auth@@21.1.0:1)
                            	at com.google.android.gms.internal.firebase-auth-api.zzxx.run(com.google.firebase:firebase-auth@@21.1.0:3)
                            	at android.os.Handler.handleCallback(Handler.java:938)
                            	at android.os.Handler.dispatchMessage(Handler.java:99)
                            	at android.os.Looper.loopOnce(Looper.java:233)
                            	at android.os.Looper.loop(Looper.java:334)
                            	at android.app.ActivityThread.main(ActivityThread.java:8399)
                            	at java.lang.reflect.Method.invoke(Native Method)
                            	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
                            	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
#### Expected Results:

  otp should be sent to user 
  
#### Relevant Code:
// code here to reproduce the problem

    /**
     * Funtions for login using Mobile OTP
     */
    //
    private fun verifyMobileNumber() {
        // Choose authentication providers
        val providers = mutableListOf(
                PhoneBuilder().setDefaultCountryIso("PK").build()
        )
        // Create and launch sign-in intent
        startActivityForResult(
                AuthUI.getInstance()
                        .createSignInIntentBuilder()
                        .setAvailableProviders(providers)
                        .setTosAndPrivacyPolicyUrls("https://bikjaa.pk/pages/terms-of-use",
                                "https://bikjaa.pk/pages/privacy-policy")
                        .setAlwaysShowSignInMethodScreen(true)
                        .setTheme(R.style.OTPTheme)
                        .build(),
                APP_REQUEST_CODE
        )
    }

my build.gradle file is 
    implementation 'com.google.android.gms:play-services-location:17.0.0'
    implementation 'com.google.android.gms:play-services-maps:17.0.0'
    implementation 'com.google.android.gms:play-services-wallet:19.1.0'
    implementation 'com.google.android.libraries.places:places:3.0.0'
    implementation 'com.google.android.gms:play-services-auth:20.4.0'
    implementation 'com.google.firebase:firebase-messaging:23.1.1'
    implementation 'com.google.firebase:firebase-core:21.1.1'
    implementation ('com.google.firebase:firebase-auth:21.1.0') {
        exclude module: "play-services-safetynet"
    }
            implementation 'com.firebaseui:firebase-ui-auth:7.0.0'

**Comment by thatfiredev** [comment]
Hey @mohsiniqbalcui 

Code 39 indicates that you have tried too many times, as explained here. Can you please wait a few minutes for it to cool down and try again?

If the problem persists or if you think this is only related to that network operator, please contact [Firebase support](https://firebase.google.com/support), as that issue doesn't seem to be related to FirebaseUI-Android directly. You can reference this github issue when you fill the support form to help them understand the problem.

**Comment by ba138** [comment]
"I have encountered this issue multiple times, and despite several attempts, it has not been resolved. Interestingly, the application functions properly when using a different network, such as Zong, but the problem persists when using the Telenor network

**Comment by thatfiredev** [comment]
@ba138 Please [contact Firebase support](https://firebase.google.com/support) they should be able to address the issue.

**Comment by codenaveed** [comment]
Hi Dears, have you found the solution for this issue? I am facing same issue with ONLY Telenor numbers.

**Comment by MufakirMairaj** [comment]
I am facing the issue from last 6 months both Ufone and Telenor phone numbers.

**Comment by Ashad-sadiq** [comment]
Is there a solution for this? Our application is stuck in **production** and there is no way for our users to login!
Ive tried loging from different operators:
OTP is not being received on: Ufone, Telenor.
OTP is being received on: Jazz, Zong, Warid.
as of 21st Feb 2024

Who should i contact to get this issue resolved ASAP?

**Comment by Waleed065** [comment]
> I am facing the issue from last 6 months both Ufone and Telenor phone numbers.

Same, Facing issue for both telenor and ufone numbers in Pakistan

**Comment by Waleed065** [comment]
> Is there a solution for this? Our application is stuck in **production** and there is no way for our users to login! Ive tried loging from different operators: OTP is not being received on: Ufone, Telenor. OTP is being received on: Jazz, Zong, Warid. as of 21st Feb 2024
> 
> Who should i contact to get this issue resolved ASAP?

Contact firebase support from the firebase account that has the issue
<img width="1050" alt="Screenshot 2024-02-29 at 11 06 34 PM" src="https://github.com/firebase/FirebaseUI-Android/assets/65929645/14da6e11-0220-41f3-b5a5-871e0061a60d">

**Comment by SheikhSaad** [comment]
Do we have any further update on this, I've been facing this issue and right now I've changed the OTP verification method.

**Comment by stMerlHin** [comment]
I am facing the same probleme from Togo carriers are MOOV and TOGOCEL.

**Comment by Musanakh** [comment]
I'm encountering the same issue on the Ufone and Telenor networks. @MufakirMairaj and @mohsiniqbalcui have you managed to find a solution by any chance?

> > > Is there a solution for this? Our application is stuck in **production** and there is no way for our users to login! Ive tried loging from different operators: OTP is not being received on: Ufone, Telenor. OTP is being received on: Jazz, Zong, Warid. as of 21st Feb 2024
> > > Who should i contact to get this issue resolved ASAP?
> > 
> > 
> > Contact firebase support from the firebase account that has the issue <img alt="Screenshot 2024-02-29 at 11 06 34 PM" width="1050" src="https://private-user-images.githubusercontent.com/65929645/309028357-14da6e11-0220-41f3-b5a5-871e0061a60d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMDg2NDgsIm5iZiI6MTcwOTMwODM0OCwicGF0aCI6Ii82NTkyOTY0NS8zMDkwMjgzNTctMTRkYTZlMTEtMDIyMC00MWYzLWI1YTUtODcxZTAwNjFhNjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDE1NTIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzY2JjNzExZjFjNWY0MzJjNDI3ZGU1MzM1N2NhYjIxMDBkNGViNmEzYzYyNGQ0ODQ4NTE2ZDI4ZWNjYjE1OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AYsGSyNXwRkKV7pClqXu5pysbXFtJggR-0ktCuLRH4I">
> 
> I had a long conversation with firebase team they asked me logs, carrier, time and phone numbers. I shared the recorded video as well. There answer was. Here it is "Thank you for the information. I have discussed the matter with our engineering team, and they have confirmed that Telenor carrier is currently unavailable for SMS due to service reliability issues. I understand that this is an important feature for your application, however we are unable to unblock this from our side. "

**Comment by MufakirMairajAlam** [comment]
No I did not find the solution, Therefore I replaced the authentication flow.

**Comment by Musanakh** [comment]
> No I did not find the solution, Therefore I replaced the authentication flow.

Can you please guide, which platform are you using for phone number authentication?

**Comment by MufakirMairajAlam** [comment]
You can use email authentication or use Twilio.

**Comment by TayyabKashif10** [comment]
@Musanakh hello there, same issue, did you manage to find a workaround? Also I've noticed that the OTPs are sent fine to Telenor numbers as of now. But they are not getting sent to Ufone numbers.
