### ISSUE TITLE
Support play-services-auth library (v21.0.0)

### ISSUE THREAD

**Issue by wangerekaharun** [firebase/FirebaseUI-Android#2158]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: Pixel 6 Pro
  * Android OS version: Android 14
  * Google Play Services version: 21.1.0
  * Firebase/Play Services SDK version: 21.1.1
  * FirebaseUI version: 8.0.2
  
#### Steps to reproduce:

  1. Update the play-services-auth version on an app using Firebase UI
  2. Run the app, it crashes due to the breaking changes added on the play-services-auth 21.1.0 version: https://developers.google.com/android/guides/releases#february_15_2024
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
Crashes with this exception:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/credentials/CredentialsOptions$Builder;at com.firebase.ui.auth.util.GoogleApiUtils.getCredentialsClient(GoogleApiUtils.java:29) 

at com.firebase.ui.auth.viewmodel.AuthViewModelBase.onCreate(AuthViewModelBase.java:30)
at com.firebase.ui.auth.viewmodel.ViewModelBase.init(ViewModelBase.java:24)
at com.firebase.ui.auth.KickoffActivity.onCreate(KickoffActivity.java:38)
at android.app.Activity.performCreate(Activity.java:8051)
at android.app.Activity.performCreate(Activity.java:8031)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7839)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.auth.api.credentials.CredentialsOptions$Builder" on path: DexPathList[[dex file "/data/data/com.mfhc.firebasetest/code_cache/.overlay/base.apk/classes3.dex", zip file "/data/app/~~crZRGUM9m8NR4vzMFc5fFw==/com.mfhc.firebasetest-oesX28d7C_VTSFzoRDt6Gg==/base.apk"],nativeLibraryDirectories=[/data/app/~~crZRGUM9m8NR4vzMFc5fFw==/com.mfhc.firebasetest-oesX28d7C_VTSFzoRDt6Gg==/lib/x86_64, /system/lib64, /system_ext/lib64]]

dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

```  
#### Expected Results:

  * What did you expect to happen?

Firebae UI Auth Should continue to work as expected with the new play-services-auth version
  
#### Relevant Code:

  ```
Update to latest play-services-auth version
  ```

**Comment by tlozovyi** [comment]
I have exactly same problem

**Comment by jonsmirl** [comment]
Same problem.

**Comment by Pantsoffski** [comment]
Any news? I have exactly same problem...

**Comment by corvinav** [comment]
+1

**Comment by jnstahl** [comment]
+1

**Comment by jonsmirl** [comment]
Ha, ha. I asked Gemini for alternatives to firebaseUI-auth and it told me to use AWS Amplify.

**Comment by tlozovyi** [comment]
In the end, I've rewritten app auth flow from the scratch without Firebase UI

**Comment by vtdeleond** [comment]
Almost one year with this critical issue. How long could this take guys?

**Comment by thatfiredev** [comment]
Hi all,
Sorry for the long delay on this one! We finally released [version 9.0.0](https://github.com/firebase/FirebaseUI-Android/blob/master/docs/upgrade-to-9.0.md) of the FirebaseUI library which fixes this issue. :)

I will close this issue for now, but please leave a comment or re-open if you're still facing this.
