### ISSUE TITLE
Handle case where credentials stored in SmartLock do not correspond to an existing user

### ISSUE THREAD

**Issue by animeshjain** [firebase/FirebaseUI-Android#234]
Steps to reproduce:

1. Login using email, password mechanism. 
2. Use SmartLock to remember the login credentials.
3. Delete the user using the "Delete account" button
4. go back to the auth screen and try to login / signup again.
5. Get stuck at this blank screen

![screenshot_20160803-124040](https://cloud.githubusercontent.com/assets/73044/17357094/a6eac378-5978-11e6-8875-f1dac913788d.png)

![screenshot_20160803-124044](https://cloud.githubusercontent.com/assets/73044/17357093/a6dff1c8-5978-11e6-8651-a2a2e7e8e91e.png)

In logcat, I can see an error as follows

    08-03 12:34:35.870 15352-15352/com.firebase.uidemo W/ChooseAccountActivity: Unsuccessful sign in with email and password
                                                                            com.google.firebase.auth.FirebaseAuthInvalidUserException: There is no user record corresponding to this identifier. The user may have been deleted.
                                                                                at com.google.android.gms.internal.zzafg.zzes(Unknown Source)
                                                                                at com.google.android.gms.internal.zzafd$zzg.zza(Unknown Source)
                                                                                at com.google.android.gms.internal.zzafo.zzet(Unknown Source)
                                                                                at com.google.android.gms.internal.zzafo$zza.onFailure(Unknown Source)
                                                                                at com.google.android.gms.internal.zzafj$zza.onTransact(Unknown Source)
                                                                                at android.os.Binder.execTransact(Binder.java:453)

There seems to be no way to get out of this scenario even by clearing the app cache etc.

**Comment by animeshjain** [comment]
The only way to get out of this limbo seems to be to go to your Google account and delete the password saved by SmartLock

**Comment by samtstern** [comment]
@animeshjain thanks for this report.  Which 'delete account' button are you clicking in step 3 in your original report?

**Comment by animeshjain** [comment]
Basically in the sample app, the screen after a successful login has a delete account button. I think the SmartLock implementation might need a little tweaking. If the account it expects to find is already deleted, then the error is probably not being handled correctly.

Here is the screenshot.

![screenshot_20160803-224343-2-480x483](https://cloud.githubusercontent.com/assets/73044/17374907/66360aaa-59cc-11e6-8e24-534455829340.png)

**Comment by mobiletoly** [comment]
Took me some time to figure out how to delete stuck password on KitKat. You have to go to "passwords.google.com" from your mobile or desktop browser and delete saved password for your app.

**Comment by samtstern** [comment]
Fix implemented in #259

**Comment by samtstern** [comment]
This fix for this issue is included in version 0.5.0.
