### ISSUE TITLE
NPE using 0.5.0 release

### ISSUE THREAD

**Issue by peterhav** [firebase/FirebaseUI-Android#265]
I'm encountering a NPE after switching to use the new 0.5.0 release in my build.gradle:

java.lang.RuntimeException: Unable to start activity ComponentInfo{xxx.xxxxx.xxxxx/com.firebase.ui.auth.ui.ChooseAccountActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(android.content.Context)' on a null object reference
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
                      at android.app.ActivityThread.access$800(ActivityThread.java:144)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5221)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(android.content.Context)' on a null object reference
                      at com.firebase.ui.auth.util.PlayServicesHelper.isPlayServicesAvailable(PlayServicesHelper.java:40)
                      at com.firebase.ui.auth.util.PlayServicesHelper.makePlayServicesAvailable(PlayServicesHelper.java:78)
                      at com.firebase.ui.auth.ui.ChooseAccountActivity.onCreate(ChooseAccountActivity.java:75)
                      at android.app.Activity.performCreate(Activity.java:5937)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360) 
                      at android.app.ActivityThread.access$800(ActivityThread.java:144) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:135) 
                      at android.app.ActivityThread.main(ActivityThread.java:5221) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694) 

When switching back to 0.4.4 the login intent works fine again.

**Comment by samtstern** [comment]
D'oh I botched this release.  0.5.1 incoming, thanks!

**Comment by samtstern** [comment]
@peterhav can you try 0.5.1? This should be fixed, thanks for catching this so fast!

**Comment by peterhav** [comment]
@samtstern, the 0.5.1 works fine!

**Comment by samtstern** [comment]
@peterhav phew!  Thanks for confirming, I'm sad I sullied the pristine `0.5.0` versioning with a NullPointerException :-/
