### ISSUE TITLE
Crash on email + pw log in (after email screen) #auth

### ISSUE THREAD

**Issue by Kiailandi** [firebase/FirebaseUI-Android#267]
### Step 2: Describe your environment

  * Android device: Asus Zenfone 2 ZE551ML
  * Android OS version: 5.0
  * Google Play Services version: 3.0.0
  * Firebase/Play Services SDK version: 9.4.0 
  * FirebaseUI version: 0.5.1 (same on 0.4.x with relative Firebase sdk)
  
### Step 3: Describe the problem:

While trying to login with email + pw (already signed up) there is a crash after clicking the "next" button on the email "panel". Looking at the error it looks like there is a problem trying to display the password "panel" / field. 

#### Steps to reproduce:

  1. Sign up with email + pw
  2. Try to login (Smart Lock is disabled)
  3. Insert email adress and press "next"
  
#### Observed Results:

Crash of the app.

java.lang.RuntimeException:
Unable to start activity ComponentInfo{com.trekken/com.firebase.ui.auth.ui.email.SignInActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setAlpha(float)' on a null object reference
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2326)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:147)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5264)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
                                                                 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setAlpha(float)' on a null object reference
                                                                    at com.firebase.ui.auth.ui.email.ImageFocusTransparencyChanger.<init>(ImageFocusTransparencyChanger.java:32)
                                                                    at com.firebase.ui.auth.ui.email.SignInActivity.onCreate(SignInActivity.java:74)
                                                                    at android.app.Activity.performCreate(Activity.java:5975)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:147) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:135) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5264) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695) 
08-25 20:23:59.390 21515-21515/com.trekken D/FirebaseCrashApiImpl: throwable java.lang.RuntimeException: Unable to start activity ComponentInfo{com.trekken/com.firebase.ui.auth.ui.email.SignInActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setAlpha(float)' on a null object reference

08-25 20:23:59.412 21515-21515/com.trekken E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.trekken, PID: 21515
                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.trekken/com.firebase.ui.auth.ui.email.SignInActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setAlpha(float)' on a null object reference
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2326)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:147)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5264)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
                                                              Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setAlpha(float)' on a null object reference
                                                                 at com.firebase.ui.auth.ui.email.ImageFocusTransparencyChanger.<init>(ImageFocusTransparencyChanger.java:32)
                                                                 at com.firebase.ui.auth.ui.email.SignInActivity.onCreate(SignInActivity.java:74)
                                                                 at android.app.Activity.performCreate(Activity.java:5975)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:147) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:135) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5264) 
                                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:900) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695) `
  
#### Expected Results:

 See the password field (I suppose)
  
#### Relevant Code:

```
@OnClick(R.id.sign_in)
    public void signIn(View view) {
        startActivityForResult(
                AuthUI.getInstance().createSignInIntentBuilder()
                        /*DEBUG*/
                        .setIsSmartLockEnabled(false)
                        .setTheme(AuthUI.getDefaultTheme())
                        .setProviders(getSelectedProviders())
                        .build(),
                RC_SIGN_IN);
    }

```

Code is almost the same as the demo app, if needed I can provide more.

**Comment by samtstern** [comment]
@Kiailandi does this happen on your device if you use the provided demo app?  If not, can you show how your code differs?  Looks like we're expecting an `ImageView` and getting `null`.

**Comment by Kiailandi** [comment]
I think I found the problem as the "bug" seems fixed. I named "SignInActivity" the "equivalent" of the "AuthUIActivity" from the demo app. The layout was named "sign_in_layout" and it seems that having a homonymous Activity / layout inside Firebase UI library produced a conflict.

**Comment by samtstern** [comment]
@Kiailandi ah yes an overlapping layout resource would definitely cause this problem.  Glad you got it fixed!
