### ISSUE TITLE
Uncaught exception resulting in crash when network is off

### ISSUE THREAD

**Issue by johnsunilmac** [firebase/FirebaseUI-Android#273]
Uncaught exception resulting in crash when network is off

08-28 19:05:29.632 18490-19317/E/StorageUtil: error getting token java.util.concurrent.ExecutionException: com.google.firebase.FirebaseException: An internal error has occured. [ <<Network Error>> ]
08-28 19:05:30.673 18490-19317/ W/ExponenentialBackoff: network unavailable, sleeping.

08-30 18:56:51.186 7626-7810/E/UncaughtException: java.lang.NullPointerException: null reference
                                                                                 at axk.a(:com.google.android.gms.DynamiteModulesC:27)
                                                                                 at bzr.d(:com.google.android.gms.DynamiteModulesC:261)
                                                                                 at bzl.onTransact(:com.google.android.gms.DynamiteModulesC:76)
                                                                                 at android.os.Binder.transact(Binder.java:380)
                                                                                 at com.google.android.gms.internal.zzamj$zza$zza.zzcyu(Unknown Source)
                                                                                 at com.google.android.gms.internal.zzamm.zzcyu(Unknown Source)
                                                                                 at com.google.firebase.storage.FileDownloadTask.run(Unknown Source)
                                                                                 at com.google.firebase.storage.StorageTask$5.run(Unknown Source)
                                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                 at java.lang.Thread.run(Thread.java:818)
08-30 18:56:51.391 7626-7810/ D/FirebaseCrashApiImpl: throwable java.lang.NullPointerException: null reference
08-30 18:56:51.399 7626-7810/ I/Process: Sending signal. PID: 7626 SIG: 9
08-30 18:56:51.402 17258-17258/:background_crash I/FirebaseCrashReceiverServiceImpl: FirebaseCrashReceiverServiceImpl created by ClassLoader com.google.android.chimera.container.internal.DelegateLastPathClassLoader[DexPathList[[zip file "/data/data/com.google.android.gms/app_chimera/m/00000008/DynamiteModulesC_GmsCore_prodlmp_xhdpi_release.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]]
08-30 18:56:51.402 17258-17258/:background_crash D/FirebaseCrashReceiverServiceImpl: onCreate
08-30 18:56:51.403 17258-17334/:background_crash D/FirebaseCrashReceiverServiceImpl: Saving crash
08-30 18:56:52.275 17258-17316/:background_crash D/FirebaseCrashSenderServiceImpl: Sending crash report id=1
08-30 18:56:52.278 17258-17316/:background_crash E/FirebaseCrashSenderServiceImpl: Error sending crash report: IOException while sending a crash report

These are the Firebase build.gradle compile commands:  
compile 'com.google.firebase:firebase-core:9.2.1'
    compile 'com.google.firebase:firebase-storage:9.2.1'
    compile 'com.google.firebase:firebase-auth:9.2.1'

**Comment by samtstern** [comment]
@johnsunilmac this stack trace references Firebase Crash.  Are you sure you're not including Firebase Crash Reporting in your app somehow>

**Comment by johnsunilmac** [comment]
Included Firebase Crash 'com.google.firebase:firebase-crash:9.4.0'.  The exception does not occur now.  The exception used to occur after a long period of network inactivity. Will wait and watch.  Thanks.

**Comment by sscdvp** [comment]
It still persists during network outage:

 compile 'com.google.firebase:firebase-crash:10.0.1'

E/FirebaseCrash: Error sending crash report: IOException while sending a crash report

**Comment by malhobayyeb** [comment]
> It still persists during network outage:
> 
> compile 'com.google.firebase:firebase-crash:10.0.1'
> 
> E/FirebaseCrash: Error sending crash report: IOException while sending a crash report

**Comment by NooAn** [comment]
I have the same error. This happened when I try open my app without internet, but only instance application is not working now.  I have  implementation 'com.google.firebase:firebase-crash:11.8.0' 
01-31 14:14:35.788 20753-20806/bytheway I/Firestore: (0.6.6-dev) [zzeur]: (2f7eb03) Stream closed with status: zzfof{code=UNAVAILABLE, description=null, cause=java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
                                                                      at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:141)
                                                                      at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
                                                                      at java.net.InetAddress.getAllByName(InetAddress.java:787)
                                                                      at io.grpc.internal.zzbq$zzb.zzuk(Unknown Source:2)
                                                                      at io.grpc.internal.zzbr.run(Unknown Source:118)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                      at java.lang.Thread.run(Thread.java:764)
                                                                   Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
                                                                      at libcore.io.Linux.android_getaddrinfo(Native Method)
                                                                      at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:58)
                                                                      at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:122)
                                                                      at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90) 
                                                                      at java.net.InetAddress.getAllByName(InetAddress.java:787) 
                                                                      at io.grpc.internal.zzbq$zzb.zzuk(Unknown Source:2) 
                                                                      at io.grpc.internal.zzbr.run(Unknown Source:118) 
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                      at java.lang.Thread.run(Thread.java:764) 
                                                                  }.
