### ISSUE TITLE
Crash on WelcomeBackPasswordPrompt when password empty.

### ISSUE THREAD

**Issue by kustra** [firebase/FirebaseUI-Android#295]
#### Environment:
- Android device: Samsung SM-T580
- Android OS version: 6.0.1
- Google Play Services version: 9.4.0
- Firebase/Play Services SDK version: 9.4.0
- FirebaseUI version: 0.5.1
#### Steps to reproduce:
1. Authenticate a user with Google or e-mail/password.
2. Log out, then authenticate the user with Facebook as well. Facebook should provide the same e-mail address as Google, so that FirebaseUI will attempt to merge the accounts.
3. A screen will appear ("Welcome back"), asking for the existing password for the account. Leave the password field empty and hit the submit button.
#### Observed Results:

Crash, with the following stack trace:

<pre> 13:34:33.631 8923-8923/my.app.id E/AndroidRuntime: FATAL EXCEPTION: main
 Process: my.app.id, PID: 8923
 java.lang.IllegalArgumentException: Given String is empty or null
     at com.google.android.gms.common.internal.zzab.zzhr(Unknown Source)
     at com.google.firebase.auth.FirebaseAuth.signInWithEmailAndPassword(Unknown Source)
     at com.firebase.ui.auth.ui.account_link.WelcomeBackPasswordPrompt.next(WelcomeBackPasswordPrompt.java:111)
     at com.firebase.ui.auth.ui.account_link.WelcomeBackPasswordPrompt.onClick(WelcomeBackPasswordPrompt.java:90)
     at android.view.View.performClick(View.java:5714)
     at android.widget.TextView.performClick(TextView.java:10926)
     at android.view.View$PerformClick.run(View.java:22589)
     at android.os.Handler.handleCallback(Handler.java:739)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:148)
     at android.app.ActivityThread.main(ActivityThread.java:7303)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)</pre>
  
#### Expected Results:

:)

**Comment by samtstern** [comment]
@kustra thanks for the report. This seems like a pretty obvious bug with a hopefully straightforward fix (just guarding empty input from the UI).

I'll take this bug, but if you're motivated to submit a PR to fix it that's always welcome.

**Comment by samtstern** [comment]
Fix implemented by #308, will be in the 1.0 release
