### ISSUE TITLE
Twitter provider with same email issue

### ISSUE THREAD

**Issue by aviadmini** [firebase/FirebaseUI-Android#466]
* Android device: SGS6
  * Android OS version: API 23
  * Firebase/Play Services SDK version: 10.0.1
  * FirebaseUI version: 1.0.1

#### Steps to reproduce:

  1. Create an account with provider A (e.g. Google)
  2. Try to create account with Twitter provider **with same email**
  3. Crash
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.

`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.aviadmini.socnet, PID: 2258
                                                                    java.lang.IllegalArgumentException: Given String is empty or null
                                                                        at com.google.android.gms.common.internal.zzac.zzdv(Unknown Source)
                                                                        at com.google.firebase.auth.FirebaseAuth.fetchProvidersForEmail(Unknown Source)
                                                                        at com.firebase.ui.auth.ui.idp.CredentialSignInHandler.onComplete(CredentialSignInHandler.java:74)
                                                                        at com.google.android.gms.tasks.zzc$1.run(Unknown Source)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:158)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

Request user emails permission is turned on in Twitter settings
  
#### Expected Results:

  * Expected to see the UI telling you have already used this email with Google

**Comment by SUPERCILEX** [comment]
@aviadmini Thanks for the bug report, this was fixed in #452 and will be available in FirebaseUI `v1.1.0` coming soon!

**Comment by samtstern** [comment]
A fix for this issue has been released in version `1.1.0`
