### ISSUE TITLE
java.lang.VerifyError

### ISSUE THREAD

**Issue by troy21688** [firebase/FirebaseUI-Android#49]
I am receiving this error and have no idea why:

    java.lang.VerifyError: com/firebase/ui/auth/core/FirebaseLoginDialog
                                                     at com.firebase.ui.auth.core.FirebaseLoginBaseActivity.onStart(FirebaseLoginBaseActivity.java:112)
                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1177)
                                                     at android.app.Activity.performStart(Activity.java:5551)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2420)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2507)
                                                     at android.app.ActivityThread.access$900(ActivityThread.java:172)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:146)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5692)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by troy21688** [comment]
Here is my code. Note that I removed the call to onStart since that was generating a NullPointException, as mentioned in an additional issue:

    package com.troychuinard.fanpolls;

import android.os.Bundle;
import android.support.design.widget.FloatingActionButton;
import android.support.design.widget.Snackbar;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.view.View;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.Button;

import com.firebase.client.AuthData;
import com.firebase.client.Firebase;
import com.firebase.ui.auth.core.FirebaseLoginBaseActivity;
import com.firebase.ui.auth.core.FirebaseLoginError;
import com.firebase.ui.auth.core.SocialProvider;

public class MainActivity extends FirebaseLoginBaseActivity {

    Button mLoginButton;
    Firebase mFirebaseRef;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Firebase.setAndroidContext(this);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        mFirebaseRef = new Firebase("https://fan-polls.firebaseio.com");

        mLoginButton = (Button) findViewById(R.id.login_button);

        mLoginButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                showFirebaseLoginPrompt();

            }
        });


    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }


    @Override
    protected void onFirebaseLoggedIn(AuthData authData) {

    }

    @Override
    protected void onFirebaseLoggedOut() {

    }

    @Override
    protected void onFirebaseLoginProviderError(FirebaseLoginError firebaseLoginError) {

    }

    @Override
    protected void onFirebaseLoginUserError(FirebaseLoginError firebaseLoginError) {

    }

    @Override
    protected Firebase getFirebaseRef() {
        return null;
    }
}

**Comment by abehaskins** [comment]
Closing this since this was discussed in #50
