### ISSUE TITLE
NullPointerException on onStart

### ISSUE THREAD

**Issue by troy21688** [firebase/FirebaseUI-Android#50]
I am getting a NullPointerException when I call to super.onStart   

     public class MainActivity extends FirebaseLoginBaseActivity {

    Firebase mFirebaseRef;
    Button mButton;
    CallbackManager mFacebookCallbackManager;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Firebase.setAndroidContext(this);
        setContentView(R.layout.activity_main);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        mFacebookCallbackManager = CallbackManager.Factory.create();
        mFirebaseRef = new Firebase("https://fan-polls.firebaseio.com/");
        mButton = (Button) findViewById(R.id.test_button);
        mButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                showFirebaseLoginPrompt();

            }
        });
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        mFacebookCallbackManager.onActivityResult(requestCode, resultCode, data);

    }

    @Override
    protected void onStart() {
        super.onStart();
        setEnabledAuthProvider(SocialProvider.facebook);
    }

    @Override
    protected void onFirebaseLoggedIn(AuthData authData) {

    }

STACKTRACE

    roidRuntime: FATAL EXCEPTION: main
                                                   Process: com.troychuinard.firebaseui, PID: 20031
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.troychuinard.firebaseui/com.troychuinard.firebaseui.MainActivity}: java.lang.RuntimeException: Binary XML file line #17: You must supply a layout_height attribute.
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2447)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2507)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:172)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:146)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5692)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: java.lang.RuntimeException: Binary XML file line #17: You must supply a layout_height attribute.
                                                       at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:492)
                                                       at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:6204)
                                                       at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6372)
                                                       at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:1837)
                                                       at android.support.design.widget.AppBarLayout$LayoutParams.<init>(AppBarLayout.java:554)
                                                       at android.support.design.widget.AppBarLayout.generateLayoutParams(AppBarLayout.java:284)
                                                       at android.support.design.widget.AppBarLayout.generateLayoutParams(AppBarLayout.java:97)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:768)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
                                                       at com.troychuinard.firebaseui.MainActivity.onCreate(MainActivity.java:32)
                                                       at android.app.Activity.performCreate(Activity.java:5541)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2411)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2507) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:172) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:146) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5692) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
    12-31 17:50:07.893 778-1276/? W/ActivityManager:   Force finishing activity               com.troychuinard.firebaseui/.MainActivity
12-31 17:50:07.903 778-20057/? W/DropBoxManagerService: Dropping: data_app_crash (2695 > 0 bytes)
12-31 17:50:07.913 1183-1183/? D/WfcActivityStateReceiver: onReceive(): packageName=com.troychuinard.firebaseui, activityState=pause
12-31 17:50:07.913 778-778/? D/CrashAnrDetector: NO DROPBOX ENTRY for :data_app_crash 1451605807918
12-31 17:50:07.913 778-921/? D/SensorService:  [AR] 1.0 -3.0 9.9
12-31 17:50:07.913 778-921/? D/SensorService: ScreenOrientationSensor::Rotation Old->New [0 -> 255]
12-31 17:50:07.923 20059-20059/? I/dumpstate: begin
12-31 17:50:07.933 2720-2720/? I/SQLiteSecureOpenHelper: getWritableDatabase(pwd)
12-31 17:50:07.933 2720-2720/? I/SQLiteSecureOpenHelper: getDatabaseLocked(b,b,pwd)...
12-31 17:50:07.953 240-240/? I/SurfaceFlinger: id=677 createSurf (1x1),1 flag=4, girebaseui
12-31 17:50:08.073 240-391/? I/SurfaceFlinger: id=672 Removed Mauncher (7/12)
12-31 17:50:08.073 240-1783/? I/SurfaceFlinger: id=672 Removed Mauncher (-2/12)
12-31 17:50:08.073 2720-2720/? I/SQLiteSecureOpenHelper: getWritableDatabase(pwd)
12-31 17:50:08.073 2720-2720/? I/SQLiteSecureOpenHelper: getDatabaseLocked(b,b,pwd)...

**Comment by puf** [comment]
If you're getting ` NullPointerException` in `onStart()` you've most likely not implemented `getFirebaseReference()` correctly.

From the [README](https://github.com/firebase/FirebaseUI-Android#inherit-from-firebaseloginbaseactivity): 

```
    @Override
    public Firebase getFirebaseRef() {
        // TODO: Return your Firebase ref
    }
```

So you'll have to return a valid `Firebase` reference in there. I.e.

```
    @Override
    public Firebase getFirebaseRef() {
        return mFirebaseRef;
    }
```

**Comment by troy21688** [comment]
Thanks Frank!  That seems to have eliminated the NullPointer.

However, when I now click the button to load the dialog, I do not see any
Login Credentials, it is simply a blank bar so to speak.  Please see the
attached screenshot:







[image: Inline image 2]


On Thu, Dec 31, 2015 at 6:20 PM, Frank van Puffelen <
notifications@github.com> wrote:

> If you're getting NullPointerException in onStart() you've most likely
> not implemented getFirebaseReference() correctly.
>
> From the README
> <https://github.com/firebase/FirebaseUI-Android#inherit-from-firebaseloginbaseactivity>:
>
>
>     @Override
>     public Firebase getFirebaseRef() {
>         // TODO: Return your Firebase ref
>     }
>
> So you'll have to return a valid Firebase reference in there. I.e.
>
>     @Override
>     public Firebase getFirebaseRef() {
>         return mFirebaseRef;
>     }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firebase/FirebaseUI-Android/issues/50#issuecomment-168266372>
> .
>



-- 
Troy Chuinard, CPA

**Comment by troy21688** [comment]
Frank -

Figured it out. I had to call the set enabled provider methods. This UI is
much easier than manually adding each provider.

I really appreciate the help on the holiday.  Have a Happy New Year!

-Troy

On Thu, Dec 31, 2015 at 6:38 PM, Troy Chuinard <tccpg288@gmail.com> wrote:

> Thanks Frank!  That seems to have eliminated the NullPointer.
>
> However, when I now click the button to load the dialog, I do not see any
> Login Credentials, it is simply a blank bar so to speak.  Please see the
> attached screenshot:
>
>
>
>
>
>
>
> [image: Inline image 2]
>
>
> On Thu, Dec 31, 2015 at 6:20 PM, Frank van Puffelen <
> notifications@github.com> wrote:
>
>> If you're getting NullPointerException in onStart() you've most likely
>> not implemented getFirebaseReference() correctly.
>>
>> From the README
>> <https://github.com/firebase/FirebaseUI-Android#inherit-from-firebaseloginbaseactivity>:
>>
>>
>>     @Override
>>     public Firebase getFirebaseRef() {
>>         // TODO: Return your Firebase ref
>>     }
>>
>> So you'll have to return a valid Firebase reference in there. I.e.
>>
>>     @Override
>>     public Firebase getFirebaseRef() {
>>         return mFirebaseRef;
>>     }
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/firebase/FirebaseUI-Android/issues/50#issuecomment-168266372>
>> .
>>
>
>
>
> --
> Troy Chuinard, CPA
>



-- 
Troy Chuinard, CPA

**Comment by troy21688** [comment]
Hi Frank -

On screen rotation, the login dialog resets to having 0 enabled providers,
as seen in the screenshot I originally included in this email chain.

My guess is it has something to do with savedInstanceState but I wanted to
report the bug to you and see if you knew of a resolution.

On Thu, Dec 31, 2015 at 6:46 PM, Troy Chuinard <tccpg288@gmail.com> wrote:

> Frank -
>
> Figured it out. I had to call the set enabled provider methods. This UI is
> much easier than manually adding each provider.
>
> I really appreciate the help on the holiday.  Have a Happy New Year!
>
> -Troy
>
> On Thu, Dec 31, 2015 at 6:38 PM, Troy Chuinard <tccpg288@gmail.com> wrote:
>
>> Thanks Frank!  That seems to have eliminated the NullPointer.
>>
>> However, when I now click the button to load the dialog, I do not see any
>> Login Credentials, it is simply a blank bar so to speak.  Please see the
>> attached screenshot:
>>
>>
>>
>>
>>
>>
>>
>> [image: Inline image 2]
>>
>>
>> On Thu, Dec 31, 2015 at 6:20 PM, Frank van Puffelen <
>> notifications@github.com> wrote:
>>
>>> If you're getting NullPointerException in onStart() you've most likely
>>> not implemented getFirebaseReference() correctly.
>>>
>>> From the README
>>> <https://github.com/firebase/FirebaseUI-Android#inherit-from-firebaseloginbaseactivity>:
>>>
>>>
>>>     @Override
>>>     public Firebase getFirebaseRef() {
>>>         // TODO: Return your Firebase ref
>>>     }
>>>
>>> So you'll have to return a valid Firebase reference in there. I.e.
>>>
>>>     @Override
>>>     public Firebase getFirebaseRef() {
>>>         return mFirebaseRef;
>>>     }
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/firebase/FirebaseUI-Android/issues/50#issuecomment-168266372>
>>> .
>>>
>>
>>
>>
>> --
>> Troy Chuinard, CPA
>>
>
>
>
> --
> Troy Chuinard, CPA
>



-- 
Troy Chuinard, CPA
