### ISSUE TITLE
Firebase UI incompatible with Floating action Button

### ISSUE THREAD

**Issue by calebgrimah** [firebase/FirebaseUI-Android#505]
### Step 2: Describe your environment

  * Android device: _genymotion emulator____
  * Android OS version: _6____
  * Google Play Services version: _10.0.0____
  * Firebase/Play Services SDK version: __10.0.1___
  * FirebaseUI version: __1.0.1__
  
### Step 3: Describe the problem:
Unable to run application, seems firebase ui is incompatible with FAB. because application runs without issues if i remove firebaseui dependency.

#### Steps to reproduce:

  1.Add FAB to main activity
 2.Add Design support library, firebase ui dependency
  
#### Observed Results:

01-10 06:23:09.564 5146-5146/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: neoncore.com.blogapplication, PID: 5146
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{neoncore.com.blogapplication/neoncore.com.blogapplication.MainActivity}: android.view.InflateException: Binary XML file line #60: Binary XML file line #60: Error inflating class android.support.design.widget.FloatingActionButton
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
  
  ```

**Comment by samtstern** [comment]
See #499, this is likely a conflict between the version of the support library you're using and the version used by FirebaseUI

**Comment by calebgrimah** [comment]
thanks for the reply..i just reduced the firebase ui version number and it solved the problem...
