### ISSUE TITLE
Failed resolution of: Lcom/google/android/gms/auth/api/Auth;

### ISSUE THREAD

**Issue by kj5d** [firebase/FirebaseUI-Android#52]
<b> logcat:</b>
01-05 23:59:21.909 9529-9529/pl.kj5d.firebase1 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: pl.kj5d.firebase1, PID: 9529
                                                                 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/Auth;
                                                                     at com.firebase.ui.auth.google.GoogleAuthProvider.<init>(GoogleAuthProvider.java:77)
                                                                     at com.firebase.ui.auth.core.FirebaseLoginDialog.setEnabledProvider(FirebaseLoginDialog.java:155)
                                                                     at com.firebase.ui.auth.core.FirebaseLoginBaseActivity.setEnabledAuthProvider(FirebaseLoginBaseActivity.java:77)
                                                                     at pl.kj5d.firebase1.MainActivity.onStart(01-05 23:59:21.909 9529-9529/pl.kj5d.firebase1 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: pl.kj5d.firebase1, PID: 9529
                                                                 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/Auth;
                                                                     at com.firebase.ui.auth.google.GoogleAuthProvider.<init>(GoogleAuthProvider.java:77)
                                                                     at com.firebase.ui.auth.core.FirebaseLoginDialog.setEnabledProvider(FirebaseLoginDialog.java:155)
                                                                     at com.firebase.ui.auth.core.FirebaseLoginBaseActivity.setEnabledAuthProvider(FirebaseLoginBaseActivity.java:77)
                                                                     at pl.kj5d.firebase1.MainActivity.onStart(MainActivity.java:120))

<b>Code:</b>

MainActivity.java:120 = setEnabledAuthProvider(SocialProvider.google);

<b>My dependencies looks like this:</b>

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.firebase:firebase-client-android:2.3.1'
    compile 'com.google.android.gms:play-services-appindexing:8.4.0'
    compile 'com.firebaseui:firebase-ui:0.3.0'
}

**Comment by abehaskins** [comment]
Hi!

Could you try adding Play Services as a dependency and seeing if you still experience this error?

```
compile 'com.google.android.gms:play-services-auth:8.3.0'
```

**Comment by Batzee** [comment]
Nope Adding 'compile 'com.google.android.gms:play-services-auth:8.3.0'" did not solve anything

**Comment by ganeshkannaandroid** [comment]
add in (Module:app)
dependencies{
..
compile 'com.google.android.gms:play-services-auth:8.3.0'
}

add in (Project:ProjectName)
 dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
        classpath 'com.google.gms:google-services:1.5.0'

       
    }

**Comment by Batzee** [comment]
Great @ganeshkannaandroid 's solution did work
Thanks

**Comment by Isabellle** [comment]
Same problem here, but the trick doesn't work for me
`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/firebase/ui/auth/google/GoogleAuthProvider`

**Comment by wangbourne** [comment]
@Isabellle, i got the same problem here. have you figured out?

**Comment by Shivendra30** [comment]
@ganeshkannaandroid 's solution also did not work for me 
I still get this error:

```
Java exception in 'Native Modules'

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/api/signin/GoogleSigninClient;

```
