### ISSUE TITLE
ConcurrentModificationException in native Firebase database api

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/FirebaseUI-Android#547]
I putting this issue here on top of sending it to the suggested email because if #544 gets merged, devs might do something similar to what I did and they should be able to find an easy way to fix it.

@puf You'll probably want to take a look at this.

### Steps to reproduce

1. Call `query.removeEventListener(hashMap.remove(this))`
2. In the object calling `removeEventListener`, override `hashCode` method with a call to `hashMap.hashCode()`.
3. A `ConcurrentModificationException` is thrown

Now I understand that this is kinda my fault, but my main point here is to help other devs that might have run into the same issue.

#### Walkthrough of code with crash

[Additions are made to hash map](https://github.com/firebase/FirebaseUI-Android/blob/32eab681d572dc9e29a407ca3deb3a9c3071e76b/database/src/main/java/com/firebase/ui/database/FirebaseIndexArray.java#L84) -> [`DataRefListener` includes a reference to its parent class thta overrides `hashCode`](https://github.com/firebase/FirebaseUI-Android/blob/32eab681d572dc9e29a407ca3deb3a9c3071e76b/database/src/main/java/com/firebase/ui/database/FirebaseIndexArray.java#L135) -> [remove is called](https://github.com/firebase/FirebaseUI-Android/blob/32eab681d572dc9e29a407ca3deb3a9c3071e76b/database/src/main/java/com/firebase/ui/database/FirebaseIndexArray.java#L53) -> [`hashCode` is called and a `ConcurrentModificationException` is thrown](https://github.com/firebase/FirebaseUI-Android/blob/32eab681d572dc9e29a407ca3deb3a9c3071e76b/database/src/main/java/com/firebase/ui/database/FirebaseIndexArray.java#L242).

Here's the code with a fix: https://github.com/SUPERCILEX/FirebaseUI-Android/commit/cdb2a380b52f9dd574b5a8a8ae7a673069e11a6d

### Explanation 

Inside the `removeEventListener` method you guys are storing the object passed into it in a wrapper class around the `ValueEventListener` which includes a `hashCode` method. At some point you guys must be calling that method thus causing the `ConcurrentModificationException` because of concurrent calls to `hashMap.remove()` and `hashMap.hashCode()`.

@puf I believe the issue is caused somewhere down the stack of whatever this unreadable garbage does:
`Query.java`
```java
this.zzbXR.zzs(new Runnable() {
            public void run() {
                Query.this.zzbXR.zze(var1);
            }
        });
```
It could also be in this mess, but I don't have the source code so I can't be of much help:
`zzbmt.java`
```java
private List<zzboa> zzb(final zzboe var1, final zzbme var2, final DatabaseError var3) {
        return (List)this.zzcdB.zzf(new Callable<List<zzboa>>() {
            public List<zzboa> zzLO() {
                zzbmj var1x = var1.zzVc();
                zzbms var2x = (zzbms)zzbmt.this.zzcdC.zzK(var1x);
                Object var3x = new ArrayList();
                if(var2x != null && (var1.isDefault() || var2x.zzc(var1))) {
                    zzbqd var4 = var2x.zza(var1, var2, var3);
                    if(var2x.isEmpty()) {
                        zzbmt.this.zzcdC = zzbmt.this.zzcdC.zzJ(var1x);
                    }

                    List var5 = (List)var4.getFirst();
                    var3x = (List)var4.zzZZ();
                    boolean var6 = false;

                    zzboe var8;
                    for(Iterator var7 = var5.iterator(); var7.hasNext(); var6 = var6 || var8.zzYD()) {
                        var8 = (zzboe)var7.next();
                        zzbmt.this.zzcdB.zzh(var1);
                    }

                    zzbns var15 = zzbmt.this.zzcdC;
                    boolean var16 = var15.getValue() != null && ((zzbms)var15.getValue()).zzXx();
                    Iterator var9 = var1x.iterator();

                    while(var9.hasNext()) {
                        zzbos var10 = (zzbos)var9.next();
                        var15 = var15.zze(var10);
                        var16 = var16 || var15.getValue() != null && ((zzbms)var15.getValue()).zzXx();
                        if(var16 || var15.isEmpty()) {
                            break;
                        }
                    }

                    if(var6 && !var16) {
                        zzbns var17 = zzbmt.this.zzcdC.zzI(var1x);
                        if(!var17.isEmpty()) {
                            List var18 = zzbmt.this.zza(var17);
                            Iterator var11 = var18.iterator();

                            while(var11.hasNext()) {
                                zzbof var12 = (zzbof)var11.next();
                                zzbmt.zzc var13 = zzbmt.this.new zzc(var12);
                                zzboe var14 = var12.zzYH();
                                zzbmt.this.zzcdH.zza(zzbmt.this.zzd(var14), var13.zzceb, var13, var13);
                            }
                        }
                    }

                    if(!var16 && !var5.isEmpty() && var3 == null) {
                        if(var6) {
                            zzbmt.this.zzcdH.zza(zzbmt.this.zzd(var1), (zzbmu)null);
                        } else {
                            var9 = var5.iterator();

                            while(var9.hasNext()) {
                                zzboe var19 = (zzboe)var9.next();
                                zzbmu var20 = zzbmt.this.zze(var19);

                                assert var20 != null;

                                zzbmt.this.zzcdH.zza(zzbmt.this.zzd(var19), var20);
                            }
                        }
                    }

                    zzbmt.this.zzX(var5);
                }

                return (List)var3x;
            }
        });
    }
```

### The crash

```
01-25 18:57:33.152 31258-31258/com.firebase.uidemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.firebase.uidemo, PID: 31258
                                                                     java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (3.0.0). Please report to firebase-database-client@google.com
                                                                         at com.google.android.gms.internal.zzbkx$1$1.run(Unknown Source)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                      Caused by: java.lang.RuntimeException: java.util.ConcurrentModificationException
                                                                         at com.google.android.gms.internal.zzbnm.zzf(Unknown Source)
                                                                         at com.google.android.gms.internal.zzbmt.zzb(Unknown Source)
                                                                         at com.google.android.gms.internal.zzbmt.zzh(Unknown Source)
                                                                         at com.google.android.gms.internal.zzbml.zze(Unknown Source)
                                                                         at com.google.firebase.database.Query$2.run(Unknown Source)
                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                         at java.lang.Thread.run(Thread.java:761)
                                                                      Caused by: java.util.ConcurrentModificationException
                                                                         at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
                                                                         at java.util.HashMap$EntryIterator.next(HashMap.java:891)
                                                                         at java.util.HashMap$EntryIterator.next(HashMap.java:890)
                                                                         at java.util.AbstractMap.hashCode(AbstractMap.java:494)
                                                                         at com.firebase.ui.database.FirebaseIndexArray.hashCode(FirebaseIndexArray.java:242)
                                                                         at com.google.android.gms.internal.zzblz.hashCode(Unknown Source)
                                                                         at sun.misc.Hashing.singleWordWangJenkinsHash(Hashing.java:48)
                                                                         at java.util.HashMap.getEntry(HashMap.java:393)
                                                                         at java.util.HashMap.get(HashMap.java:348)
                                                                         at com.google.android.gms.internal.zzbnc.zzj(Unknown Source)
                                                                         at com.google.android.gms.internal.zzbnc.zzd(Unknown Source)
                                                                         at com.google.android.gms.internal.zzbme.zzXa(Unknown Source)
                                                                         at com.google.android.gms.internal.zzbof.zza(Unknown Source)
                                                                         at com.google.android.gms.internal.zzbms.zza(Unknown Source)
                                                                         at com.google.android.gms.internal.zzbmt$4.zzLO(Unknown Source)
                                                                         at com.google.android.gms.internal.zzbmt$4.call(Unknown Source)
                                                                         at com.google.android.gms.internal.zzbnm.zzf(Unknown Source) 
                                                                         at com.google.android.gms.internal.zzbmt.zzb(Unknown Source) 
                                                                         at com.google.android.gms.internal.zzbmt.zzh(Unknown Source) 
                                                                         at com.google.android.gms.internal.zzbml.zze(Unknown Source) 
                                                                         at com.google.firebase.database.Query$2.run(Unknown Source) 
                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428) 
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272) 
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                         at java.lang.Thread.run(Thread.java:761)
```

**Comment by mikelehen** [comment]
Thanks for the detailed investigation.  It does look like there's potential race condition / concurrency bug since Database ends up calling the hashCode / equals implementations from our worker thread, and FirebaseArray might be modifying the underlying refs / snapshots that equals / hashCode are operating on.

Your fix may work, but I think as-is FirebaseArrayIndex.DataRefListener is probably not suitable for use in a HashMap since it's hash / equals are based on mutable data.  So it may be necessary to either:
1. Change equals / hashCode on FirebaseArrayIndex to be based on immutable data (the keyQuery / dataQuery) instead of mutable data (or just leave the default implementations and don't override them), but perhaps there's some reason we wanted equals() to be based on the contents of the array?  I don't know.
2. Override equals / hashCode on the inner class to use reference equality and System.identityHashCode() so they're unaffected by the equals / hashCode on the parent class.

I've also logged an internal bug against the database SDK to stop relying on the developer-supplied hashCode / equals implementations, since it could be buggy or (in this case) unable to deal with concurrent execution.

**Comment by SUPERCILEX** [comment]
@mikelehen This stuff makes my brain melt: both of us were wrong. While you are correct that the `hashCode` method is garbage (we should only be checking the actual contents of the list), the crash had nothing to do with `DataRefListener` which uses the default `hashCode` implementation.

### Updated explanation

1. `super.removeChangeEventListener(listener);` calls `mQuery.removeEventListener((ValueEventListener) this);`
2. We start calling `mRefs.remove(query)`
3. At some point, the original `mQuery.removeEventListener(this)` calls the `hashCode` method in `FirebaseIndexArray` thus causing the crash.

Anyway, I'm going to close this issue as the main point of making the fix and explanation available for future devs and getting the Firebase team involved was accomplished.

**Comment by mikelehen** [comment]
Ahh, whoops.  I thought DataRefListener was the only listener implementation and so I assumed that somehow its hashCode was relying on the hashCode of its containing class (FirebaseIndexArray) although I admit that seemed odd to me.  But I see that FirebaseIndexArray extends FirebaseArray which itself is a Value/ChildEventListener and so yeah, I think mQuery.removeEventListener() is ending up calling its hashCode implementation directly.

So yeah, I think my solution #2 is invalid, since it's not related to the inner class.

Again, thanks for bringing this up.
