### ISSUE TITLE
error report for Android Studio

### ISSUE THREAD

**Issue by ORESoftware** [firebase/FirebaseUI-Android#564]
I don't know what Google repo to put this error report in.

but here is an error I experienced in Android Studio for the Firebase / Anroid Support plugin, I clicked "Report to Google" but wanted to report it on Github as well.

```

java.lang.NullPointerException
	at com.android.tools.idea.assistant.view.TutorialStep.<init>(TutorialStep.java:60)
	at com.android.tools.idea.assistant.view.TutorialCard.<init>(TutorialCard.java:93)
	at com.android.tools.idea.assistant.view.FeaturesPanel.<init>(FeaturesPanel.java:70)
	at com.google.services.firebase.FirebaseServiceCreators.getPanel(FirebaseServiceCreators.java:59)
	at com.android.tools.idea.assistant.AssistSidePanel.<init>(AssistSidePanel.java:42)
	at com.android.tools.idea.assistant.AssistToolWindowFactory.createToolWindowContent(AssistToolWindowFactory.java:41)
	at com.android.tools.idea.assistant.OpenAssistSidePanelAction$1.run(OpenAssistSidePanelAction.java:79)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:345)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:329)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

Here's a screenshot:

![screenshot from 2017-01-31 14-52-50](https://cloud.githubusercontent.com/assets/11139560/22488082/06d08dce-e7c5-11e6-9e17-15ebc772e4a3.png)

**Comment by samtstern** [comment]
@ORESoftware this looks like an Android studio error, please follow the process here to file it:
http://tools.android.com/filing-bugs

**Comment by ORESoftware** [comment]
thank you! I had no idea where to put it
