### ISSUE TITLE
Facebook Twitter options disabled in AuthUI saple

### ISSUE THREAD

**Issue by lakamsani** [firebase/FirebaseUI-Android#585]
### Step 1: Summary
Facebook and Twitter options disabled.

### Step 2: Describe your environment

  * Android device: Pixel XL emulator with API 23
  * Android OS version: 6.0 
  * Google Play Services version: 38
  * Firebase/Play Services SDK version: 10.0.1
  * FirebaseUI version: 1.1.1
  
### Step 3: Describe the problem:
<img width="345" alt="screen shot 2017-02-11 at 3 37 45 pm" src="https://cloud.githubusercontent.com/assets/3322496/22858439/88377980-f072-11e6-81c3-bba9940f913a.png">

#### Steps to reproduce:

  1. build and  run the app cloned from this repo.
  2.  confirm google and email account setup/creation works fine.
  3. Facebook and Twitter options are disabled despite setting them up in Firebase console and downloading the google-service.json file and entering the FB/twitter app id and tokens in FirebaseUI-Android/auth/src/main/res/values/config.xml:
<img width="785" alt="screen shot 2017-02-11 at 1 49 39 pm" src="https://cloud.githubusercontent.com/assets/3322496/22858444/c393e518-f072-11e6-9b89-176541b9fb02.png">
4. This is a separate problem. When trying the storage demo to upload an image got this exception.

``
02-11 15:36:19.900 7463-7463/com.android.gallery D/gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
02-11 15:36:20.044 7668-7737/com.firebase.uidemo E/StorageException: StorageException has occurred.
                                                                     An unknown error occurred, please check the HTTP result code and inner exception for server response.
                                                                      Code: -13000 HttpResult: 400
02-11 15:36:20.044 7668-7737/com.firebase.uidemo E/StorageException: The server has terminated the upload session
                                                                     java.io.IOException: The server has terminated the upload session
                                                                         at com.google.firebase.storage.UploadTask.zzabc(Unknown Source)
                                                                         at com.google.firebase.storage.UploadTask.zzabb(Unknown Source)
                                                                         at com.google.firebase.storage.UploadTask.run(Unknown Source)
                                                                         at com.google.firebase.storage.StorageTask$8.run(Unknown Source)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                         at java.lang.Thread.run(Thread.java:818)
02-11 15:36:20.044 7668-7737/com.firebase.uidemo E/StorageException: StorageException has occurred.
                                                                     An unknown error occurred, please check the HTTP result code and inner exception for server response.
                                                                      Code: -13000 HttpResult: 400
02-11 15:36:20.044 7668-7737/com.firebase.uidemo E/StorageException: The server has terminated the upload session
                                                                     java.io.IOException: The server has terminated the upload session
                                                                         at com.google.firebase.storage.UploadTask.zzabc(Unknown Source)
                                                                         at com.google.firebase.storage.UploadTask.zzabb(Unknown Source)
                                                                         at com.google.firebase.storage.UploadTask.run(Unknown Source)
                                                                         at com.google.firebase.storage.StorageTask$8.run(Unknown Source)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                         at java.lang.Thread.run(Thread.java:818)
02-11 15:36:20.044 7668-7668/com.firebase.uidemo W/ImageDemo: uploadPhoto:onError
                                                              com.google.firebase.storage.StorageException: An unknown error occurred, please check the HTTP result code and inner exception for server response.
                                                                  at com.google.firebase.storage.UploadTask.zzabe(Unknown Source)
                                                                  at com.google.firebase.storage.UploadTask.zzaaK(Unknown Source)
                                                                  at com.google.firebase.storage.StorageTask.zzaaS(Unknown Source)
                                                                  at com.google.firebase.storage.zze.zzaaZ(Unknown Source)
                                                                  at com.google.firebase.storage.StorageTask.zzf(Unknown Source)
                                                                  at com.google.firebase.storage.UploadTask.zzabc(Unknown Source)
                                                                  at com.google.firebase.storage.UploadTask.zzabb(Unknown Source)
                                                                  at com.google.firebase.storage.UploadTask.run(Unknown Source)
                                                                  at com.google.firebase.storage.StorageTask$8.run(Unknown Source)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                  at java.lang.Thread.run(Thread.java:818)
                                                               Caused by: java.io.IOException: The server has terminated the upload session
                                                                  at com.google.firebase.storage.UploadTask.zzabc(Unknown Source) 
                                                                  at com.google.firebase.storage.UploadTask.zzabb(Unknown Source) 
                                                                  at com.google.firebase.storage.UploadTask.run(Unknown Source) 
                                                                  at com.google.firebase.storage.StorageTask$8.run(Unknown Source) 
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                  at java.lang.Thread.run(Thread.java:818) 
02-11 15:36:21.588 7668-7727/com.firebase.uidemo E/Surface: getSlotFromBufferLocked: unknown buffer: 0x99e912a0
02-11 15:36:21.632 1253-2117/? D/gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
02-11 15:36:21.640 7668-7727/com.firebase.uidemo E/EGL_emulation: tid 7727: eglSurfaceAttrib(1165): error 0x3009 (EGL_BAD_MATCH)
02-11 15:36:21.640 7668-7727/com.firebase.uidemo W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xaa2b8a80, error=EGL_BAD_MATCH
``

  
#### Observed Results:

For comparison I also tried the auth app from [quickstart demo](https://github.com/firebase/quickstart-android) and FB/Twitter works fine there. That app is called **com.google.firebase.quickstart.auth** in the Firebase console screenshot shown below. 
<img width="333" alt="screen shot 2017-02-11 at 3 58 09 pm" src="https://cloud.githubusercontent.com/assets/3322496/22858454/ef5973a2-f072-11e6-9b47-16502b9b7dff.png">

In the Firebase UI demo project  I tried putting the same file  in  app/google-services.json as well as in auth/google-services.json. That file  contains JSON config both the apps i.e. **com.firebase.uidemo** and **com.firebase.ui.auth**  plus the **com.google.firebase.quickstart.auth** all belong to the same project in the Firebase console where the authentication was configured for FB and Twitter. 

 
  
#### Expected Results:

Firebase UI app should enable FB/Twitter options like the Quickstart demo as the config is similar.

**Comment by lakamsani** [comment]
Fixed by adding  FB app id and twitter key/secret to app/src/main/res/values/config.xml. auth is a library so it does not need its own auth/google-services.json or app id in firebase console. deleted those two. New to firebase and learning ...

**Comment by samtstern** [comment]
@lakamsani glad you figured it out, thanks for the thorough report!
