### ISSUE TITLE
Firebase auth ui error when signing in on Android OS 4.2.2 - Invalid id_token in IdP response

### ISSUE THREAD

**Issue by ivy-hill** [firebase/FirebaseUI-Android#602]
* Android device: Samsung GT-P3113
  * Android OS version: 4.2.2
  * Google Play Services version: 10.0.1
  * Firebase/Play Services SDK version: 10.0.1
  * FirebaseUI version: 1.1.1
   minSdkVersion 16
   targetSdkVersion 25

#### The Problem:

Sign-in with Google provider is failing with the error below.  

W/IDPSignInContainer: Failure authenticating with credential
                                                                             com.google.firebase.FirebaseException: An internal error has occurred. [ Invalid id_token in IdP response ]
                                                                                 at com.google.android.gms.internal.zzbix.zzcb(Unknown Source)
                                                                                 at com.google.android.gms.internal.zzbiu$zzj.zza(Unknown Source)
                                                                                 at com.google.android.gms.internal.zzbjf.zzcc(Unknown Source)
                                                                                 at com.google.android.gms.internal.zzbjf$zza.onFailure(Unknown Source)
                                                                                 at com.google.android.gms.internal.zzbja$zza.onTransact(Unknown Source)
                                                                                 at android.os.Binder.execTransact(Binder.java:351)
                                                                                 at dalvik.system.NativeStart.run(Native Method)

#### Steps to reproduce:

  1. Sign in with google provider.  It works the first time.
  2. Wait a while...
  3. Sign-out then sign in again.  The error above occurs.
  
The same code is working fine on Android OS v6.x.  This error is not happening.

**Comment by samtstern** [comment]
@ivy-hill are you using the same account on each device?

**Comment by ivy-hill** [comment]
Yes, I was using the same google account on both.

**Comment by samtstern** [comment]
@ivy-hill the Google Sign In team is looking into this issue, it seems to happen in some cases and the error messaging is not good.  I can confirm that this is not a problem with FirebaseUI and that there will soon be better error messaging from the GSI server.
