### ISSUE TITLE
Firebase RecyclerView crash when closing an activity started by intent with 2 Fragments in FragmentStatePagerAdapter

### ISSUE THREAD

**Issue by lumleon** [firebase/FirebaseUI-Android#648]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: _____ Android Emulator Nexus 5 API 25, Samsung I9505, Samsung P-605
  * Android OS version: __4.41, 5.01, 7.1___
  * Google Play Services version: _____ 10.2.1
  * Firebase/Play Services SDK version: _____10.2.1
  * FirebaseUI version: ____1.2.0
  
#### Steps to reproduce:

  1. create 2 fragments in FragmentStatePagerAdapter
  2. create FirebaseRecyclerAdapter in the 2 fragments and add clicklistener for the entire item
  3.  scroll to the end of the list view and click 
  4. start another activity by intent with the post key to show the child post details
  5.  click back and it will crash as the following log

  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  03-25 22:48:54.560 8547-8583/com.anrex.raceblogger V/FA: Recording user engagement, ms: 4194
03-25 22:48:54.561 8547-8583/com.anrex.raceblogger V/FA: Activity paused, time: 2423311
03-25 22:48:54.574 8547-8583/com.anrex.raceblogger D/FA: Logging event (FE): _e, Bundle[{_o=auto, _et=4194, _sc=DailyRaceTipsActivity, _si=7506535637291765120}]
03-25 22:48:54.579 8547-8547/com.anrex.raceblogger D/AutoManageHelper: onStart true {0=com.google.android.gms.internal.zzaaa$zza@c5ff290}
03-25 22:48:54.584 8547-8547/com.anrex.raceblogger D/InappBilling: Creating IAB helper.
03-25 22:48:54.584 8547-8547/com.anrex.raceblogger D/InappBilling: Starting setup.
03-25 22:48:54.584 8547-8547/com.anrex.raceblogger D/IabHelper: Starting in-app billing setup.
03-25 22:48:54.588 8547-8547/com.anrex.raceblogger D/InappBilling: Setup finished.
03-25 22:48:54.588 8547-8547/com.anrex.raceblogger E/InappBilling: **** InApp Error: Problem setting up in-app billing: IabResult: Billing service unavailable on device. (response: 3:Billing Unavailable)
03-25 22:48:54.588 8547-8547/com.anrex.raceblogger D/InappBilling: Showing alert dialog: Error: Problem setting up in-app billing: IabResult: Billing service unavailable on device. (response: 3:Billing Unavailable)
03-25 22:48:54.645 8547-8558/com.anrex.raceblogger I/art: Background sticky concurrent mark sweep GC freed 1125(125KB) AllocSpace objects, 8(3MB) LOS objects, 12% free, 23MB/26MB, paused 8.175ms total 70.496ms
03-25 22:48:54.658 8547-8583/com.anrex.raceblogger V/FA: Activity resumed, time: 2423383
03-25 22:48:54.691 8547-8547/com.anrex.raceblogger D/AndroidRuntime: Shutting down VM
03-25 22:48:54.691 8547-8547/com.anrex.raceblogger E/UncaughtException: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 4(offset:4).state:5
                                                                            at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5504)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                            at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                            at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                            at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3534)
                                                                            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3310)
                                                                            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                            at android.view.View.layout(View.java:17637)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                            at android.view.View.layout(View.java:17637)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                            at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
                                                                            at android.view.View.layout(View.java:17637)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                            at android.view.View.layout(View.java:17637)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                            at android.view.View.layout(View.java:17637)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                            at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                            at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                            at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1391)
                                                                            at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
                                                                            at android.view.View.layout(View.java:17637)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                            at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                                            at android.view.View.layout(View.java:17637)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                            at android.view.View.layout(View.java:17637)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                            at android.view.View.layout(View.java:17637)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                            at android.view.View.layout(View.java:17637)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                            at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                            at android.view.View.layout(View.java:17637)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                            at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                            at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
                                                                            at android.view.View.layout(View.java:17637)
                                                                            at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
03-25 22:48:54.691 8547-8547/com.anrex.raceblogger E/UncaughtException:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
03-25 22:48:54.698 8547-8583/com.anrex.raceblogger D/FA: Logging event (FE): _ae, Bundle[{_o=crash, _sc=MainActivity, _si=7506535637291765119, timestamp=1490435334692, fatal=1}]
03-25 22:48:54.923 8547-8547/com.anrex.raceblogger E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.anrex.raceblogger, PID: 8547
                                                                     java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 4(offset:4).state:5
                                                                         at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5504)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                         at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                         at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                         at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                         at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3534)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3310)
                                                                         at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                         at android.view.View.layout(View.java:17637)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                         at android.view.View.layout(View.java:17637)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
                                                                         at android.view.View.layout(View.java:17637)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
                                                                         at android.view.View.layout(View.java:17637)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at android.view.View.layout(View.java:17637)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                         at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                         at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1391)
                                                                         at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
                                                                         at android.view.View.layout(View.java:17637)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                                         at android.view.View.layout(View.java:17637)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at android.view.View.layout(View.java:17637)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                         at android.view.View.layout(View.java:17637)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at android.view.View.layout(View.java:17637)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                         at android.view.View.layout(View.java:17637)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                                                                         at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
                                                                         at android.view.View.layout(View.java:17637)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-25 22:48:54.923 8547-8547/com.anrex.raceblogger E/AndroidRuntime:     at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
#### Expected Results:

  * What did you expect to happen? should not be crashed when closing the activity
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  
    public void init(){

        /** TODO: Insert all the code from the HomeActivity’s onCreate() method after the setContentView method call */


        // Create the adapter that will return a fragment for each of the two
        // primary sections of the activity.
        mSectionsPagerAdapter = new FragmentStatePagerAdapter(getFragmentManager()) {


            private final Fragment[] mFragments = new Fragment[] {
                    new DailyTipsActivePostsFragment(),
                 //   new DailyRealTipsPostsFragment(),
                 //   new BankerOldPostsFragment(),
                    //  new MyTopPostsFragment(),
            };
            private final String[] mFragmentNames = new String[] {

                    getString(R.string.heading_daily_active),
                //    getString(R.string.heading_daily_real),

            };



            @Override
            public Fragment getItem(int position) {

                return mFragments[position];

            }

            @Override
            public int getCount() {

                return mFragments.length;

            }


            @Override
            public CharSequence getPageTitle(int position) {
                return mFragmentNames[position];
            }


        };

        // Set up the ViewPager with the sections adapter.
        mViewPager = (ViewPager) rootView.findViewById(R.id.container);
        mViewPager.setAdapter(mSectionsPagerAdapter);
        TabLayout tabLayout = (TabLayout) rootView.findViewById(R.id.tabs);
        tabLayout.setupWithViewPager(mViewPager);


        // Button launches BankerPostNewActivity for userrole = admin
        if( getUserRole().equals("admin")){

            rootView.findViewById(R.id.fab_new_post).setVisibility(View.VISIBLE);
            rootView.findViewById(R.id.fab_new_post).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startActivity(new Intent(getActivity(), DailyNewActivity.class));
            }
        });

        }
    }


// code for recycler adapter
 public void setupAdapter(){

        // Set up FirebaseRecyclerAdapter with the Query
        Query postsQuery = getQuery(mDatabaseReference);

        mAdapter = new FirebaseRecyclerAdapter<RaceSchedulePost, RaceSchedulePostListViewHolder>(
                RaceSchedulePost.class,
                R.layout.item_dailytipspost,
                RaceSchedulePostListViewHolder.class,
                postsQuery  ) {

            @Override
            protected void populateViewHolder(final RaceSchedulePostListViewHolder viewHolder, final RaceSchedulePost model, int position) {

                final DatabaseReference postRef = getRef(position);


                //Method for setter Feb 8, 2017
                viewHolder.setRacedate(model.getRacedate());
                viewHolder.setLocation(model.getLocation());
                viewHolder.setTurf(model.getTurf());
                viewHolder.setAwt(model.getAwt());
                viewHolder.setTitle(model.getTitle());

                viewHolder.setTipsresult(model.getTipsresult());

                viewHolder.setStatus(model.getStatus());

                // Set click listener for the whole post view
                final String postKey = postRef.getKey();

             //set onclick listener for entire post
         viewHolder.mView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                //set the postkey to field
                mPostKey = postKey;

                mStatusKey =model.getStatus();

                //Toast.makeText(getActivity(), mPostKey, Toast.LENGTH_SHORT).show();

                //set click counter
                DatabaseReference globalPostRef = mDatabaseReference.child(CHILD_DAILYPOST).child(mPostKey);
                onPostClicked(globalPostRef);

                //if today or active post, check balance and charge rate and then ask deduct balance to view post


                // Launch PostDetailActivity
                    Intent intent = new Intent(getActivity(), DailyRaceTipsActivity.class);
                    intent.putExtra(DailyRaceTipsActivity.EXTRA_POST_KEY, mPostKey);
                    intent.putExtra(DailyRaceTipsActivity.EXTRA_STATUS_KEY, mStatusKey);

                startActivity(intent);

            }
         });

   mAdapter.notifyDataSetChanged();


        mRecycler.setAdapter(mAdapter);

        mAdapter.registerAdapterDataObserver(new RecyclerView.AdapterDataObserver() {
            @Override
            public void onItemRangeInserted(int positionStart, int itemCount) {
                super.onItemRangeInserted(positionStart, itemCount);
                int pollCount = mAdapter.getItemCount();
                int lastVisiblePosition = mManager.findLastCompletelyVisibleItemPosition();

                // If the recycler view is initially being loaded or the user is at the bottom of the list, scroll
                // to the bottom of the list to show the newly added message.
                if (lastVisiblePosition == -1 ||
                        (positionStart >= (pollCount - 1) && lastVisiblePosition == (positionStart - 1))) {
                    mRecycler.scrollToPosition(positionStart);
                }
            }
        });



    }

[reproduce.zip](https://github.com/firebase/FirebaseUI-Android/files/869913/reproduce.zip)

**Comment by stevedj** [comment]
Hi, I also got this problem

I create a viewpager with fragments inside it, in active fragment, there is a recycler view, I opened a new activity and do some stuff in there, and click back, I got several errors,

I would like to help if there is anything that I can do

Best Regards
Steve

**Comment by stevedj** [comment]
Hi all,

for additional info, I have tried to cleanup when it is on destroy/stop but,
it still giving me that error

Is there anyone who encounter the same problem?

Best regards
Steve

**Comment by SUPERCILEX** [comment]
@stevedj @lumleon The error you're getting isn't because of FirebaseUI, it's an issue with how you're using the `RecyclerView`:
> `java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 4(offset:4).state:5`

I've had this issue before and here was my solution: https://issuetracker.google.com/issues/37135118#comment9

Make sure not to do anything funky with `ViewHolder`s and you should be good. Hope this helps! 😄

**Comment by SUPERCILEX** [comment]
@samtstern I believe this issue can be closed due to inactivity.
