### ISSUE TITLE
error validating access token for Facebook after removing app and more

### ISSUE THREAD

**Issue by erikswed** [firebase/FirebaseUI-Android#684]
### Step 2: Describe your environment

  * Android device: _____ Galaxy note 4
  * Android OS version: _____6.01
  * Google Play Services version: _____10,2,98
  * Firebase/Play Services SDK version: _____10,2,0
  * FirebaseUI version: ____v1.2.0
  
### Step 3: Describe the problem:

When I go to my Facebook and remove the app permission and then in FirebaseUI again sign in with the same Facebook. I´m presented with this "error validating access token. The user has not autorized..."., there is also an "Okey" button that freezes when pressed. After this I never get´s a chance to sign in with another Facebook account. It´s like a loop . Uninstalling FirebaseUI and selecting Facebook sign in again  then ask me if I want to sign in using that Facebook account again(that Facebook I removed the app for). Now there is no option to sign in with another Facebook account only the "continue" button. I would expect that I could choose another Facebook account to sign in with but no.

Maybe i entered the credential wrong :
```
    <!--
    Facebook Application ID, prefixed by 'fb'.  Enables Chrome Custom tabs.
    -->
    <string name="facebook_login_protocol_scheme" ranslatable="false">fb3458726730446530</string>


```
When I then press "continue" to again sign in using that Facebook account I get this error:

```
com.firebase.uidemo D/ViewRootImpl: #3 mView = null
com.firebase.uidemo E/FacebookProvider: JSON Exception reading from Facebook GraphRequest
	   org.json.JSONException: No value for email
		   at org.json.JSONObject.get(JSONObject.java:389)
		   at org.json.JSONObject.getString(JSONObject.java:550)
		   at com.firebase.ui.auth.provider.FacebookProvider$1.onCompleted(FacebookProvider.java:146)
		   at com.facebook.GraphRequest$1.onCompleted(GraphRequest.java:304)
		   at com.facebook.GraphRequest$5.run(GraphRequest.java:1383)
		   at android.os.Handler.handleCallback(Handler.java:739)
		   at android.os.Handler.dispatchMessage(Handler.java:95)
		   at android.os.Looper.loop(Looper.java:158)
		   at android.app.ActivityThread.main(ActivityThread.java:7225)
		   at java.lang.reflect.Method.invoke(Native Method)
		   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
		   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

And now I see the App again at: 
https://www.facebook.com/settings/?tab=applications
This is the outer loop..

**Comment by samtstern** [comment]
@erikswed thanks for the report here.  As I understand it, FirebaseUI does not properly handle what we call an "out of band deauthorization", which is basically when the user removes Facebook access permissions via some other interface.

**Comment by samtstern** [comment]
This is a very old issue and I believe it has been addressed by other fixes (namely what happens if we can't get the facebook email).  Closing it, but if anyone experiences this they should re-open it.
