### ISSUE TITLE
NullPointerException - Sign In With Email - Firebase-UI-Auth 1.2.0

### ISSUE THREAD

**Issue by victoraldir** [firebase/FirebaseUI-Android#733]
Hello,

Just came across with this problem and cannot overcome. I am getting a NullPointer when Signing In With Email, however the problem just happens in release mode and using proguard.

Please, find below the stack. Also opened a thread in here 
[https://stackoverflow.com/questions/44295185/nullpointerexception-sign-in-with-email-firebase-ui-auth-1-2-0?noredirect=1#comment75598983_44295185](url)

`java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
                                                   at com.firebase.ui.auth.util.signincontainer.SaveSmartLock.saveCredentialsOrFinish(Unknown Source)
                                                   at com.firebase.ui.auth.ui.BaseHelper.saveCredentialsOrFinish(Unknown Source)
                                                   at com.firebase.ui.auth.ui.email.RegisterEmailFragment$4$1.onComplete(Unknown Source)
                                                   at com.google.android.gms.c.l$1.run(Unknown Source)
                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                   at android.os.Looper.loop(Looper.java:154)
                                                   at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)`

**Comment by SUPERCILEX** [comment]
See [my response](https://stackoverflow.com/a/44296600/4548500), this is fixed in `v2.0` which will be available soon.

**Comment by victoraldir** [comment]
Can't wait @SUPERCILEX . Thanks for getting back so quickly! Closing the issue.

**Comment by clamentsanz** [comment]
I have the same bug now

**Comment by samtstern** [comment]
@clamentsanz please file a new issue if you're seeing this in a recent version
