### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by Soumya7391** [firebase/FirebaseUI-Android#764]
06-19 12:47:40.379 4986-4986/com.firebase.uidemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.firebase.uidemo, PID: 4986
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.firebase.uidemo/com.firebase.uidemo.auth.AuthUiActivity}: java.lang.IllegalStateException: **Default FirebaseApp is not initialized in this process com.firebase.uidemo. Make sure to call FirebaseApp.initializeApp(Context) first**.
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2572)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654)
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                       at android.os.Looper.loop(Looper.java:207)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5728)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                                                                    Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.firebase.uidemo. Make sure to call FirebaseApp.initializeApp(Context) first.

Why Am I not able to run the application? Getting the error as shown above.

**Comment by TheCraftKid** [comment]
Like with any Firebase app, you have to add a google-services.json file associated with a Firebase project. Here's the relevant link in the [documentation](https://github.com/firebase/FirebaseUI-Android#sample-app).

**Comment by Soumya7391** [comment]
@TheCraftKid Have added it. Then too Am getting the same error.

**Comment by samtstern** [comment]
@Soumya7391 are you running the sample app without any modifications?

**Comment by Soumya7391** [comment]
@samtstern Yeah.. Din't do any modification. As said in the documentation, I created a firebase proj and integrated.. tats all...

**Comment by OlegTarashkevich** [comment]
@Soumya7391 
The same problem, phone auth doesn't work. I've already added google-services.json
FATAL EXCEPTION: main
                                                                      ```
Process: com.lucky.notewidget, PID: 30623
                                                                      java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.lucky.notewidget. Make sure to call FirebaseApp.initializeApp(Context) first.
                                                                          at com.google.firebase.FirebaseApp.getInstance(Unknown Source)
                                                                          at com.firebase.ui.auth.AuthUI.getInstance(AuthUI.java:138)
```

**Comment by samtstern** [comment]
@Soumya7391 are you still experiencing this issue?  I'm sorry I forgot to respond.  If so, can you try installing the app from the command line with `./gradlew clean :app:installDebug` rather than from Android Studio?

**Comment by SUPERCILEX** [comment]
@samtstern this issue can probably be closed now since we haven't received a response.
