### ISSUE TITLE
Attempt to read from field 'int com.firebase.ui.auth.ui.FlowParameters.themeId' on a null object reference

### ISSUE THREAD

**Issue by Violet-Bora-Lee** [firebase/FirebaseUI-Android#765]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 2: Describe your environment

  * Android device: Samsung SM-G906K / Android SDK built for x86(Emulator-Nexus_5X)
  * Android OS version: 6.0.1 / 7.1.1
  * Google Play Services version: 9.6.1
  * Firebase/Play Services SDK version: 9.6.1
  * FirebaseUI version: 0.6.0
  
### Step 3: Describe the problem:
App crashed(Unfortunately, xxx has stopped)  right after successful build.

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

E/UncaughtException: java.lang.RuntimeException: Unable to start activity ComponentInfo{XXXXX/com.firebase.ui.auth.ui.email.SignInActivity}: java.lang.NullPointerException: Attempt to read from field 'int com.firebase.ui.auth.ui.FlowParameters.themeId' on a null object reference
                                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3255)
                                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3351)
                                                                                               at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                               at android.os.Looper.loop(Looper.java:158)
                                                                                               at android.app.ActivityThread.main(ActivityThread.java:7230)
                                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                                            Caused by: java.lang.NullPointerException: Attempt to read from field 'int com.firebase.ui.auth.ui.FlowParameters.themeId' on a null object reference
                                                                                               at com.firebase.ui.auth.ui.ActivityHelper.configureTheme(ActivityHelper.java:43)
                                                                                               at com.firebase.ui.auth.ui.AppCompatBase.onCreate(AppCompatBase.java:27)
                                                                                               at com.firebase.ui.auth.ui.email.SignInActivity.onCreate(SignInActivity.java:57)
                                                                                               at android.app.Activity.performCreate(Activity.java:6877)
                                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
                                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3208)
                                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3351) 
                                                                                               at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796) 
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                               at android.os.Looper.loop(Looper.java:158) 
                                                                                               at android.app.ActivityThread.main(ActivityThread.java:7230) 
                                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 

FATAL EXCEPTION: main                                                                                       
                                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{XXXX/com.firebase.ui.auth.ui.email.SignInActivity}: java.lang.NullPointerException: Attempt to read from field 'int com.firebase.ui.auth.ui.FlowParameters.themeId' on a null object reference
                                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3255)
                                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3351)
                                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                            at android.os.Looper.loop(Looper.java:158)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:7230)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                                         Caused by: java.lang.NullPointerException: Attempt to read from field 'int com.firebase.ui.auth.ui.FlowParameters.themeId' on a null object reference
                                                                                            at com.firebase.ui.auth.ui.ActivityHelper.configureTheme(ActivityHelper.java:43)
                                                                                            at com.firebase.ui.auth.ui.AppCompatBase.onCreate(AppCompatBase.java:27)
                                                                                            at com.firebase.ui.auth.ui.email.SignInActivity.onCreate(SignInActivity.java:57)
                                                                                            at android.app.Activity.performCreate(Activity.java:6877)
                                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
                                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3208)
                                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3351) 
                                                                                            at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796) 
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                            at android.os.Looper.loop(Looper.java:158) 
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:7230) 
                                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 

#### Expected Results:

  * to start app without crashing
  
#### Relevant Code:

  ```
        mAuthStateListener = new FirebaseAuth.AuthStateListener() {
            @Override
            public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) {
                FirebaseUser user = firebaseAuth.getCurrentUser();
                if (user != null){  //user is signed in
                    onSignedInInitialize(user.getDisplayName());
                }else { //user is signed out
                    onSignedOutCleanup();
                    startActivityForResult(
                            AuthUI.getInstance()
                                    .createSignInIntentBuilder()
                                    .setIsSmartLockEnabled(!BuildConfig.DEBUG)
                                    .setProviders(
                                            AuthUI.EMAIL_PROVIDER,
                                            AuthUI.GOOGLE_PROVIDER
                                    )
                                    .setTheme(R.style.MySignInTheme)
                                    .setLogo(R.drawable.image_view_logo_image)
                                    .build(),
                            RC_SIGN_IN);
                }

            }
        };
  ```

```
    <style name="MySignInTheme" parent="FirebaseUI">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorPrimaryDark</item>
        <item name="colorControlNormal">@color/colorPrimary</item>
        <item name="colorControlActivated">@color/colorAccent</item>
        <item name="colorControlHighlight">@color/colorAccent</item>
        <item name="windowActionBar">false</item>
        <item name="windowNoTitle">true</item>
        <item name="android:windowFullscreen">true</item>
        <item name="android:windowBackground">@android:color/white</item>
    </style>
```

**Comment by Violet-Bora-Lee** [comment]
I've solve the problem right after I changed FirebaseUI Version to 1.2.0, Firebase/Play Services Version 10.2.0. Thx.
