### ISSUE TITLE
NPE using AUTH

### ISSUE THREAD

**Issue by adityagundecha** [firebase/FirebaseUI-Android#85]
02-24 13:03:31.359 7834-7834/com.example.a2p1wk1.canteenapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.example.a2p1wk1.canteenapp, PID: 7834
                                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.a2p1wk1.canteenapp/com.example.a2p1wk1.canteenapp.ActivityMain}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.firebase.client.Firebase$AuthStateListener com.firebase.client.Firebase.addAuthStateListener(com.firebase.client.Firebase$AuthStateListener)' on a null object reference
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                               Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.firebase.client.Firebase$AuthStateListener com.firebase.client.Firebase.addAuthStateListener(com.firebase.client.Firebase$AuthStateListener)' on a null object reference
                                                                                  at com.firebase.ui.auth.core.FirebaseLoginBaseActivity.onStart(FirebaseLoginBaseActivity.java:151)
                                                                                  at com.example.a2p1wk1.canteenapp.ActivityMain.onStart(ActivityMain.java:25)
                                                                                  at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
                                                                                  at android.app.Activity.performStart(Activity.java:6253)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:148) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by adityagundecha** [comment]
package com.example.a2p1wk1.canteenapp;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

import com.firebase.client.AuthData;
import com.firebase.client.Firebase;
import com.firebase.ui.auth.core.AuthProviderType;
import com.firebase.ui.auth.core.FirebaseLoginBaseActivity;
import com.firebase.ui.auth.core.FirebaseLoginError;

public class ActivityMain extends FirebaseLoginBaseActivity {

    private Firebase fireBaseRef;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        fireBaseRef = new Firebase("https://luminous-inferno-6831.firebaseio.com/");
    }

    @Override
    protected void onStart() {
        super.onStart();
        // All providers are optional! Remove any you don't want.
//        setEnabledAuthProvider(AuthProviderType.GOOGLE);
        setEnabledAuthProvider(AuthProviderType.PASSWORD);
        showFirebaseLoginPrompt();

    }

    @Override
    protected Firebase getFirebaseRef() {
        return null;
    }

    @Override
    protected void onFirebaseLoginProviderError(FirebaseLoginError firebaseLoginError) {

    }

    @Override
    protected void onFirebaseLoginUserError(FirebaseLoginError firebaseLoginError) {

    }

    @Override
    public void onFirebaseLoggedIn(AuthData authData) {
        // TODO: Handle successful login
    }

    @Override
    public void onFirebaseLoggedOut() {
        // TODO: Handle logout
    }

}

**Comment by puf** [comment]
If you implement this method to return a Firebase reference, the error will
go away:

protected Firebase getFirebaseRef() {
    return null;
}
