### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.google.android.gms flg=0x4000010 (has extras) } in com.google.android.gms.b.qf@bd2a49b

### ISSUE THREAD

**Issue by MIkeeJY** [firebase/FirebaseUI-Android#863]
```
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.google.android.gms flg=0x4000010 (has extras) } in com.google.android.gms.b.qf@bd2a49b
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1058)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5431)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
Caused by java.lang.IllegalStateException: Task is already complete
       at com.google.android.gms.common.internal.zzbo.zzu(Unknown Source)
       at com.google.android.gms.tasks.zzn.zzDH(Unknown Source)
       at com.google.android.gms.tasks.zzn.isComplete(Unknown Source)
       at com.google.android.gms.tasks.TaskCompletionSource.setResult(Unknown Source)
       at com.google.android.gms.internal.zzbeb.zzps(Unknown Source)
       at com.google.android.gms.internal.zzbba.zzpx(Unknown Source)
       at com.google.android.gms.internal.zzbbd.zzpA(Unknown Source)
       at com.google.android.gms.internal.zzbdk.onReceive(Unknown Source)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1038)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5431)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
```

**Comment by samtstern** [comment]
@MIkeeJY please follow the issue template, this is not enough information to debug.  We need:

- A description of your device and environment
- Steps to reproduce
- Code that casues this issue
- A stack trace or logs that indicates a connection to FirebaseUI

Closing for lack of information, if you can provide the information needed please try again.

**Comment by MIkeeJY** [comment]
@samtstern  Hi man,I edit it again,these are all informations from fabric...

**Comment by samtstern** [comment]
@MIkeeJY I don't see anything related to FirebaseUI in those stack traces.  Can you explain why you think it's related to this library?

**Comment by MIkeeJY** [comment]
@samtstern May not relate to FirebaseUI but  Firebase...
