### ISSUE TITLE
FirebaseIndexArray :java.lang.IndexOutOfBoundsException when key data is changed

### ISSUE THREAD

**Issue by nivarp** [firebase/FirebaseUI-Android#870]
### Step 2: Describe your environment

  * Android device: All
  * Android OS version: All
  * Firebase/Play Services SDK version: 11.0.4
  * FirebaseUI version: 2.2.0
  
### Step 3: Describe the problem:
Using FirebaseIndexRecyclerAdapter in the code with key ref and data ref nodes. This issue typically comes when the key ref is changed.

Some points which can be of help:
a. KeyRef is changed using a server side operation and performs set instead of update on the node. This means there can be changes in size and will include addition, deletion and movement of key nodes.
b. DataRef keeps on getting updated irrespective of the above operation and some times we do observe duplicate entries as well, not sure if they are related though.

Let me know if more information is needed.

Crash Log:
java.lang.IndexOutOfBoundsException: Index: 11, Size: 9
                                         at java.util.ArrayList.add(ArrayList.java:457)
                                         at com.firebase.ui.database.FirebaseIndexArray.onKeyMoved(FirebaseIndexArray.java:179)
                                         at com.firebase.ui.database.FirebaseIndexArray.onChildChanged(FirebaseIndexArray.java:113)
                                         at com.firebase.ui.database.ObservableSnapshotArray.notifyChangeEventListeners(ObservableSnapshotArray.java:122)
                                         at com.firebase.ui.database.FirebaseArray.onChildMoved(FirebaseArray.java:116)
                                         at com.google.android.gms.internal.px.zza(Unknown Source)
                                         at com.google.android.gms.internal.vj.zzHX(Unknown Source)
                                         at com.google.android.gms.internal.vp.run(Unknown Source)
                                         at android.os.Handler.handleCallback(Handler.java:751)
                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                         at android.os.Looper.loop(Looper.java:154)
                                         at android.app.ActivityThread.main(ActivityThread.java:6121)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by SUPERCILEX** [comment]
@nivarp Yeah, all of those annoying bugs stem from the assumption that your data snapshots can't contain null values—I think we probably should have forced the developer to handle null `DataSnapshot#getValue()`s, but oh well, it's too late now.

I've submitted #871, but I doubt that will get merged anytime soon because if full of hacks and general grossness. On top of that, it decreases move and remove performance by a full O(n) which kinda sucks. 😢😆

BTW: on your side, you can fix this issue by trying to remove the keys _first_ and _then_ the data. By removing the key first, we can easily record that as a deletion and properly clean up the array. Otherwise, you get those weird states where the data list is smaller than the key list and things just go downhill from there.

**Comment by SUPERCILEX** [comment]
Ooooooh, you actually gave me ideas on how to improve performance for good citizens. We had to kill perf for everyone just to handle the null value case, but I got an idea that makes it so performance only tanks when the array contains null values. This means you should be able to temporarily have null values without too much of a fuss. 😄

**Comment by nivarp** [comment]
Thanks @SUPERCILEX 
Let me try out the changes and report back with observations.

**Comment by SUPERCILEX** [comment]
@nivarp I'll make your life easier, just replace your current FirebaseUI database dep with this one:
```groovy
[implementation/compile] "com.github.SUPERCILEX.FirebaseUI-Android:firebase-ui-database:bf437d1f88"
```

**Comment by TheCraftKid** [comment]
@SUPERCILEX Do you upload your build of FirebaseUI to jCenter just to make testing easier? That's amazing.

**Comment by SUPERCILEX** [comment]
@TheCraftKid Haha, it's not that cool: I use [JitPack](https://jitpack.io/#SUPERCILEX/FirebaseUI-Android) which automates the building and distributing for me. 😄

**Comment by nivarp** [comment]
Thanks @SUPERCILEX : We have implemented the changes in our code and it seems to have fixed the said issue of IllegalArgumentException. However we get the following error now.

Exception java.lang.IllegalArgumentException: Key not found
 com.firebase.ui.database.FirebaseArray.getIndexForKey (FirebaseArray.java:182)
com.firebase.ui.database.FirebaseArray.onChildRemoved (FirebaseArray.java:140)
com.google.android.gms.internal.px.zza ()
com.google.android.gms.internal.vj.zzHX ()
com.google.android.gms.internal.vp.run ()
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6123)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:867)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:757)

Will create a separate ticket if you think these are unrelated.

**Comment by SUPERCILEX** [comment]
@nivarp it looks like you've customized `FirebaseArray` beyond my PR: the line numbers don't match up for either the existing codebase or the PR. Since I wasn't able to repro that issue in my PR testing, could you try using exactly the same `FirebaseArray` that's in the PR?

**Comment by nivarp** [comment]
Hi @SUPERCILEX,
Yes you are right about modifications, will use the right PR and get back with observations. Thanks again!

**Comment by SUPERCILEX** [comment]
@samtstern I think this issue can be closed since we've fixed everything we could from our side. The rest is up to the developer.
