### ISSUE TITLE
Forcefully exiting app

### ISSUE THREAD

**Issue by vidhipatel94** [firebase/FirebaseUI-Android#880]
Forcefully exiting app after opening app. Issue occurs after adding ```compile 'com.firebaseui:firebase-ui-auth:2.3.0'``` in gradle. I also added this line in gradle as specified in https://github.com/firebase/FirebaseUI-Android/tree/master/auth#configuration : 
```
defaultConfig {
     // ...
     resConfigs "auto"
  }
```
Still not working.

```
*** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
                                                           java.lang.NoSuchMethodError: No static method zza(Landroid/os/Parcel;Landroid/os/Parcelable$Creator;)Landroid/os/Parcelable; in class Lcom/google/android/gms/internal/zzeg; or its super classes (declaration of 'com.google.android.gms.internal.zzeg' appears in /data/app/app.mazadi.sd-2/base.apk:classes17.dex)
                                                               at com.google.android.gms.common.internal.zzaw.onTransact(Unknown Source)
                                                               at android.os.Binder.execTransact(Binder.java:467)
                                                               at android.os.BinderProxy.transactNative(Native Method)
                                                               at android.os.BinderProxy.transact(Binder.java:536)
                                                               at com.google.android.gms.common.internal.zzay.zza(Unknown Source)
                                                               at com.google.android.gms.common.internal.zzd.zza(Unknown Source)
                                                               at com.google.android.gms.common.api.internal.zzbw.run(Unknown Source)
                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                               at android.os.Looper.loop(Looper.java:148)
                                                               at android.os.HandlerThread.run(HandlerThread.java:61)

```

**Comment by vidhipatel94** [comment]
I was missing to add gms play services.
