### ISSUE TITLE
Google + Facebook login not working

### ISSUE THREAD

**Issue by ryandailey100** [firebase/FirebaseUI-Android#891]
Hello, I cannot get both Google and Facebook login working on my application. Email login works just fine. Whenever I press on either Google or Facebook login button, the app's onActivityResult gets called with a null result. What can be wrong? Is there anything that i could be missing? I have gone through all the steps so I am not sure what could be wrong. Please get back to me ASAP as this is whats holding me back from releasing my app. Thanks!

**Comment by SUPERCILEX** [comment]
@ryandailey100 Have you added all the xml strings with your app keys? Have you added the redirect URLs in the Firebase Auth console and keys. Have you added your SHA1 and SHA256 in the Firebase console?

**Comment by ryandailey100** [comment]
I have added the both release and debug SHA1 keys to the Firebase console. I don't think I have added the xml strings. What file do I add the strings into?

**Comment by SUPERCILEX** [comment]
@ryandailey100 See https://github.com/firebase/FirebaseUI-Android/tree/master/auth#identity-provider-configuration

**Comment by ryandailey100** [comment]
Yes I have looked at it but it does not say where to add the text

**Comment by ryandailey100** [comment]
Also that text wouldn't affect the Google sign in, as it is only for Facebook.

**Comment by SUPERCILEX** [comment]
@ryandailey100 Oh, gotya. AAPT—or Android Asset Packaging Tool—doesn't actually care where you put them. When all your resources are compiled, they're actually stored in one big `values.xml` file with everything. However, standard convention is to put them in a `config.xml` file (but again, if you'd like to put them somewhere else that makes more sense to you go for it because it won't matter).

See the sample [`config.xml`](https://github.com/firebase/FirebaseUI-Android/blob/master/app/src/main/res/values/config.xml).

**Comment by SUPERCILEX** [comment]
@ryandailey100 Yeah, for Google sign-in it should work as long as your app signing key and SHA1 match up. Can you check the logcat right after the sign-in fails? That should give us more detail as to what's going on.

**Comment by ryandailey100** [comment]
This is the error I get when pressing Google signin:
FATAL EXCEPTION: main
                                                                              Process: com.daileyproduction.collegelife, PID: 636
                                                                              java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;[Ljava/lang/String;)V in class Lcom/google/android/gms/internal/zzbga; or its super classes (declaration of 'com.google.android.gms.internal.zzbga' appears in /data/app/com.daileyproduction.collegelife-1/split_lib_dependencies_apk.apk)
                                                                                  at com.google.android.gms.auth.api.signin.internal.zze.<clinit>(Unknown Source)
                                                                                  at com.google.android.gms.auth.api.signin.internal.zze.zza(Unknown Source)
                                                                                  at com.google.android.gms.auth.api.signin.internal.zzc.getSignInIntent(Unknown Source)
                                                                                  at com.firebase.ui.auth.provider.GoogleProvider.startLogin(GoogleProvider.java:156)
                                                                                  at com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity$1.onClick(AuthMethodPickerActivity.java:127)
                                                                                  at android.view.View.performClick(View.java:5669)
                                                                                  at android.view.View$PerformClick.run(View.java:22549)
                                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6290)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by SUPERCILEX** [comment]
Oh, you're mixing play services dependencies. Make sure to use FirebaseUI `v2.3.0` and properly [override our Firebase deps](https://github.com/firebase/FirebaseUI-Android#upgrading-dependencies) if nesassary.

**Comment by ryandailey100** [comment]
Thanks so much! That did the trick. Both Facebook and Google Sign-In is now working on my app 👍 I noticed one side affect when updating Firebase Auth UI to 2.3.0. The sign-in buttons have shifted to the centre of the screen instead of the bottom. Is there anyway to place it back to the bottom?

**Comment by SUPERCILEX** [comment]
Yeah, add your app's icon with `setIcon(int)`. Otherwise we put them in the middle to minimize whitespace. See the sample:
https://github.com/firebase/FirebaseUI-Android/blob/5154ae058f5e276e87a896a78df7aa2802271997/app/src/main/java/com/firebase/uidemo/auth/AuthUiActivity.java#L201-L210

**Comment by SUPERCILEX** [comment]
Oops, it's `setLogo(int)`.

**Comment by ryandailey100** [comment]
Great! Thanks for all the help 👍

**Comment by SUPERCILEX** [comment]
NP!
