### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Activity must not be null

### ISSUE THREAD

**Issue by thelong1EU** [firebase/FirebaseUI-Android#918]
Hi!
I'm getting this error from my users through Fabric Crashlitics. Do you have any ideas why the Activity might be null?

```
Fatal Exception: java.lang.NullPointerException: Activity must not be null
       at com.google.android.gms.common.internal.zzbp.a(Unknown Source)
       at com.google.android.gms.common.api.internal.zzcf.<init>(Unknown Source)
       at com.google.android.gms.common.api.GoogleApiClient$Builder.a(Unknown Source)
       at com.firebase.ui.auth.util.signincontainer.SaveSmartLock.a(Unknown Source:219)
       at com.firebase.ui.auth.ui.HelperActivityBase.a(Unknown Source:88)
       at com.firebase.ui.auth.ui.HelperActivityBase.a(Unknown Source:76)
       at com.firebase.ui.auth.ui.idp.CredentialSignInHandler.a(Unknown Source:67)
       at com.google.android.gms.tasks.zzf.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5348)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:947)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
```

**Comment by SUPERCILEX** [comment]
@thelong1EU Ahhhh yes. Duplicate of #856. It's quite a painful bug, but we're working on it. 😄

**Comment by thelong1EU** [comment]
Sorry. Thanks for your work: :beers:
