### ISSUE TITLE
Getting this Runtime Exception -->java.lang.reflect.InvocationTargetException while using FirebaseRecyclerviewAdapter

### ISSUE THREAD

**Issue by Rao-Arsalan** [firebase/FirebaseUI-Android#935]
I'm getting an exception while using the Firebase Ui Libraray.

`E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.sumatodev.expensemanager, PID: 31330
                                                                              java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                  at com.firebase.ui.database.FirebaseRecyclerAdapter.onCreateViewHolder(FirebaseRecyclerAdapter.java:149)
                                                                                  at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5555)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                                  at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                                  at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                                  at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                                  at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                                  at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                                  at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3025)
                                                                                  at android.view.View.measure(View.java:18860)
                                                                                  at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                                  at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                                  at android.view.View.measure(View.java:18860)
                                                                                  at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1316)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                  at android.widget.ScrollView.onMeasure(ScrollView.java:353)
                                                                                  at android.view.View.measure(View.java:18860)
                                                                                  at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
                                                                                  at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
                                                                                  at android.view.View.measure(View.java:18860)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5995)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                  at android.view.View.measure(View.java:18860)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5995)
                                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                  at android.view.View.measure(View.java:18860)
                                                                                  at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1081)
                                                                                  at android.view.View.measure(View.java:18860)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5995)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                  at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                                  at android.view.View.measure(View.java:18860)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5995)
                                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                  at android.view.View.measure(View.java:18860)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5995)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                  at android.view.View.measure(View.java:18860)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5995)
                                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                  at android.view.View.measure(View.java:18860)
                                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5995)
                                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                  at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2662)
                                                                                  at android.view.View.measure(View.java:18860)
                                                                                  at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2158)
                                                                                  at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1262)
                                                                              	at androi`

the below is my code.

` public class ForwardBudgetingFragment extends Fragment {
    private static final String TAG = ForwardBudgetingFragment.class.getSimpleName();
    private RecyclerView mIncomeRv ;
    private FirebaseRecyclerAdapter<ForwardBudgetingModel,ForwardBudgetingHolder> adapter;
    Query myRefQuery;
   public static ForwardBudgetingFragment newInstance() {
        Bundle arg = new Bundle();
        ForwardBudgetingFragment fragment = new ForwardBudgetingFragment();
        fragment.setArguments(arg);
        return fragment;
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View  v = inflater.inflate(R.layout.fragment_forward_budgeting, container, false);
        

      
        mIncomeRv = (RecyclerView) v.findViewById(R.id.income_rv);

    
      
        myRefQuery = FirebaseDatabase.getInstance().getReference()
                .child("ForwardBudgeting")
                .child(FirebaseAuth.getInstance().getCurrentUser().getUid())
                .child("Income");

        adapter = new FirebaseRecyclerAdapter<ForwardBudgetingModel, ForwardBudgetingHolder>(ForwardBudgetingModel.class, R.layout.activity_add_forward_budgeting,
                ForwardBudgetingHolder.class, myRefQuery) {
            @Override
            protected void populateViewHolder(ForwardBudgetingHolder viewHolder, ForwardBudgetingModel model, int position) {

                viewHolder.setmTransactionAmount(FormatterAmount.getAmountsWithInsertedCommas(Double.parseDouble(model.getAmount())), model.getTransactionType());
                viewHolder.setmTransactionName(model.getName());
                viewHolder.setC(getContext());
                viewHolder.setId(model.getId());
                Log.i(TAG,model.getName()+" : "+model.getId()+" : "+getContext()+" : "+getActivity().getApplicationContext());

            }

        };
        mIncomeRv.setLayoutManager(new LinearLayoutManager(getContext()));
       
        mIncomeRv.setAdapter(adapter);

      
        return v;
    }
   
}

Here is my Holder Class

public class ForwardBudgetingHolder extends RecyclerView.ViewHolder {

    //hold actual data
    String transactionType;
    String id;

    private TextView mTransactionName;
    private TextView mTransactionAmount;
    private Button mTransactionEdit, mTransactionDelete;
    private Context c;

    public ForwardBudgetingHolder(View itemView) {
        super(itemView);
       
        mTransactionAmount = (TextView) itemView.findViewById(R.id.transactionAmount);
        mTransactionName = (TextView) itemView.findViewById(R.id.transactionName);
       
      
          
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Context getC() {
        return c;
    }

    public void setC(Context c) {
        this.c = c;
    }

    public TextView getmTransactionName() {
        return mTransactionName;
    }

    public void setmTransactionName(String mTransactionName) {
        this.mTransactionName.setText(mTransactionName);
    }

    public TextView getmTransactionAmount() {
        return mTransactionAmount;
    }

    public void setmTransactionAmount(String mTransactionAmount, String transactionType) {
        this.mTransactionAmount.setText(mTransactionAmount);
        this.transactionType = transactionType;
    }

   
}
`

Here is my Holder Class

`public class ForwardBudgetingHolder extends RecyclerView.ViewHolder {

    //hold actual data
    String transactionType;
    String id;

    private TextView mTransactionName;
    private TextView mTransactionAmount;
    private Button mTransactionEdit, mTransactionDelete;
    private Context c;

    public ForwardBudgetingHolder(View itemView) {
        super(itemView);
       
        mTransactionAmount = (TextView) itemView.findViewById(R.id.transactionAmount);
        mTransactionName = (TextView) itemView.findViewById(R.id.transactionName);
       
      
          
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Context getC() {
        return c;
    }

    public void setC(Context c) {
        this.c = c;
    }

    public TextView getmTransactionName() {
        return mTransactionName;
    }

    public void setmTransactionName(String mTransactionName) {
        this.mTransactionName.setText(mTransactionName);
    }

    public TextView getmTransactionAmount() {
        return mTransactionAmount;
    }

    public void setmTransactionAmount(String mTransactionAmount, String transactionType) {
        this.mTransactionAmount.setText(mTransactionAmount);
        this.transactionType = transactionType;
    }

   
}`

please solve it i try to find on stackoverflow and also do google but can't find desired result.

**Comment by samtstern** [comment]
@Rao-Arsalan there's  **a lot** of code here and it may be too much for us to debug.  However we just released version `3.0.0` which does not use reflection anymore and I bet your problem will be solved.  Could you follow the upgrade guide (see the README) and see if the new version fixes your problem?

**Comment by Rao-Arsalan** [comment]
@samtstern  when i'm converting my Firebase UI version 2.0.1 to 3.0.0 my gradle showing ton's of error.
which i'm trying to solve this but can't solve this.

**Comment by waqas117** [comment]
@Rao-Arsalan You have to apply these options

1: make default non parameter constructor in your Model
2:create your adapter in onActivityCreated
3:uninstall app from your device then install and test
4:work for some times **Clear your studio cache**

**Comment by Rao-Arsalan** [comment]
@waqas117  i tried alot as you describe but getting failed.

**Comment by waqas117** [comment]
@Rao-Arsalan Do you think your R.layout.activity_add_forward_budgeting is correct layout for using your Holder??

**Comment by Rao-Arsalan** [comment]
@waqas117 yeah i put wrong layout file instead of correct layout..
thanks man it's worked fine.
