### ISSUE TITLE
RecyclerView  InvocationTargetException

### ISSUE THREAD

**Issue by borjaruiz** [firebase/FirebaseUI-Android#94]
App is crashing in this sentence.
I've followed the example code. The difference is that I use it in a fragment instead of in an Activity.
I've tried putting ChatHolder as public and also putting it as static inside the fragment. Same error in both.

FirebaseRecyclerAdapter<Chat, ChatHolder> adapter = new FirebaseRecyclerAdapter<Chat, ChatHolder>(Chat.class, R.layout.row_mensaje, ChatHolder.class, mChat){
            @Override
            protected void populateViewHolder(ChatHolder viewHolder, Chat model, int position) {
             }
};

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                             at com.apptest.Firebase.FirebaseRecyclerAdapter.onCreateViewHolder(FirebaseRecyclerAdapter.java:181)
                                                                             at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5476)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4701)
                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4611)
                                                                             at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1988)
                                                                             at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1384)
                                                                             at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1347)
                                                                             at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
                                                                             at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3026)
                                                                             at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2903)
                                                                             at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3277)
                                                                             at android.view.View.layout(View.java:15686)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
                                                                             at android.view.View.layout(View.java:15686)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                             at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                             at android.view.View.layout(View.java:15686)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
                                                                             at android.view.View.layout(View.java:15686)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
                                                                             at android.view.View.layout(View.java:15686)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                             at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                             at android.view.View.layout(View.java:15686)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1183)
                                                                             at android.view.View.layout(View.java:15686)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                             at android.view.View.layout(View.java:15686)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                             at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                             at android.view.View.layout(View.java:15686)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                             at android.view.View.layout(View.java:15686)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                             at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                             at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                             at android.view.View.layout(View.java:15686)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                             at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                             at android.view.View.layout(View.java:15686)
                                                                             at android.view.ViewGroup.layout(ViewGroup.java:5039)
                                                                             at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
                                                                             at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)

**Comment by puf** [comment]
This is the code that raises the exception.
```
Constructor<VH> constructor = mViewHolderClass.getConstructor(View.class);
return constructor.newInstance(view); ```
So it looks like you're missing a necessary constructior

On Mon, Mar 14, 2016 at 6:00 AM borjaruiz <notifications@github.com> wrote:

> App is crashing in this sentence.
> I've followed the example code. The difference is that I use it in a
> fragment instead of in an Activity.
> I've tried putting ChatHolder as public and also putting it as static
> inside the fragment. Same error in both.
>
> FirebaseRecyclerAdapter adapter = new FirebaseRecyclerAdapter(Chat.class,
> R.layout.row_mensaje, ChatHolder.class, mChat){
> @Override <https://github.com/Override>
> protected void populateViewHolder(ChatHolder viewHolder, Chat model, int
> position) {
> }
> };
>
> java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
> at
> com.apptest.Firebase.FirebaseRecyclerAdapter.onCreateViewHolder(FirebaseRecyclerAdapter.java:181)
> at
> android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5476)
> at
> android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4701)
> at
> android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4611)
> at
> android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1988)
> at
> android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1384)
> at
> android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1347)
> at
> android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:574)
> at
> android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3026)
> at
> android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2903)
> at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3277)
> at android.view.View.layout(View.java:15686)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
> at android.view.View.layout(View.java:15686)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
> at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
> at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
> at android.view.View.layout(View.java:15686)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
> at android.view.View.layout(View.java:15686)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
> at android.view.View.layout(View.java:15686)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
> at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
> at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
> at android.view.View.layout(View.java:15686)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1183)
> at android.view.View.layout(View.java:15686)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
> at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
> at android.view.View.layout(View.java:15686)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
> at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
> at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
> at android.view.View.layout(View.java:15686)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
> at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
> at android.view.View.layout(View.java:15686)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
> at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
> at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
> at android.view.View.layout(View.java:15686)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
> at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
> at android.view.View.layout(View.java:15686)
> at android.view.ViewGroup.layout(ViewGroup.java:5039)
> at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
> at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/firebase/FirebaseUI-Android/issues/94>.
>

**Comment by borjaruiz** [comment]
My ViewHolder and my RecyclerView code are like the example. Which constructor am I missing? Thanks for your reply.

`public class ChatHolder extends RecyclerView.ViewHolder {
        View mView;
        RelativeLayout relative_body = (RelativeLayout) mView.findViewById(R.id.relative_body);
        TextView body = (TextView) mView.findViewById(R.id.tvBody);
    
        public ChatHolder(View itemView) {
            super(itemView);
            mView = itemView;
        }
...
}
`
