### ISSUE TITLE
problem with Facebook login using Firebase UI 3.0 and Facebook SDK 4.27.0

### ISSUE THREAD

**Issue by LeeHounshell** [firebase/FirebaseUI-Android#966]
I have been using Facebook with Firebase UI for a while now.  Mostly it has been working fine for me.
With the recent Firebase UI 3.0 I have an issue logging into Facebook and see the following in my log:

10-11 08:40:25.481 22216-22216/? W/Bundle: Key error_code expected String but value was a java.lang.Integer.  The default value <null> was returned.
10-11 08:40:25.491 1518-1518/? D/InputMethodFrameWorkUtils: InputMethodSubtype is found as local:en_US
10-11 08:40:25.491 1518-1518/? W/ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1748 android.content.ContextWrapper.sendBroadcast:392 com.sec.android.inputmethod.inputmethodframework.InputMethodFrameWorkUtils.setCurrentInputMethodSubtype:49 com.ime.framework.common.InputManagerImpl.finishInput:5042 com.sec.android.inputmethod.SamsungKeypad.onFinishInput:665 
10-11 08:40:25.491 22216-22216/? W/Bundle: Attempt to cast generated internal exception:
                                           java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
                                               at android.os.BaseBundle.getString(BaseBundle.java:921)
                                               at com.facebook.login.NativeAppLoginMethodHandler.handleResultOk(NativeAppLoginMethodHandler.java:78)
                                               at com.facebook.login.NativeAppLoginMethodHandler.onActivityResult(NativeAppLoginMethodHandler.java:64)
                                               at com.facebook.login.LoginClient.onActivityResult(LoginClient.java:146)
                                               at com.facebook.login.LoginFragment.onActivityResult(LoginFragment.java:169)
                                               at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:149)
                                               at android.app.Activity.dispatchActivityResult(Activity.java:6867)
                                               at android.app.ActivityThread.deliverResults(ActivityThread.java:4751)
                                               at android.app.ActivityThread.handleSendResult(ActivityThread.java:4798)
                                               at android.app.ActivityThread.access$1500(ActivityThread.java:219)
                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1784)
                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                               at android.os.Looper.loop(Looper.java:145)
                                               at android.app.ActivityThread.main(ActivityThread.java:6939)
                                               at java.lang.reflect.Method.invoke(Native Method)
                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

Has anyone else come across this issue?
Any chance this is related to the new 3.0 Firebase UI?

Thanks

**Comment by LeeHounshell** [comment]
I also found this in the log:

10-11 08:40:25.641 22216-22216/? E/FacebookProvider: Error logging in with Facebook. SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]: Errors while executing operation "ProxyAuthAppLoginStartQuery": At Query.proxy_auth_app_login_start: Failed to resolve field.
1

**Comment by LeeHounshell** [comment]
I tried reverting to Firebase UI 2.3.0 and Facebook 4.26.0 and the problem persists.  I am concluding that something else is causing my issue and closing this.

**Comment by cutiko** [comment]
Maybe this thread can help you https://github.com/firebase/FirebaseUI-Android/issues/933

**Comment by LeeHounshell** [comment]
This problem just stopped.  I have no idea why.  but now the same code as before is not failing Facebook login.

**Comment by mitesh-shah** [comment]
@LeeHounshell I have just created a new app and added a login with facebook functionality via firebase and facing exactly the same issue as you have mentioned in the beginning of this thread (in logs).

Would you mind helping me out here with possible solutions?

**Comment by mariolourobert** [comment]
@mitesh-shah I have the same 1675030 issue with a FB Login. Have you find a solution ?
Thx

**Comment by mitesh-shah** [comment]
@mariolourobert No, I tried with Facebook SDK and it is working for me.

**Comment by mlegy** [comment]
When you use this command

    keytool -exportcert -alias androiddebugkey -keystore ~/.android/debug.keystore | openssl sha1 -binary | openssl base64

to get the key hashes you put in facebook configurations, it will ask you for a password, make sure you enter `android` as the password.
