### ISSUE TITLE
 java.lang.RuntimeException: where google account is not added in phone

### ISSUE THREAD

**Issue by gautam2682** [firebase/FirebaseUI-Android#994]
* Android device: genymotion emulator
  * Android OS version: 4.4
  * Google Play Services version: 11.4.2
  * Firebase/Play Services SDK version: 11.4.2
  * FirebaseUI version: 3.1.0
  
Here is logcat :- 
```
10-28 09:15:24.261 4257-4257/com.cbs.sscbs E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.cbs.sscbs, PID: 4257
                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cbs.sscbs/com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f080086
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:136)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                              Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f080086
                                                                 at android.content.res.Resources.getValue(Resources.java:1123)
                                                                 at android.support.v7.widget.ResourcesWrapper.getValue(ResourcesWrapper.java:208)
                                                                 at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:330)
                                                                 at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
                                                                 at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:188)
                                                                 at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
                                                                 at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:85)
                                                                 at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:94)
                                                                 at com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity.onCreate(AuthMethodPickerActivity.java:95)
                                                                 at android.app.Activity.performCreate(Activity.java:5231)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                                 at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                 at android.os.Looper.loop(Looper.java:136) 
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                 at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                 at dalvik.system.NativeStart.main(Native Method) 
```

When sign in button is clicked in genymotion emulator where google account is not set up it automatically stopped , but does not stop when i set checked to false for google provider in xml, but i need google account to sign up for all devices . please solve this error.

**Comment by Kampeone** [comment]
how did you fixed this?
